Alexays/Waybar

src/modules/clock.cpp
src/modules/cpu.cpp
src/modules/memory.cpp

```
clock {
"interval": 1,
"format": "{:%H:%M:%M"},
...
}
```
Caused the Waybar to use 100% CPU.
This was caused by `interval` not being set properly due to a typo.
Possibly also fixes #47

fix custom intervals causing cpu to go mental

---

meson.build
protocol/meson.build

Add the required `gio-unix-2.0`.
Is it only needed when using dbusmenu?

meson: fix 'gio-unix-2.0' dependency

---

include/modules/sway/ipc/client.hpp

Trying to package it for Void Linux (https://github.com/void-linux/void-packages/pull/4207) which has musl libc variants results in this error with sway enabled.
[Full log from Travis](https://travis-ci.org/maxice8/UnlimitedPullRequestWorks/jobs/447311047)
```
I/usr/include/libdbusmenu-glib-0.4 -flto -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -std=c++17 -DHAVE_SWAY -DHAVE_LIBPULSE -DHAVE_DBUSMENU -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -D_REENTRANT -pthread  -MD -MQ 'waybar@exe/src_modules_sway_ipc_client.cpp.o' -MF 'waybar@exe/src_modules_sway_ipc_client.cpp.o.d' -o 'waybar@exe/src_modules_sway_ipc_client.cpp.o' -c ../src/modules/sway/ipc/client.cpp
../src/modules/sway/ipc/client.cpp: In member function 'int waybar::modules::sway::Ipc::open(const string&) const': …
```

add missing <cstring> include for strncpy, fixes musl

---

include/ALabel.hpp
include/modules/pulseaudio.hpp
include/util/command.hpp
src/ALabel.cpp
src/modules/pulseaudio.cpp

Subscribe for mouse scroll events on the pulseaudio widget
and change volume when event is received.
Scroll up increments the volume and scroll down decrements it.
Signed-off-by: Harish Krupo <harishkrupo@gmail.com>

Add configuration options for widgets on mouse events

---

include/modules/battery.hpp
src/modules/battery.cpp

Full battery status should also bet set as a class.
Additionally, users can configure the battery module such that an "Unknown" status is interpreted as "Full", because that's how some notebooks behave (e.g. Thinkpad T430s. Yup, that's the one I use ^^).

Add class for full battery and give option to interpret unknown as full

---

include/modules/battery.hpp
include/modules/sni/sni.hpp
meson.build
meson_options.txt
src/modules/sni/sni.cpp

For gcc-7, filesystem still lives in the experimental namespace, thus compilation will fail. I have added an option to meson to fix the header includes and namespaces accordingly.

add option for when filesystem still lives in the experimental namespace

---

src/bar.cpp

Calling `set_exclusive_zone` and `set_size` with the values provided by the compositor in a configure will actually freeze the bar in the new configuration it requested, as calling those with non-zero values opts-out of autoconfiguration by the compositor.
By removing these calls, waybar can now adapt to dynamic changes in the output dimensions, which can happen for example if the monitor's transform is changed (like for a tablet-like device auto-detecting its orientation).

Don't call layer_surface.set_size on configure

---

include/modules/sway/workspaces.hpp
src/modules/sway/workspaces.cpp

The way waybar used the workspace "num", clicking a workspace called "1:
something" resulted in going to a newly created workspace called "1",
because the workspace ipc command expects the workspace name, not its number.

Fix clicking and scrolling through workspaces

---

src/modules/sway/workspaces.cpp

And another one :D 
Now only the ordering of the workspaces has to be fixed if all-outputs == true.

Fix workspaces not being removed from bar when moved to another output

---

include/modules/cpu.hpp
src/modules/cpu.cpp

This PR fixes the cpu load readings, which are way off in `sysinfo`
Also the individual cores get displayed in the tooltip

Use /proc/stat for cpu load

---

include/modules/network.hpp
resources/config
src/modules/network.cpp

This PR adds the ability to display the IP address, as well as the subnet mask (also in CIDR notation).
The following format replacements will get added:
| string      | replacement |
| --- | --- |
| `{ipaddr}`  | The first IP of the interface. |
| `{netmask}` | The subnetmask corresponding to the IP. |
| `{cidr}`    | The subnetmask corresponding to the IP in CIDR notation. |
And while we are at it, the following format replacement is missing from network:
| string      | replacement |
| --- | --- |
| `{signaldBm}`  | Signal strenth of the wireless network in dBm. |

Module network ipaddr

---

src/modules/custom.cpp

This can be quite useful to simply add a button to the bar that executes some script on click, for example to control a mediaplayer.

Allow custom plugins that don't execute anything

---

resources/config
resources/custom_modules/mediaplayer.py
resources/custom_modules/mediaplayer.sh

For personal use I created an event based python script based on playerctl to use with the custom module. Currently it's specifically for Spotify.
I thought this might be useful for other users, and an improvement over the current delayWorker script.
Is this something we should work towards merging?
Current requirements:
playerctl > 2.0
python-gobject

Event based mediaplayer script

---

src/modules/sway/ipc/client.cpp

Fixes #109 by checking for old and new IPC response formats. Works with swaywm/sway@9d18d81

Update to new Sway IPC protocol

---

src/ALabel.cpp
src/modules/network.cpp

This adds the ability to set format icons similar to the pulseaudio module.
A config for this could look like this (Needs FontAwesome Pro):
```
"format": "{icon}",
"format-icons": {
"wifi": ["", "" ,""],
"ethernet": [""],
"disconnected": [""] 
}
```
Also if fixes getIcon() in ALabel.

Use SignalStrength for format icons

---

include/modules/custom.hpp
src/modules/custom.cpp

This commit allows custom modules (json only) to set a percentage. This can be displayed either by using `{percentage}` or by using `{icon}` with `format-icons` set.
```
| option           | typeof  | default | description |
| `format`         | string  | `{}`    | The format, how information should be displayed. On `{}` data gets inserted. |
| `format-icons`   | array   |         | Based on the set percentage, the corresponding icon gets selected.<br>The order is *low* to *high*. |
| string | replacement |
| --- | --- |
| `{}` | Output of the script. |
| `{percentage}` | Percentage wich can be set via a json return-type. |
| `{icon}` | An icon from 'format-icons' according to percentage. |
```

Add format-icons to custom module

---

include/ALabel.hpp
include/IModule.hpp
include/bar.hpp
include/modules/sni/host.hpp
include/modules/sni/item.hpp
include/modules/sni/watcher.hpp
include/modules/sway/workspaces.hpp
include/util/chrono.hpp
include/util/command.hpp

Replaces all occurences of `#include <gtkmm.h>` with only ne neccesary headers

refactor: replace all gtkmm.h includes

---

src/modules/sway/window.cpp

With this, the window title `waybar` will be ignored so it won't flicker as decribed in #148.
Regarding the hiding of tooltips, i think this belongs in another pull (together with formating tooltips like module text).

fix(window): Ignore waybar

---

include/factory.hpp
include/modules/backlight.hpp
meson.build
meson_options.txt
resources/config
resources/style.css
src/factory.cpp
src/modules/backlight.cpp

Monitor the backlight level via udev. Poll every `interval` as well,
in case backlight udev events aren't supported.
- Should this be enabled in the default config?
- Should this be `#ifdef`'d depending on `libudev` availability?
- My laptop doesn't send udev events for backlight change, so it would be nice if someone with one that does could test that.

Add backlight module

---

include/bar.hpp
include/client.hpp
include/factory.hpp
include/modules/idle_inhibitor.hpp
meson.build
protocol/meson.build
resources/config
resources/style.css
src/client.cpp
src/factory.cpp
src/modules/idle_inhibitor.cpp

This patch adds a module to simulate user action, so the lockscreen won't be started.
I tested it only with swayidle, but it uses the idle inhibit protocol and should work with others programs.

Add module Idle inhibitor

---

resources/config
src/ALabel.cpp
src/modules/clock.cpp

I wanted the ability to see the current date when I hover my mouse over the clock module.
Adds the following settings:
- clock/tooltip
- clock/tooltip-format (default is same as normal format)

Added clock tooltip with optional alternate format

---

include/modules/backlight.hpp
src/modules/backlight.cpp

The backlight modules does not allow the use of `format-alt` prior to this change.

fix(backlight) Allow format-alt

---

include/modules/backlight.hpp
src/modules/backlight.cpp

`Backlight#devices_` was being destructed before
`Backlight#udev_thread_`. Also check if thread is still running after
`epoll_wait`.
Fixes #188. @jonfin, could you test?

Fix crash when monitor unplugged

---

include/modules/custom.hpp
src/modules/custom.cpp

Just a small change that adds an additional string field to the custom module, so `format-alt` can be utilized better.
Maybe this should be touched again when tackeling #100

feat(custom): Add field for additional data to json

---

include/ALabel.hpp
include/modules/idle_inhibitor.hpp
src/modules/idle_inhibitor.cpp

The idle inhibitor module won't work if any click event is specified in the config. Because the click event handler of the idle inhibitor module is not activated. 
- Declare event handler in ALabel virtual so the idle_inhibitor can overriding them
- Handle the left click event in idle_inhibitor and call ALabel handler if needed
It should not conflict with #204.

[bugfix] idle_inhibitor: handle click events correctly

---

src/modules/sway/ipc/client.cpp

Waybar from my Fedora package has been crashing with following assertion:
`/usr/include/c++/8/bits/basic_string.h:1067: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11:      :basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _All      oc>::reference = char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.`
The crash happens because std::string.reserve() does not change string size, leaving it as 0. And all further modifications of string.data() are actually happening out of range. …

 fix(sway): ipc client crash when compiled with -D_GLIBCXX_ASSERTIONS 

---

src/modules/pulseaudio.cpp

Pulseaudio ports names in my setup are starting with capital letter:
```
% pacmd list-sinks |grep '\[Out\]'
[Out] Speaker: Speaker playback (priority 100, latency offset 0 usec, available: no)
[Out] Headphones: Headphones playback (priority 100, latency offset 0 usec, available: yes)
active port: <[Out] Headphones>
```
Because of that waybar::modules::Pulseaudio::getPortIcon() fails to select "headphones" icon for "Headphones" port and returns "phone" as the only matching icon.
The second commit is a small optimization: it saves a few CPU cycles per call on allocation of vector and all these strings.

fix(pulseaudio) use case-insensitive comparison for icon lookup

---

include/bar.hpp
include/modules/custom.hpp
include/util/sleeper_thread.hpp
src/ALabel.cpp
src/bar.cpp
src/main.cpp
src/modules/custom.cpp

This implements pkill signals for custom modules (see #170). You can define it with `"signal"` in the config and test it with `pkill -RTMIN+8 waybar` (for example signal 8). 
In addition there is now also the setting `"interval": "once"`, to load the module only once at startup.
edit: I already updated the [wiki](https://github.com/Alexays/Waybar/wiki/Module:-Custom) for this PR. I didn't know they were directly live. If you need time for the review, I can reverse it. Just let me know.

Add pkill signals to custom modules

---

src/modules/network.cpp

As detailed in #240, ESSIDs with characters like `&` were causing the network widget to break when connected to those networks. This PR fixes it by using `Glib::Markup::escape_text` before interpreting as pango.

Fix #240: Escape ESSID text before interpreting as pango

---

src/modules/custom.cpp

Because getIcon() has logic to test if format-icon is an array or a dictionary, it is possible to also pass alt_ to this function.

[custom] Allow icon selection based on json alt attribute

---

include/modules/sni/item.hpp
src/modules/sni/item.cpp

A functional but not quite finished implementation of update signals subscription for SNI::Item. Also changes most of dbus code in the class to use giomm wrappers because raw gdbus API is a pain to use.
I'm still not happy with the way updateImage could be invoked multiple times for each NewIcon signal. Ideally there should be some kind of batch update, and I'm considering if it's better to call GetAll and emulate PropertiesChanged signal. Going to give it a try on the weekend.

Process tray icon updates

---

resources/custom_modules/mediaplayer.py

And here is the feature itself. I verified that it work in my usecases. But yours might be different. If you don't mind testing it first that would be awesome.
This branch is based on my branch from my other PRs (#249, #250) as I needed command line arguments to implement this.

Feature select player

---

.clang-format
.editorconfig
README.md
include/factory.hpp
include/modules/mpd.hpp
meson.build
meson_options.txt
resources/config
resources/style.css
src/factory.cpp
src/modules/mpd.cpp

This adds a basic MPD module, somewhat based on Polybar's implementation.
Also adds a minimal [EditorConfig](https://editorconfig.org/) so editors picks up the codebase's style. ~~(Maybe a `.clang_format` would be nice too but I don't think I should be the one choosing the style. See [here](https://zed0.co.uk/clang-format-configurator/) if you're interested)~~
Clang format configuration added!
**Don't merge now** I'm currently trying to also add support for options (shuffle, repeat, etc.). I'm putting it here now so I pick up on recommendations/reviews as soon as possible ^^
Features:
- artist, album-artist, album, title, and date in the label
- format, format-stopped, and format-disconnected depending on this module's state
- Event driven updates (so fast!)
- Automatic reconnect …

Add MPD support

---

src/modules/mpd.cpp

The idea comes from #273 but doesn't fix it (I haven't managed to crash the bar yet)
This still doesn't support the `escape` configuration, the rationale is that:
- Users probably won't modify the song metadata to change the style of Waybar's MPD module
- The rest of the format replacements comes from the configuration and can be escaped there directly

fix(mpd): Escape MPD values in the label

---

include/modules/mpd.hpp
resources/config
src/modules/mpd.cpp

Because `mpd_song_get_tag` from libmpdclient can return NULL, verify the
value of tag is valid. Otherwise, set a default string of "N/A". Also
adds configuration to specify what this default string should be.
Additionally, fix compile-time warning of catch by value.
Closes #273 (I'll file another issue on the segfault at `mpd_status_get_state`,
unless we want to keep conversation there)
P.S. Thoughts appreciated on the config name `"unknown-tag"`; for some
reason it just doesn't jive with me, though it's fairly descriptive of what it does.
I'll update the wiki once this gets merged.
EDIT: It appears you guys are using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) style (or
something similar). Should I fix my commits to reflect that?

Ensure no NULL tags are set

---

include/modules/mpd.hpp
src/modules/mpd.cpp

Finally got to the bottom of this!
Didn't manage to find a way to "unblock" the event listener, so here's what I propose (from the commit message):
The MPD server has a `connection_timeout` that defaults to 60. If no data
is transferred in this time span, the connection is closed. If the
connection is closed while the event listener thread is listening for events,
it will block forever. By timing out the event listening and
re-connecting regularly, we prevent this issue. An option "timeout" has
been added for users that have a lower server `connection_timeout` than
default. Fixes #277

fix(mpd): regularly timeout the event listener to prevent timeout

---

src/ALabel.cpp

This change allows rotation of label contents, which can be useful when using a vertical bar.
See:

Allow rotating label contents by specifying a new "rotate" property 

---

src/modules/battery.cpp

It seems like there is a mistaken comparison expression where an assignment statement should be used instead. See the commit for the single line which I am referring to.

fix(battery): change comparison expr. to assignment

---

resources/config
src/modules/pulseaudio.cpp

Fixes https://github.com/Alexays/Waybar/issues/301
~~`scroll-step` is probably not what most people want, but kept it for backwards compatibility. `scroll-step-percent = 1` is now effectively the same as `scroll-step = 6.5535`.~~
`scroll-step = 1` ≈ 1% now.
Better alignment with the percentage ticks could be achieved (by calculating the change needed to reach the next tick, instead of adding the same number every time), but eh, negligible, IMO.
Let me know if you're happy with the API, I'll update the wiki.

Change scroll-step unit to percent

---

src/modules/sway/workspaces.cpp

Scrolling off the rear end of the list should advance to the first element, not the second in the list.

Fix workspace scroll wrapping off the end of the list

---

include/modules/network.hpp
src/modules/network.cpp

This PR adds support for 4 new tags for the network modules:
* `{bandwidthDownBits}` and `{bandwidthUpBits}`
* `{bandwidthDownOctets}` and `{bandwidthUpOctets}`
Those tags, in combination with the `{interval}` tag, allows users to monitor ongoing network traffic
As of current state, this PR implements those only for linux, but I tried to make it easy to add support for FreeBSD
As I am not running under FreeBSD, I'd rather have some FreeBSD dude add this part. FreeBSD implementation can apparently be done using the [/proc/net/dev](https://www.freebsd.org/cgi/man.cgi?query=proc&apropos=0&sektion=5&manpath=CentOS+7.1&arch=default&format=html) file
If no one is willing to implement this, then I'll go ahead and try to implement it, though I won't be able to test it and would as such like to …

Adding bandwidth support for network module

---

src/modules/backlight.cpp

replaced `actual_backlight` with `backlight``

backlight: fix for percentage output for amdgpu_bl0 device

---

src/modules/memory.cpp

This adds named format parameters while keeping existing formats using `{}` working.

Allow formatting memory with used and available memory

---

include/modules/sway/workspaces.hpp
src/modules/sway/workspaces.cpp

Implements https://github.com/Alexays/Waybar/issues/210
Adds the `persistant_workspaces` option to the module `sway/workspaces`.
Within `persistant_workspaces`, you can list workspaces that should always be showed, even when non existant as per sway. It is possible to indicate which outputs they should be displayed on ; if no output was indicated, it will display on all outputs.
example:
```
"sway/workspaces": {
"persistant_workspaces": {
"3": [], // Always show a workspace with name '3', on all outputs if it does not exists
"4": ["eDP-1"], // Always show a workspace with name '4', on output 'eDP-1' if it does not exists
"5": ["eDP-1", "DP-2"] // Always show a workspace with name '5', on outputs 'eDP-1' and 'DP-2' if it does not exists
}
}
```
Known issue: upon clicking on a non-existing …

Adding sway/workspaces:persistant_workspaces

---

src/modules/clock.cpp

I don't understand why these two clocks disagree, but they do, and this way always seems to update the second exactly on time.

Fix clock is always a second off

---

include/modules/battery.hpp
src/modules/battery.cpp

Linear estimate like `upower`.
Also removed `current` variables as they are not used since 17291dffdf623f21fe9902d59a0cf90b4f6a594e

Estimate of time remaining until empty|full on tooltip

---

resources/style.css

Because of CSS specificity rules, the `#custom-media` style will always override the `custom-spotify` and `custom-vlc` styles, so the background of the media element is always green rather than sometimes orange when VLC is running. I added `#custom-media` in front of each of the class selectors to increase their specificity so they take precedence.

Increase specificity of media stylings

---

src/bar.cpp

now you can have a custom styling for each bar. this wasn't possible before, since every bar defined the same set of ids and classes.
also question:
the height/width parameters are useless inside of the css file. i noticed the width and height were being set via a different api. is there any way we can set this to "auto" so the css can take precedence over the width/height of the bar?

adds the wl output name as a css class

---

include/ALabel.hpp
include/modules/sway/workspaces.hpp
src/ALabel.cpp
src/modules/sway/workspaces.cpp

Previously, any and all scroll events were interpreted as reason to switch
workspaces. This resulted in twitchy behaviour, where the scrolling was
practically unusable.
Now, we pool all scroll values, and only scroll if the value is larger than the
new config option "smooth-scrolling-threshold". If this option is not set, the
behaviour is unchanged.

Fix twitchy scrolling on touchpads

---

src/modules/memory.cpp

I would like to be able to see the memory usage expressed like `3.3G / 8.0G`, which is not possible at the moment. This PR solves this.
I also noticed that there is no option to display the swap values. If you agree, I'd like to make a PR for that as well.
Note: Wiki page needs to be updated if this gets merged.

Expose total memory to the formatting directive

---

src/bar.cpp

- Adds `name` property for each bar and uses this as a CSS class
- Adds CSS class for the position property
When using multiple waybars from the same configuration file (https://github.com/Alexays/Waybar/issues/267) it can be preferable to style them individually.
E.g For a bar at the bottom of the screen the `border-bottom` might be better at the top, or a specific named bar might want to have a different background colour.

Allow CSS to select specific waybars when multiple are in use

---

src/modules/sway/workspaces.cpp

Make the mutex guard lifecycle finish before the send ipc command
by adding scope around the code.
Fixes #395

Fix deadlock on workspace scrolling

---

resources/config
resources/custom_modules/mediaplayer.py

When the command line argument `--player <name>` is not defined, custom module is not picking up new players.
Also added example usage of argument to config.

 fix(custom): ignore selected_player if not defined. Fixes #419 

---

resources/config
src/modules/pulseaudio.cpp

This adds the format-bluetooth-muted option to handle muted bluetooth audio as described in #420.
If no format-bluetooth-muted entry is present, the "format" fallback is used like it was before.

add support for muted bluetooth audio, fix #420

---

src/modules/network.cpp
src/modules/sni/host.cpp

```
==587==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f22313f0084 at pc 0x000000778010 bp 0x7f22132c27d0 sp 0x7f22132c27c8
READ of size 4 at 0x7f22313f0084 thread T11
#0 0x77800f in waybar::modules::Network::worker()::$_1::operator()() const /home/alebastr/sources/Waybar/build-asan/../src/modules/network.cpp:117:28
#1 0x7777ec in std::_Function_handler<void (), waybar::modules::Network::worker()::$_1>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/std_function.h:297:2
#2 0x5f5a68 in std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/std_function.h:687:14
#3 0x5f58aa in waybar::util::SleeperThread::operator=(std::function<void …
```

fix(network): stack-use-after-return found by address sanitizer

---

src/modules/sway/mode.cpp

Closes #435.
IPC reports `{"mode": "mode_string", "pango_markup": bool}` on mode change.
Use this to conditionally enable pango markup.

sway/mode: enable pango markup on supported modes

---

include/bar.hpp
src/bar.cpp

Fix some issues with exclusive zones and margins:
- exclusive zone did not include margins after toggling bar
- exclusive zone included incorrect margin when bar is anchored at bottom or right edge
- margins were incorrectly applied over anchored axis (see comment in setSurfaceSize)
There are some remaining issues with specifying size for anchored axis that may require decoupling window size from layer surface size. For now let's just pretend that this works as expected :see_no_evil:

Fix some issues with exclusive zone and margins

---

man/waybar-battery.5.scd
src/modules/battery.cpp

Adds a `format-time` configuration for the battery module so that users
can configure how they want their remaining time to be displayed.
The default format remains the same as before, i.e. `{H} h {M} min`,
but users can choose something like `{H}:{M:02d}` to give an output
like `4:29` if wanted.

Add configurable time display for battery module

---

meson.build
meson_options.txt
resources/waybar.service

add a systemd --user unit/service file, so that one can run waybar as a
--user systemd service.
this feature is automatically enabled if systemd is found, but can be disabled
with -Dsystemd=disabled

install a systemd user service unit

---

meson.build
resources/waybar.service.in

ie. don't assume waybar is always gonna be installed in `/usr/bin/waybar`

service file: allow for waybar installed in different prefix

---

resources/style.css

In the default style.css many modules (clock, battery, cpu, ...) get horizontal padding, but mpd module does not. This commit adds mpd to the list of modules that get the padding.
Before:
After:

add padding for mpd module in default style

---

include/modules/mpd.hpp
src/modules/mpd.cpp

This PR aims to solve issue #281 by taking the `connection_lock_` in `waitForEvent()`.
Additionally, I observed that multiple `periodic_updater`s could be running.
This happens when mpd is playing and no events happen.
This causes the mpd connection to drop when `mpd_recv_idle` times out.
If the current `periodic_updater` is sleeping at this moment, `update` will run and start a new one,
while the current one will also continue running (there is a new connection to mpd at this moment, so it sees no reason to stop). Adding a mutex to make sure `update` only continues when the current `periodic_updater` has stopped, fixes this.
It would be nice if more people could try out this code, since I'm not sure #281 is solved by  this, maybe it just happens more infrequently.

Add more locking in mpd module

---

src/modules/clock.cpp

Fixes #479, because upstream does not intend to.
It may be less expensive to do that only once in a while, or to inotify-watch on /etc/timezone, but this is good enough.

Detect timezone changes

---

include/AModule.hpp
src/AModule.cpp

The `fmt::format()` function looks for the `{arg}` named argument in the given "format" string which does not exist. It will fail if the string contains any `{...}` curled-brace substring.
Consequently, any `on-click*` option's command line containing for instance substring like `${var}` or `awk '{...}'` will crash the program.

fix: No need to format string with unused 'arg' named argument (#484)

---

include/bar.hpp
include/client.hpp
meson.build
meson_options.txt
src/bar.cpp
src/client.cpp
subprojects/gtk-layer-shell.wrap

Initial attempt to address #63 - positioning of menus and tooltips with [wmww/gtk-layer-shell](https://github.com/wmww/gtk-layer-shell) library.
While the approach of the library is simple — subscribe to 'realize' for all windows and patch surfaces for anything that looks like popup, there's too much magic happening inside so I'm not even going to try adapting the code directly to waybar.
* install sway 1.2 + wlroots 0.7.0
* install gtk-layer-shell 0.1.0 (optional; meson will fetch it from github if not present)
* checkout git branch from this pull request
* configure waybar with `-Dgtk-layer-shell=enabled` (disabled by default)
- menus are opened at mouse pointer position
- tooltips are not grabbing focus and making waybar go insane
- outputs are detected and new bars created for outputs …

Use gtk-layer-shell library for correct positioning of popups

---

README.md

Add missing dependencies of the new gtk-layer-shell to the README.
I have tested the apt install only on Debian testing, not on Ubuntu 19.10

add dependencies of gtk-layer-shell to readme

---

protocol/dbus-status-notifier-item.xml

I noticed a lot of errors of the sort:
```
(waybar:165190): "GLib-GIO-WARNING **: 16:39:02.710: Received property WindowId with type i does not match expected type u in the expected interface"
```

Fix: WindowId recieves 'u'

---

man/waybar-battery.5.scd
man/waybar-network.5.scd
man/waybar.5.scd

This pull request adds documentation for the configuration options:
* gtk-layer-shell
* network->family
* network->format-icon
Further, it clarifies the available options for the layer configuration and fixes the layout of the waybar-battery man page.
I will also try to update the Github wiki.

man: adding and clarification of configuration options

---

man/waybar-backlight.5.scd
man/waybar-battery.5.scd
man/waybar-clock.5.scd
man/waybar-cpu.5.scd
man/waybar-custom.5.scd
man/waybar-disk.5.scd
man/waybar-idle-inhibitor.5.scd
man/waybar-memory.5.scd
man/waybar-mpd.5.scd
man/waybar-network.5.scd
man/waybar-pulseaudio.5.scd
man/waybar-sway-mode.5.scd
man/waybar-sway-window.5.scd
man/waybar-temperature.5.scd

#505 fix attempt two. #517 had a space on an empty line which caused a build error, this fixes that.
Also changed the spacing in the mpd and temperature modules to use tabs instead of spaces, to be consistent with the other modules.

[Corrected] Add info on "on-click-middle" option to custom module man page

---

src/modules/network.cpp

Fixes:
```
../src/modules/network.cpp:68:3: error: 'assert' was not declared in this scope
68 |   assert(starts_with(read, category));
|   ^~~~~~
../src/modules/network.cpp:6:1: note: 'assert' is defined in header '<cassert>'; did you forget to '#include <cassert>'?
5 | #include "util/format.hpp"
+++ |+#include <cassert>
6 |
```

fix(network): add missing include

---

src/modules/sni/item.cpp

Allows things such as https://github.com/udda/multiload-ng to work nicely :)

Keep aspect ratio when scaling tray icons.

---

include/client.hpp
src/client.cpp

std::unique_ptr is not required here as the only benefit it gives is stability of address on vector resize and it's easy to invalidate it accidentally. std::list provides the same guarantee of stable addresses
of the elements and correct destruction while avoiding smart pointer overhead.
Also fixes #554, caused by my inability to read the manual for std::remove_if :smile:
To be honest, fixing remove_if would be enough, but I already did the refactoring part and decided to proceed with that.

refactor(client): use std::list<waybar_output> to store outputs

---

include/modules/pulseaudio.hpp
src/modules/pulseaudio.cpp

It makes finding the icon a little more reliable. [PA_PROP_DEVICE_FORM_FACTOR](https://freedesktop.org/software/pulseaudio/doxygen/proplist_8h.html#a77c49f81eb8426259c13fc53619b9670)
Though this should probably get refactored to use [PA_PROP_DEVICE_ICON_NAME](https://freedesktop.org/software/pulseaudio/doxygen/proplist_8h.html#ad2eee8a3a9bbad4ed65eb7eb094a7518) in the future.
This is how Pulseaudio finds the icon: [sink.c](https://github.com/pulseaudio/pulseaudio/blob/f5d3606fe76302c7dbdb0f6a80400df829a5f846/src/pulsecore/sink.c#L3443)

Use PA_PROP_DEVICE_FORM_FACTOR for device icon.

---

include/modules/clock.hpp
man/waybar-clock.5.scd
meson.build
resources/config
src/modules/clock.cpp
subprojects/date.wrap

Please forgive my C++ newbiness!
Notably I had to do the subprojects thing to get around HowardHinnant/date#398, and I don't _love_ that I had to write my own formatter in clock.cpp, but I think this should work.
Feedback, and push back, very welcome. Let me know how to improve the code and I will!

Add timezone support to clock module (closes #223)

---

src/modules/pulseaudio.cpp

Now that the icon is determined based on the form factor (see 8fb3211594ced057025d2b8a9acc1b63a27cb388), it makes sense to adapt the icon names to the string representation of the form factors.
The [form factor strings are copied from pulseaudio](https://github.com/pulseaudio/pulseaudio/blob/2afadb7119f4d84e39212fc12102c49513f9f1a3/src/modules/bluetooth/module-bluez5-device.c#L203-L225):
```c
static const char *form_factor_to_string(pa_bluetooth_form_factor_t ff) {
switch (ff) {
case PA_BLUETOOTH_FORM_FACTOR_UNKNOWN:
return "unknown";
case PA_BLUETOOTH_FORM_FACTOR_HEADSET:
return "headset";
case PA_BLUETOOTH_FORM_FACTOR_HANDSFREE:
return "hands-free";
case PA_BLUETOOTH_FORM_FACTOR_MICROPHONE:
return "microphone";
case PA_BLUETOOTH_FORM_FACTOR_SPEAKER:
return "speaker";
case …
```

pulseaudio: adapt icon names to form factors

---

include/modules/sway/ipc/client.hpp
include/modules/sway/mode.hpp
include/modules/sway/window.hpp
include/modules/sway/workspaces.hpp
src/modules/sway/ipc/client.cpp
src/modules/sway/mode.cpp
src/modules/sway/window.cpp
src/modules/sway/workspaces.cpp

Could fix some rare crashes when disconnecting monitors. I'm still not satisfied with the change but it works and I don't think I'll have a better fix anytime soon.
Differences from the first attempt: `Ipc` now owns the `SleeperThread`
AddressSanitizer backtrace:
```
=================================================================
==78099==ERROR: AddressSanitizer: heap-use-after-free on address 0x6030001b2ce8 at pc 0x000000ac9815 bp 0x7f4c7d1ea570 sp 0x7f4c7d1ea568
READ of size 8 at 0x6030001b2ce8 thread T7
#0 0xac9814 in std::__cxx11::list<sigc::slot_base, std::allocator<sigc::slot_base> >::empty() const /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_list.h:1052:38
#1 0xac8f60 in sigc::internal::signal_emit1<void, waybar::modules::sway::Ipc::ipc_response …
```

fix(sway): resolve destruction dependency between Ipc and SleeperThread

---

include/modules/clock.hpp
src/modules/clock.cpp

`date` includes fractional seconds into `%S` format string output (see https://github.com/HowardHinnant/date/issues/543 for details).
This change should address the issue with seconds formatting reported in https://github.com/Alexays/Waybar/issues/565#issuecomment-579382135

fix(clock): lower precision of zoned_time to avoid fractional seconds in output

---

meson.build

From LLVM libc++ documentation:
"Prior to LLVM 9.0, libc++ provides the implementation of the
filesystem library in a separate static library."
Now the filesystem library (not the experimental one) is shipped
inside the libc++.so library.
Check if '-lc++fs' link flag is needed and supported before adding
it.

fix(meson): Support libc++ >=9.0.0

---

include/modules/sni/tray.hpp
include/modules/sni/watcher.hpp
src/modules/sni/tray.cpp
src/modules/sni/watcher.cpp

Fixes #359
This uses a singleton so we only ever use one StatusNotifierWatcher for
all of our bars (and all of their trays).
Before we had one per tray module. The first one to get the DBus name
would prevent the others from getting it. When that tray disappears (due
to dpms toggles for example), the other watchers do not react to it
correctly. Plus, I am not even sure that it is correct for the same
process to try to acquire the same name multiple times.
This does not solve the fact that we should be able to lose the
name and get it back on the bus, but at least we are not deceiving
ourselves :).

Use the same StatusNotifierWatcher for all trays

---

include/modules/pulseaudio.hpp
src/modules/pulseaudio.cpp

When you have multiple sinks (resp. sources), the module used to display
the state of the most recently changed one. This changes remembers the
default sink name, and only records changes to that one.

pulseaudio: track only the default sink and source

---

src/bar.cpp

If the bar is using initial size from the config (i.e both width and height are set and resize is not required), GtkWindow configure event is is not emitted. Initialize exclusive zone earlier for that case.
Fixes #609

fix(bar): set exclusive zone early for gtk-layer-shell

---

resources/waybar.service.in

the service needs to have After=wayland-session.target otherwise it'll
be started in parallel to the compositor which might not be fully
configured.
ps. sorry I overlooked this setting when I was sending the previous pull request.

systemd service: fix start up ordering

---

README.md

* adding libspdlog-dev to list of ubuntu dependencies
* making list easier to read and copy from
* sorting (ocd)
This morning my build failed on [master](https://github.com/Alexays/Waybar/commit/6c27af35e94e4645a39b58b57bd6b91d782a9838). I noticed a bunch of these errors:
```
../subprojects/spdlog-1.3.1/include/spdlog/details/pattern_formatter.h:99:9: error: ‘assert’ was not declared in this scope
```
Also `meson --reconfigure build` was saying:
```
Run-time dependency spdlog found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency spdlog
```
Installing libspdlog-dev seemed to fix it.

readme: ubuntu dependencies 

---

Makefile

This commit makes it so that running `make` without arguments builds rather than builds and runs, which is unconventional and surprising behaviour.

Switch default Makefile rule from run to build

---

include/modules/memory.hpp
src/modules/memory.cpp

The approximation should include `SReclaimable`, and subtract `Shmem`. To prevent the parsing code from ballooning in size, this commit also refactors the parsing into a map.

fix(memory): provide better free memory approximation on old kernels

---

include/util/command.hpp

I startup "Terminator", a terminal emulator, from Waybar button.
Waybar forks on button click, and the child process executes Terminator,
and the Waybar process itself setups SIGCHLD to SIG_IGN to discard defunct child processes.
But the SIGCHLD setting is inherited to a new child process on fork when I click the button next time.
That is why Terminator startups with SIGCHLD setting of SIG_IGN on the second click.
Terminator forks, executes `uname -p`, and waits finishing of the `uname -p` process.
But because Terminator's SIGCHLD setting is SIG_IGN, `uname -p` process disappears just after it exits,
and Terminator can't wait it, raise an exeception, and exits.
The solution is to restore SIGCHLD setting of child processes to SIG_DFL after forks.
Then, Terminator's SIGCHLD setting becomes …

restore SIGCHLD settings to SIG_DFL. #600

---

include/modules/bluetooth.hpp
include/modules/network.hpp
include/util/rfkill.hpp
man/waybar-bluetooth.5.scd
man/waybar-network.5.scd
meson.build
src/modules/battery.cpp
src/modules/bluetooth.cpp
src/modules/network.cpp
src/util/rfkill.cpp

I added an interface to the [linux rfkill utility](https://wireless.wiki.kernel.org/en/users/Documentation/rfkill). This allows modules to update based on changes of the rfkill state. I added this to the existing network module and created a new bluetooth module implementing the feature.
The code is adapted from [here](https://git.kernel.org/pub/scm/linux/kernel/git/jberg/rfkill.git/).
I was never sure if my bluetooth module was deactivated or not connecting to my devices for another reason.
It's possible to update the module via an interval in addition to rfkill events.
Two main changes were made:
1. Distinction between no wifi connection present and wifi module turned off. (think: airplane mode)
1. Update status on rfkill event in addition to interval based updates.
The second actually …

Add rfkill status to network module and new bluetooth module

---

man/waybar.5.scd
src/client.cpp

This adds ability to exclude specific output for a bar with `!` character, for example:
```
[
{
"layer": "bottom",
"output": "eDP-1",
},
{
"layer": "bottom",
"output": "!eDP-1",
}
]
```

Add a way to exclude specific output

---

src/modules/battery.cpp

Fixes #666: `static_cast<float>(capacity / full_at)` is either 0.0 or 1.0 for most sane values of `full_at`.
I'm not 100% sure of the logic, though: clamping `capacity` to 0 .. `full_at` might be reasonable for defective batteries, if and only if `full_at` is well-known and can never be exceeded, and `capacity` readings are error-prone and could be misleading if higher than `full_at`.
I'd prefer the interpretation that `capacity` should not be clamped, but that I simply consider my battery to be charged at, say, `full_at` 80. In fact, that's what I set as a regular charging threshold to conserve battery lifetime, unless I prepare for extended offline periods and manually request 100%-charging. But my battery is nevertheless perfectly able to charge up to 100%, and I'd prefer this to be …

Fix round to 0 or 1 in capacity computation with given full-at

---

meson.build

The man page for bluetooth was present but not being built by meson.

Build bluetooth module man page

---

README.md

Let's cleanup dependencies list 🙂 
- I removed an empty line, not sure if that separation meant something?
- `chrono-date` and `spdlog` are required, I think in AUR package you should add them instead of letting meson download them
- `sway` is not really a dependency (especially since https://github.com/Alexays/Waybar/commit/6522a7acb4a87ecfa0f8e85a190b9743ba52a6f9) in a sense that sway package provides no shared libraries needed for the modules to work, it feels like adding a dependency on "linux"
- `wlroots` also seems to be not really a dependency, `ldd /usr/bin/waybar | grep wlroots` finds nothing
- `libappindicator-gtk3` should be a required dependency based on [this log message](https://github.com/Alexays/Waybar/blob/9817955fef845444a95092653ea202f75ba7c3e4/src/modules/sni/tray.cpp#L …

Add missing dependencies to README

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

All workspace buttons that are visible on the same output as the current waybar can be styled with the `current_output` css class.
This is really only useful in combination with the `"all-outputs":
true`. Then the workspaces that are on the current output can be styled
differently than the workspace on other outputs, while all workspaces are visible in every waybar.

sway/workspaces added current_output CSS class to buttons.

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

Sway provides the workspace "num" property which is an integer number of the workspace, i.e., workspace `"3"` -> `3` and also `"3dev"` -> `3`. This PR uses this property to sort the workspaces, which makes sense when persistent workspaces or all-output is specified. This commit also adds a new configuration option, whether the numeric workspaces come in front or after workspaces that have non-numeric name.
* I think this should fix issue #482.
* Tested only with sway version 1.4
* Always sorts workspaces, regardless of any settings.

sway/workspaces: sort by the "num" property provided by sway

---

Dockerfiles/alpine
Dockerfiles/opensuse

This PR fixed alpine and opensuse Dockerfiles for building #659 .
This time I was able to test on my own computer, so I am more confident about the validity of this.
I have a problem with fedora : [pugixml-devel (fedora)](https://apps.fedoraproject.org/packages/pugixml-devel) is a terrible package. It doesn't include `/usr/lib/pkgconfig/pugixml.pc` so pkg-config is confused about this :
```
Run-time dependency pugixml found: NO (tried pkgconfig)
meson.build:78:0: ERROR: Dependency "pugixml" not found, tried pkgconfig
```
I don't know what is the expected way to fix this : should I manually download the file during the Dockerfile build, add a fedora specifig meson.build.patch, or add a wrapfile ?
ping @Alexays

WIP : Layout dockerfiles

---

include/factory.hpp
include/modules/wlr/taskbar.hpp
man/waybar-wlr-taskbar.5.scd
man/waybar.5.scd
meson.build
protocol/meson.build
protocol/wlr-foreign-toplevel-management-unstable-v1.xml
src/factory.cpp
src/modules/wlr/taskbar.cpp

Although waybar was originally designed to work with sway, some people use it as a bar with other compositors now. People such as me ;) One feature I was missing from waybar, was a simple taskbar with all the windows that I have open (similar to tint2 for X). After some searching I found wf-panel and its taskbar implementation based on the foreign-toplevel-manager protocol defined by wlroots. I took a lot of inspiration from this implementation and developed a module with similar features for waybar.

foreign-toplevel-manager based taskbar module

---

include/modules/sway/workspaces.hpp
src/modules/sway/workspaces.cpp

Previously, clicking on the same workspace you were on would throw you
to another workspace if `workspace_auto_back_and_forth yes` was
specified in your sway config. This also fixes workspace output moving
misbehaving and doing the same.

sway/workspaces: make clicking on workspaces idempotent

---

include/factory.hpp
include/modules/river/tags.hpp
man/waybar-river-tags.5.scd
meson.build
protocol/meson.build
protocol/river-status-unstable-v1.xml
src/factory.cpp
src/modules/river/tags.cpp

This commit adds a new module displaying the tags of [river](https://github.com/ifreund/river) which serve a similar purpose to sway's workspaces. This works using a custom `river-status` protocol that allows waybar to receive events when the tag state of an output changes.
There are also other things that could be added to waybar for better integration with river such as a module displaying the title of the currently focused view, or a module displaying the current mode (like there is for sway already). I decided to implement the tags module first as it is the most important and I'm not totally sure what this project's stance is on supporting specific compositors other than sway.

river/tags: add module

---

src/modules/battery.cpp

I have a Wacom pen which is loaded via my laptop. Currently its battery has been added to the laptop battery, which has doubled the total capacity, so I have never been able to charge my laptop over 50% according to the display. But pens are from the type USB, so it is not recognized anymore by my fix.

Only real batteries are counted as batteries

---

src/modules/wlr/taskbar.cpp

These two commits fix the problems with the 'on-click-right' click events and the 'format' option.
Resolves #728, Resolves #735

Fixes for wlr/taskbar

---

man/waybar-wlr-taskbar.5.scd

The example incorrectly used 'on-middle-click' as option although it
should be 'on-click-middle'. Fix this and also add some other options.

Fix and extend the wlr/taskbar example in the man page

---

include/modules/wlr/taskbar.hpp
man/waybar-wlr-taskbar.5.scd
src/modules/wlr/taskbar.cpp

Add support for defining multiple icon themes in the config which are used in the given order to lookup icons. With this approach it is possible to define one (or multiple) fallback icon themes if the app cannot be found in the current main icon theme. In addition the module will always lookup icons in the system default icon theme (for GTK this is hicolor).
Also respect XDG_DATA_DIRS now if set to get correct lookup paths for desktop files in the system. Especially for flatpack this is of importance. See #754
In addition I also refactored a little bit the lower_app_id changes done in PR #761

Support for multiple icon themes and XDG_DATA_DIRS

---

.travis.yml

`/quarterly` package set was recently updated to **2020Q3**, so let's use it instead of bumpy `/latest`.

CI: unbreak FreeBSD

---

include/modules/sway/workspaces.hpp
src/modules/sway/workspaces.cpp

sway assigns a "num" property to every workspace and this PR copies the logic of sway into waybar. While this is duplicated effort, it seems to be needed to properly sort persistent workspace, which might not exist in the sway IPC response, but needs something like the "num" property anyway.
Not sure this is really the best way but it seems to fix the issue #777 and the comment in the PR #696 .

make waybar itself assign numbers to workspaces like sway

---

meson.build

The 'date' library dependency was incompletly imported with meson.
Only the target 'date::date' seemed to be caught by meson, but
'date::date-tz' not, which lead to build errors in gentoos sandbox
environment.
See this question, too:
https://stackoverflow.com/questions/62951569/meson-doesnt-link-library
Adding the modules in meson imports them all and the library builds
nice.
Note, that this did not happen with a standard checkout and local build
on my system, but only when creating an ebuild for the package.

Fix 'date' dependency in meson

---

src/modules/network.cpp

This will enable the networking module to be used for ethernet
interfaces on kernels without nl80211 support.
It should be reasonable to allow desktop systems without
wireless interfaces to run custom kenrel configs
without nl80211 compiled in.

network: make missing nl80211 non-fatal

---

protocol/wlr-layer-shell-unstable-v1.xml
subprojects/date.wrap
subprojects/gtk-layer-shell.wrap

Fixes: #776, fixes #780 (via date 3.0.0)
Fixes: #530, fixes #750 (via gtk-layer-shell 0.2.0)
***
gtk-layer-shell will now print a harmless warning about xdg-wm-base version mismatch. This is caused by gtk-layer-shell bundling xdg-shell protocol of older version, which I'll try to fix upstream before upcoming 0.2.1 release.
CI is not using gtk-layer-shell subproject:
```
|subprojects/gtk-layer-shell-0.2.0/src/meson.build:24:0: Exception: Static libraries can only be introspected with GObject-Introspection >=1.58.1
...
gtk-layer-shell: NO Static libraries can only be introspected with GObject-Introspection >=1.58.1
```
Sounds like missing dependency in docker files.

chore: update subprojects for date, gtk-layer-shell

---

src/modules/sway/workspaces.cpp

closes #686
Previously, the workspace only switched when you release the mouse, which feels slow and clunky compared to i3bar and swaybar.

switch workspace on mouse-down to match swaybar

---

include/util/command.hpp
src/main.cpp

When forkExec is called it begins to ignore all SIGCHLD signals for the rest of the progam's execution so that they are automatically reaped. However, this means that subsequent waitpid calls in the exec function will always fail. So instead handle SIGCHLD by reaping any processes created by forkExec and ignoring all others so that they can be handled directly by the exec function.
I had a custom module disappearing on scroll-up which is fixed by this and I'm 99% sure this is what causes #739 while still fixing #369. I didn't know where to put the signal handler function, so I just put it in main.cpp. It adds a couple of ugly global variables, but I couldn't think of any other way to do it. If waybar was relying on signal(SIGCHLD, SIG_IGN) to reap other child processes not created by …

Handle SIGCHLD for exec/forkExec

---

resources/waybar.service.in

`wayland-session.target` is a non-standard target, and [systemd will not include it](https://github.com/systemd/systemd/pull/15180). The effect is that this service is useless unless people manually create this `wayland-session.target`. We should be using `graphical-session.target` instead, which is a standard target meant to mean "any graphical session".
Even for people who use both X11 and Wayland, I don't think it will be terrible, the service would supposedly just silently fail when attempted to start under X11, and next time they logout and login in Wayland it will start again (this time successfully).
If that is a problem, there are alternatives, e.g. users could manually start the service when launching Wayland session instead of enabling the service for auto-start. If even that is …

systemd: use standard targets, update service type

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

In sway/workspaces, just like `disable-scroll` turns on/off the ability to change workspaces by scrolling the mouse add `disable-click` that turns on/off the ability to change workspaces by clicking.

Add option for no workspace switch on click

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

In case you want to style a specific workspace add IDs to the workspace buttons. Styling is done by matching button#sway-workspace-${name}.

Add IDs to sway workspace buttons for CSS styling

---

include/ALabel.hpp
include/modules/clock.hpp
man/waybar-clock.5.scd
src/ALabel.cpp
src/modules/clock.cpp

Timezone switching inspired by KDE's clock module; calendar formatting fix because the bold/underline is easy to miss on my font/monitor (I use "<b><span color='green'>{}</span></b>").

New clock features

---

include/bar.hpp
src/bar.cpp
subprojects/gtk-layer-shell.wrap

In the hindsight, it wasn't a good idea to have one set of GTK event handlers for both code paths. Took me a while to remember which code is needed for gtk-layer-shell and which one is for bare layer-surface. Apparently `Bar::onConfigure` wasn't passing the right values to `setExclusiveZone` because it was written with assumption that `layerSurfaceHandleConfigure` already done everything required.
***
At some point GTK stopped listening to `resize`/`set_size_request` if the requested size is insufficient. This is now causing occasional bar size changes and warnings in the log for both code paths.
This would also cause an interesting behavior if `gtk-layer-shell` is disabled and the bar height is a fixed value from the config file; the bar would expand according to a content size, but the …

Fix resizing of the bar with gtk-layer-shell

---

src/ALabel.cpp

If a label is being ellipsized it doesnt make sense to allow it to use line breaks to have multiple lines.
Fixes #827

Prevent line breaks in ellipsized labels

---

man/waybar-wlr-taskbar.5.scd
src/modules/wlr/taskbar.cpp

The fix for taskbar tooltips in 6a2d214b55 was incomplete: it causes the label
to contain escaped titles.  Allow choosing whether to enable markup or not.

Allow enabing pango markup in the taskbar string

---

src/modules/custom.cpp

This pull request fixes the issue where the process would restart immediately and the thread would sleep after the process has restarted, and not before.
Fixes #621

Fix "restart-interval" in the custom module

---

src/modules/memory/common.cpp

This commit adds support of format string for memory module tooltip (#845).

Add format for memory tooltip

---

include/modules/custom.hpp
man/waybar-custom.5.scd
src/modules/custom.cpp

This pull request adds a new config for the custom module: `exec-on-event`.
This config allows disabling the default behavior of re-executing the script whenever an event that has a command set is triggered.
Fixes #841

Add an "exec-on-event" config for the custom module

---

src/util/rfkill.cpp

Fixes the following build warning with musl libc:
```
In file included from ../src/util/rfkill.cpp:24:
/usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
|  ^~~~~~~
```

Fix non-standard usage of <sys/poll.h>

---

man/waybar-disk.5.scd
src/modules/disk.cpp

I prefer to hide my disk information until only a certain percentage is left. This would implement that functionality in a way like the CPU/memory modules use `state`.

Add state to disk module

---

man/waybar.5.scd.in
meson.build
src/client.cpp

This still allows loading the installed default config, but also add back the path `/etc/xdg/waybar` unconditionally for the people who were using it as their configuration directory and have a "prefixed" waybar installation. Should fix https://github.com/Alexays/Waybar/issues/714 and https://github.com/NixOS/nixpkgs/issues/99057
Also added the sysconfdir-prefixed path in the man page to prevent some confusion. The meson code is kinda messy, sorry about that. If there's a better way to do this, please do tell.

Add back unprefixed global config directory

---

src/modules/sway/workspaces.cpp

Hello,
Little hack to have workspace name like `2:Firefox` (to get the default sway workspace bindsym working) with an associated icon without the need to repeat 10 times the line in the configuration file for each case.
~~thanks for the bar~~

Add format-icons for workspace's name entry in sway/workspaces module

---

resources/style.css

Currently, the bottom border on workspace buttons eats into the box size and causes the text to sit higher than in other modules. This is ugly when there are other modules (like the window title) right next to the workspace module. To fix the issue, create the bottom border using an inset box-shadow, which doesn't affect the box's content sizing.
Before:
After:

style(workspaces): align text with other modules

---

include/modules/wlr/taskbar.hpp
src/modules/wlr/taskbar.cpp

Remove trim usage in format because it glues icon with test and takes away control on spaces.
Also some clang-tidy fixes

Remove trim usage in format

---

src/modules/mpd/mpd.cpp
src/modules/mpd/state.cpp

- Add elapsedTime and totalTime to tooltip format arguments
- Catch format exceptions and print error
- Copy mpd connection error message before it gets freed
- Update display after connection to mpd was lost

Fix various mpd bugs

---

src/client.cpp
src/modules/wlr/taskbar.cpp

It's not allowed to bind to a higher version of a wayland protocol than supported by the client. Binding wlr-foreign-toplevel-manager-v1 v3 to a generated code for v2 causes errors in libwayland due to a missing handler for `zwlr_foreign_toplevel_handle_v1.parent` event.
This PR just allows to run waybar on the compositors with newer protocols. Someone else will have to update the protocol file, read https://github.com/swaywm/wlr-protocols/pull/52 and add `zwlr_foreign_toplevel_handle_v1.parent` event support for detecting window stacks and allowing to ignore child windows in the taskbar. Wayfire git master already supports sending the event and could be used for testing.
Note: I'm using interface version instead of the constant `2` because I'm assuming that whoever updates the protocol …

fix(wlr/taskbar): do not bind to unsupported protocol versions

---

include/util/format.hpp

Other units are all uppercased, so using an uppercased "K" makes it look more consistent (especially when `{bandwidthUpBits}` or something like that is used).

Replace lowercase "k" with uppercase "K" to make it look more consistent

---

src/modules/custom.cpp

This is a fix for https://github.com/Alexays/Waybar/issues/890
The issue was caused by ```label_.set_tooltip_markup``` being called too frequently (more than once every 0.6s), which somehow prevents any tooltips from appearing at all. Now, ```label_.set_tooltip_markup``` is only called if the tooltip markup has changed. This means modules can now output text updates more frequently without breaking tooltips.
It would be good if it was possible to also update tooltip markup frequently without breaking tooltips, but that seems to be a GTK problem, and this is a good start.

Tooltips no longer completely break if a custom module updates too frequently

---

include/bar.hpp
include/client.hpp
src/bar.cpp
src/client.cpp
src/modules/idle_inhibitor.cpp
subprojects/gtk-layer-shell.wrap

An attempt to update the bar code for #860 that went overboard. I'm pretty sure that something is broken in this branch, just haven't figured out what. I'll be keeping this as a draft until I'm convinced that the only collateral damage is logs.
`GLSSurfaceImpl` works fine for me so far, which is not surprising with how small it is after letting `gtk-layer-shell` manage exclusive zone. `RawSurfaceImpl` is not so extensively tested, but I'm going to switch to it for next few days and try all the configuration changes possible via IPC.
***
The end goal is a live configuration reload and updates from sway IPC events, but the path is long (https://github.com/alebastr/Waybar/compare/master...swaybar-ipc is a somewhat ugly proof of concept for the IPC part).
It might also require some feedback …

Refactor layer surface implementations (again)

---

resources/waybar.service.in

The current service doesn't play too nice with Sway when it is started
from [sway service](https://github.com/xdbob/sway-services).
Waybar is started before the system has a display.
```
Nov 30 22:11:23 ansan waybar[1352]: Unable to init server: Could not
connect: Connection refused
Nov 30 22:11:23 ansan waybar[1352]: cannot open display:
Nov 30 22:11:23 ansan systemd[1306]: waybar.service: Main process
exited, code=exited, status=1/FAILURE
Nov 30 22:11:23 ansan systemd[1306]: waybar.service: Failed with result
'exit-code'.
```
Restarting the service after the system has been initialized works nicely,
so this restart rule should do the trick without tinkering with the
target.

fix(systemd): restart when service fails

---

meson.build
subprojects/fmt.wrap
subprojects/spdlog.wrap

There is no particular change in this update that we require. However, our previous version, 5.3.0, is nearly two years old, so it seems prudent to pull in all the upstream fixes that have been made since then.
New wrap file taken from https://wrapdb.mesonbuild.com/fmt and modified to download from GitHub as per commit 99dde1aff8db ("Download patch files from Github instead of wrapdb").

Update fmt subproject to 7.1.3

---

meson.build
src/bar.cpp
subprojects/spdlog.wrap

This is very useful when writing CSS that affects more than just a single widget. Pass `-l debug` to enable debug logging and show this information.
Example output:
[2020-11-30 12:38:51.141] [debug] GTK widget tree:
window#waybar.background.bottom.eDP-1.:dir(ltr)
decoration:dir(ltr)
box.horizontal:dir(ltr)
box.horizontal.modules-left:dir(ltr)
widget:dir(ltr)
box#workspaces.horizontal:dir(ltr)
widget:dir(ltr)
label#mode:dir(ltr)
widget:dir(ltr)
label#window:dir(ltr)
box.horizontal.modules-center:dir(ltr)
box.horizontal.modules-right:dir(ltr)
widget:dir(ltr)
box#tray.horizontal:dir(ltr)
widget:dir(ltr)
label#idle_inhibitor:dir(ltr)
widget:dir(ltr)
label#pulseaudio:dir(ltr)
widget:dir(ltr)
label#network:dir(ltr)
widget:dir(ltr)
label#cpu:dir(ltr)
widget:dir(ltr)
label#memory:dir(ltr) …

Add debug log message to print each bar's widget tree

---

include/modules/clock.hpp

We are currently using this value once before it's initialized, since we check it before we set it in `Clock::calendar_text()`. This was caught by Valgrind, producing the following error:
==8962== Conditional jump or move depends on uninitialised value(s)
==8962==    at 0x138285: date::operator==(date::year_month_day const&, date::year_month_day const&) (date.h:2793)
==8962==    by 0x135F11: waybar::modules::Clock::calendar_text[abi:cxx11](waybar::modules::waybar_time const&) (clock.cpp:111)
==8962==    by 0x13587C: waybar::modules::Clock::update() (clock.cpp:62)
==8962==    by 0x156EFA: waybar::Bar::getModules(waybar::Factory const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}::operator()() const (bar.cpp:577)
==8962==    by …

clock: initialize cached date

---

src/modules/clock.cpp
src/modules/mpd/mpd.cpp

There was one uninitialized value warning and two mismatched-sign compare warnings. They both appear valid, the first occurring when MPD's `format-stopped` contains `{songPosition}` or `{queueLength}` and the second occurring when the clock's `timezones` array is more than 2 billion items long (not likely, I admit). Fix both issues.

Fix a few compiler warnings

---

resources/style.css

These modules, unlike others, have no horizontal margins by default. This means that they'll appear uncomfortably close together in any config that puts them side-by-side. In general, the default style should make configs with any module ordering look good. Add the same 4px horizontal margins that other module have to these.
This affects rendering of the default config by moving the workspace buttons 4px to the right.
Before:
After:

style: add 4px margins to window and workspaces modules

---

include/modules/battery.hpp
man/waybar-battery.5.scd
src/modules/battery.cpp

I've come across a few inconsistencies in the battery state calculations so I had a go at the code to try and make it simpler and fix some of the issues. This PR includes:
- Calculating the battery state from just the energy values. Using other values for the total capacity was resulting in broken results in other cases. Since the energy information is already enough and was already present this simplifies the code and avoids the inconsistency.
- Clamp battery states above 100%. This can happen when the battery recalibrates and charges more than the capacity it thinks it has. Just show 100% in those cases.
- Round the battery state so that 99.9% shows as 100%. This avoids some cases where the last bit of battery doesn't charge but the battery is effectively full already.
- Whenever the …

Simplify and improve battery state calculations

---

include/modules/battery.hpp
src/modules/battery.cpp

Speedup battery state update by only updating the battery list when we get a CREATE/DELETE event in the directory or whenever we do a full refresh on the interval.
This doesn't seem to make much difference in CPU performance either way that I've been able to measure. But the code doesn't look too bad, although it does need a mutex. It's a judgment call weather to do this or to just get rid of the TODO and live with the refresh on every update. There may be situations where the battery state is updating very fast where this is a relevant gain.

Don't update battery list on every update

---

protocol/wlr-foreign-toplevel-management-unstable-v1.xml
src/modules/wlr/taskbar.cpp

There was an update the of the toplevel manager protocol. Unfortunately,
there are no new interesting updates with regard to the taskbar
implementation. Nonetheless, update the protocol xml files to the latest
version so that the implementation is up-to-date.
While being there, also change the debug warning that is shown when
there is a version mismatch between the server and client version of the
protocol.

Update to the latest version of the foreign toplevel manager protocol

---

src/modules/sway/workspaces.cpp

GDK Wayland backend can emit two events for mouse scroll: one is a
GDK_SCROLL_SMOOTH and the other one is an emulated scroll event with
direction. We only receive emulated events on a window, thus it is not
possible to handle these in a module and stop propagation.
Ignoring emulated events should be safe since those are duplicates of
smooth scroll events anyways.
Fixes #386
CC @emmanueltouzery, @somini: please, confirm if that works and fixes the issue for you.

fix(sway/workspaces): ignore emulated scroll events

---

src/modules/sway/window.cpp

This error occurs because of an incorrect assumption that the size of the list of nodes that contains the focused window is the number of windows in a workspace.
The windows in a workspace are stored as a tree by Sway, rather than a list, so the number of windows has to be found by counting the leaves of a workspace tree.

Fix Sway #waybar.solo CSS rule applying on split

---

src/modules/pulseaudio.cpp

Yesterday I opened #933, but actually this change was enough to make `waybar-pulseaudio` work with `pipewire-pulse`. What's your opinion about this change?

Fix waybar-pulseaudio with pipewire-pulse

---

src/modules/pulseaudio.cpp

This reverts commit 0d03c1d4da50ef248b197c29301e7cd879f98336.
As pointed out in [#933](https://github.com/Alexays/Waybar/issues/933#issuecomment-748444973), #937 wasn't fixing anything at all... waybar works with pipewire after its restart, thus a different patch is needed.

Revert "Fix waybar-pulseaudio with pipewire-pulse"

---

src/bar.cpp

I noticed that #880 didn't seem to work when the bar was in vertical mode, and it looks like that was because the boxes were being re-assigned after adding the selectors, so I moved the selectors to just after the re-assignment, so now they should work in either mode :)

Fix for group module selectors when bar is vertical

---

include/bar.hpp
include/client.hpp
src/client.cpp

This resolves #602 allowing you to specify the output identifier exactly like Sway allows you to do.
It does this by getting the identifier from the description that is reported. This is how swaybar does it as well: https://github.com/swaywm/sway/pull/3415/files#diff-f1816f4a24dbbcf1a1dc419a0daeee3ac8bfcb410a44bd9d9e75900d1210bbbcR264-R279

Added waybar_output.identifier support. #602

---

src/ALabel.cpp

fixes #896
This fixes a logical error in the loop checking several alts to get the right icon. The old logic assigned "default" on each failure to find the right one. This made the loop fail on the next iteration unless default also was an object that contained the other alts looked for.
My fix changes the logic to use a default value for the name that should be used and assigns to that name if it finds the value. Finally it assigns to `format_icons` once it either found the one we're looking for or nothing was found.

Fixing logic in getIcon

---

src/modules/wlr/taskbar.cpp

See commit descriptions for individual issues.
A better fix for the protocol error would be to separate the foreign toplevel manager code from Gtk UI and keep a single instance shared between bars, but that requires more time and effort than I can spare right now :frowning_face:
CC: @danieldg, @l3nkz

Fix issues in wlr/taskbar

---

man/waybar-river-tags.5.scd
src/modules/river/tags.cpp

add option (array) to river/tags so that you can define the labels to display rather than 1,2,3...

add option 'tag-labels' to river/tags

---

include/factory.hpp
include/modules/simpleclock.hpp
meson.build
src/modules/simpleclock.cpp

ref https://github.com/Alexays/Waybar/issues/668
This will allow to have the clock module (before hhdate was introduce) when its not available (Debian disable subprojects download)
wdyt?

Add simpleclock as fallback when hhdate is not available

---

src/modules/cpu/common.cpp
src/modules/disk.cpp
src/modules/memory/common.cpp

According to the [wiki page on states](https://github.com/Alexays/Waybar/wiki/States), the following is true:
- Some modules support 'states'
- [E]ach state can have its own `format`. Those can be configured via `format-<name>`.
I sadly found this not to be true when I wanted to hide the CPU, Disk and Memory modules whenever my states are 'good'. The text here seems to have been copied directly from the Battery module wiki page, even though no other modules supported it. I'll update the wiki to reflect these changes if this gets merged.

Support format-{state} for cpu/disk/memory

---

src/client.cpp

Since both `name` and `description` are not mutable in the protocol version we bind to, it's fine to drop the xdg_output object after receiving an initial set of properties.
Also cleanup the code for attaching styles. There's always only one screen in Gdk so there's no reason to do that for every window.
Fixes #990

Fix duplicate bars on xdg_output property changes

---

src/modules/wlr/taskbar.cpp

Fixes application icons not found like Quassel Client where the icon is not named org.kde.quassel but quassel or Wayfire config manager which .desktop file is not named org.gtk.wayfire-config-manager.desktop but instead wayfire-config-manager.desktop.

Improved wlr/taskbar icon search.

---

include/util/ustring_clen.hpp
meson.build
src/modules/clock.cpp
src/util/ustring_clen.cpp

fix for #976
uses g_unichar_iswide to calculate the column width of a string; this is used to properly format the calendar under CJK locales

[calendar] CJK locale formatting

---

man/waybar-backlight.5.scd
man/waybar-battery.5.scd
man/waybar-bluetooth.5.scd
man/waybar-clock.5.scd
man/waybar-cpu.5.scd
man/waybar-custom.5.scd
man/waybar-disk.5.scd
man/waybar-idle-inhibitor.5.scd
man/waybar-memory.5.scd
man/waybar-mpd.5.scd
man/waybar-network.5.scd
man/waybar-pulseaudio.5.scd
man/waybar-sndio.5.scd
man/waybar-sway-language.5.scd
man/waybar-sway-mode.5.scd
man/waybar-sway-window.5.scd
man/waybar-temperature.5.scd
src/ALabel.cpp

Add `min-length` config property, can be used in combination with `max-length` to fix the length of a module to a specific size
Also add `align` property to align text in a label
this should help with #883

improve module sizing options

---

src/modules/sway/window.cpp

I know it's a pretty naive implementation but I hope:
1. It will work
2. It will be retro-compatible with existing configuration file
I have to confess I'm not a C++ developer (far from it).
Closes #1000

[sway/window] Add app_id to usable fields in title

---

src/modules/wlr/taskbar.cpp

While using waybar noticed that other apps where also missing icon and added these extra changes:
* Added ~/.local/share prefix to search in current user defined apps.
* Add support for apps that don't properly set an id like pamac-manager which desktop info file is org.manjaro.pamac.manager.desktop but wayfire reports its id as pamac-manager.
* Lastly, If no icon is found use "unknown" as default icon instead of displaying an empty square button.
For icon issues like with pamac-manager I had to use g_desktop_app_info_search directly since I didn't see any bind to it on the giomm c++ binding.

[wlr/taskbar] More icon search improvements.

---

include/modules/sway/workspaces.hpp
man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

#736 introduced a behavior that some may like, but some may not ; I'm part of the latter.
This PR adds a configuration entry to Sway workspaces module in order to enable or disable this behavior.
By default, the behavior is to follow what's configured in the Sway config file (seems more logical that way IMO), and you're able to explicitely tell Waybar not to follow what's configured in the Sway config file.
However, the `--no-auto-back-and-forth` flag is conserved when moving workspaces to other outputs or when changing workspaces by scrolling on the bar, since these behaviors were rightfully fixed by #736 and that's fine by me.
The config entry is named `disable-auto-back-and-forth` and is a boolean.
Closes #985

Add a way to configure auto_back_and_forth on Sway workspaces

---

src/modules/wlr/taskbar.cpp

Fixes a crash and handles the edge case where the application.desktop 'Icon' property points to the absolute path of the icon file instead of an icon name, for example:
```
[Desktop Entry]
Name=Cendric
Comment=RPG and Platformer
Exec=/usr/bin/Cendric
Terminal=false
Icon=/usr/share/Cendric/res/icon.ico
Type=Application
Categories=Game;
```

[wlr/taskbar] Fix unhandled exception crash when icon name is a path.

---

src/modules/wlr/taskbar.cpp

Checks the StartupWMClass property of all .desktop files returned by g_desktop_app_info_search() in order to select the correct .desktop file. 
This fixes issues when applications with similar names are installed, eg: codeblocks, codelite, visual studio code, in this scenario visual studio code which appid is Code and .desktop file is visual-studio-code.desktop, without the check for StartupWMClass would end with either codeblocks or codelite icon.

[wlr/taskbar] Check StartupWMClass

---

src/client.cpp

In #992 I missed a certain case: If `kanshi` or something similar automatically aplies configuration when monitors are plugged, resulting xdg_output events could be received and dispatched in a single batch: initial configuration, done, configuration modified by kanshi, done [, ...repeat for each output configured by kanshi].
Also, as #1019 shows outputs may unexpectedly disappear from under our code due to async callback dispatch magic. I addressed a couple of obvious crashes, but there are more, much more... :scream:
Fixes #990 (again), makes #1019 slightly less likely.

Fix more issues with duplicated bars

---

include/modules/bluetooth.hpp
include/modules/network.hpp
include/util/rfkill.hpp
man/waybar-bluetooth.5.scd
src/modules/bluetooth.cpp
src/modules/network.cpp
src/util/rfkill.cpp

I only wanted to fix that one event size check in `rfkill.cpp`. Should have more willpower to stop and ignore the rest :sob:
Summary:
* Reopening "/dev/rfkill" for each event isn't optimal and could miss some events. Especially since we were ignoring ADD event with the initial state of the device.
* Rfkill doesn't even need a thread. Glib::MainLoop is fast enough to handle events on a couple of file descriptors.
* `Bluetooth::interval_thread_` was not doing anything useful because it had no way to get changed status value. Now we have 3 less threads :smile:
* I'm actually ashamed of the last commit, but untangling the locks and threads in `network.cpp` was beyond an evening coding exercise. Although I'm quite curious why we have to sleep for 5 seconds while holding the mutex and will …

rfkill code refactoring

---

resources/waybar.service.in

This allows `systemctl --user reload waybar` to reload waybar's config as expected.

Configure systemd.service file to allow reloading

---

include/client.hpp
src/client.cpp

Defer destruction of bars for the output to the next iteration of the event loop to avoid deleting objects referenced by currently executed code.
Should fix some of the crashes on output disconnect. Could potentially cause a different kind of race conditions, but I haven't found anything that may happen in practice.
Testing: I've been running this patch for a week and attempting to reproduce the crash. Seems good so far.
@baloo, can you please try the patch and test if it fixes the issues in your setup?
Fixes #1019

fix: schedule output destruction on idle callback

---

include/util/command.hpp

(Fixes #358.)
Subprocesses created for custom module scripts were previously left running when the parent Waybar process exited. This patch sets the parent-death signal of child processes (PR_SET_PDEATHSIG on Linux, PROC_PDEATHSIG_CTL on FreeBSD) to SIGTERM.
Caveats:
* This uses Linux-specific or FreeBSD-specific calls. I don’t know if this project targets other systems?
* There is a possibility that Waybar exits after calling `fork()`, but before calling `prctl` to set the parent-death signal. In this case, the child will not receive the SIGTERM signal and will continue to run. I did not handle this case as I consider it quite unlikely, since module scripts are usually launched only when Waybar starts. Please let me know if you think it needs to be handled.
Testing:
* With `htop` open, …

Terminate custom module scripts on exit

---

include/modules/cpu.hpp
src/modules/cpu/common.cpp

Remove the division of the load by the number of online (or available) processors.
The current displayed value is quite counter-intuitive and hard to get a grasp on as it is different from the values of `uptime` and `top`; moreover there already is the other `{usage}` format, as argued in #769 by @gvccandido.
Furthermore, this (very small) fix would lead Waybar CPU load output to be the same as the one displayed by `i3status`.
Another possibility would be to keep the current format and add a new format for this "more standard" load.
This would fix #769 .
Thank you for Waybar, it is a very useful software I use daily.

Fix: CPU load values

---

man/waybar-mpd.5.scd
src/modules/mpd/mpd.cpp

adds the following configuration options to the MPD module:
- artist-len
- album-len
- album-artist-len
- title-len
to control the maximum length of the tags when they are displayed on the bar.

add length limits for MPD module tags

---

resources/style.css

Hi Alex,
the default style does not apply the green background to the battery module if the status is reported as "plugged" (eg. when the charge limiter is active). I think re-using the style currently used for "charging" is a better default.
Cheers,
Martin

Add style for battery state "plugged"

---

resources/style.css

This patch adds some default styling for the disk module, which previously did not have any styling specified. It uses a brown background since brown isn't used by any other modules.

Add default styling for disk module

---

meson.build

There's *.scd file for sway/language module's manpage, but it's not mentioned in meson.build.

meson.build: add missing waybar-sway-language manpage

---

include/modules/cpu.hpp
man/waybar-cpu.5.scd
src/modules/cpu/bsd.cpp
src/modules/cpu/common.cpp
src/modules/cpu/linux.cpp

Adds format replacements for the CPU module to get the current min, max and average frequencies.
The implementation for *BSD platforms has been stubbed out for the time being, until someone on these platforms implements it.
Here's a quick example of the output it produces :
Closes #764

Add cpu min/max/avg frequencies

---

src/modules/cpu/linux.cpp

On some systems (eg: ARM) the supported frequencies of the CPU are not properly reported by /proc/cpuinfo so use lscpu instead which is more reliable.

[Module CPU] fix crash due to empty frequencies.

---

man/waybar-mpd.5.scd
resources/config
src/modules/mpd/mpd.cpp

Allow the user to show the current volume from MPD status via the
`format` and/or `tooltip-format` configuration options.
The values are provided by libmpdclient and are integers, generally
between 0-100 (without %). Values above 100 are also possible, as mpd
output plugins like `pulse` support volumes above 100%.

Implement MPD volume status format template

---

include/modules/sway/window.hpp
man/waybar-sway-window.5.scd
src/modules/sway/window.cpp

Rewrites window title according to config option "rewrite".
"rewrite" is an object where keys are regular expressions and values are rewrite rules if the expression matches. Rules may contain references to captures of the expression. Regex and replacement follow ECMA-script rules. If no regex matches, the title is left unchanged.
Useful to add icons depending on the window title, e.g.:
```json
"sway/window": {
"rewrite": {
"(.*) - Mozilla Firefox": " $1",
"(.*) - zsh": " [$1]",
}
}
```
Examples:
- Firefox:
-  before ![before patch](https://i.imgur.com/LmBSMUy.png)
-  patched ![after patch](https://i.imgur.com/mhSCDGr.png)
- Terminal / zsh: 
- before ![before patch](https://i.imgur.com/0RSj65m.png)
- patched ![after patch](https://i.imgur.com/Ev0v2U9.png)

Add option to rewrite sway/window title

---

src/modules/pulseaudio.cpp

Apparently, pipewire-pulse slightly changed the naming of the sink.
To me it looks like this name parsing is in general quite prone to this kind of bugs but I don't know pulseaudio/pipewire and what additional ways it might provide for this kind of information so for now I just sticked to the way it was already handled anyway.

[modules/pulseaudio] fix bluetooth class for PipeWire

---

src/modules/battery.cpp

`format-discharging-full` has been impossible since #923 made it impossible to be full and discharging at the same time. This should fix that by only making `format-charging-full` impossible. Whether or not that should be allowed is a good question, but beyond the scope of this change.
Fixes #1031

[modules/battery] allow format-discharging-full

---

src/modules/sway/window.cpp

For example, before if I had
```json
"rewrite": {
"a": "x",
"b": "y"
}
```
and my window title was `ab` it would get rewritten to `xb`, with this PR it's `xy` (for a specific use-case, I use it to rewrite my home dir to ~ and add icons without having really weird regex logic)
Open question: do we want to have this match in the middle of titles? You can easily opt out of that behaviour with `^$` but it's a lot harder to opt in (you'd need something like `(.*)pattern(.*) => $1...$n`)

rewriteTitle: allow multiple sequential rewrites

---

src/client.cpp

This is to allow text editors such as Visual Studio Code to recognize that the file is a JSON file and add syntax highlighting accordingly

Add options to use a .json extension for the config filename

---

include/bar.hpp
man/waybar.5.scd.in
src/bar.cpp

So I sneakily added the `overlay` layer value in one of the previous PRs, but it wasn't behaving as a real `overlay` mode of `swaybar`. Here's the two missing bits: input passthrough flag that makes the bar ignore any pointer events and allows the window underneath to handle those, and a flag to disable the exclusive zone.
Possible uses:
- A bar on the `bottom` layer with `"exclusive": false` which is only visible on an empty workspace.
- A transparent bar on the `overlay` or `top` layer which shows some data over the application window, but cannot be interacted with.
- If you look closely at the swaybar `hide` mode (the one where you only see a bar when the binding is pressed), it actually does not set exclusive zone but still accepts input.
Now we can get _almost_ similar behavior with …

Add config options for exclusive zone and input event passthrough

---

src/modules/network.cpp

- one fix for wifi network appearing as disconnected after some time.
- one improvement, to fetch wifi essid as soon as available instead of after some time.

Fix network module rework

---

src/modules/sway/language.cpp

When using e.g. [wtype](https://github.com/atx/wtype), which also sends events to emulate keyboard presses, this confuses Waybar and incorrectly hides the module. This fix will ensure compatibility with `wtype`, simply ignoring events where layout is not set, and only reacting on events which actually change the keyboard layout.

sway-language: ignore events with empty layout

---

include/modules/network.hpp
src/modules/network.cpp

That should fix the interface auto detection when NetworkManager is used.

Fix network interface auto detection

---

include/util/sleeper_thread.hpp

The changes in GCC 11.x made `std::condition_variable` implementation
internals `noexcept`. `noexcept` is known to interact particularly bad
with `pthread_cancel`, i.e. `__cxxabiv1::__force_unwind` passing through
the `noexcept` call stack frame causes a `std::terminate` call and
immediate termination of the program
Digging through the GCC ML archives[1] lead me to the idea of patching
this with a few pthread_setcancelstate's. As bad as the solution is, it
seems to be the best we can do within C++17 limits and without major
rework.
[1]: https://gcc.gnu.org/legacy-ml/gcc/2017-08/msg00156.html
Fixes: #1065
***
I'm running the patch for last few days and the crashes are gone. Let's ask more people to test before merging though.
Fedora build: …

fix(util): protect std::condition_variable methods from pthread_cancel

---

include/client.hpp
man/waybar.5.scd.in
src/client.cpp

Hey,
so I've tried my hand at implementing recursive configuration imports with an "include" array:
```
"include": [
"$HOME/.config/waybar/included_file"
]
```
**Disclaimer:** I have next to no experience in C++ so I very possibly could've built an error into this. I would welcome it very much if you would be able to have a close look at it.
Some things:
- It does not break existing configs, at least not in my tests.
- It simply tries to recursively merge configuration files specified in an "include" array with the main file.
- Duplicate keys are overwritten. Since it's a bottom-up recursion, the main file overrides included files.
- It is a tiny bit slower for standard configurations since it recursively copies instead of directly assigning the config.
- Cyclic imports completely break …

Add recursive config includes

---

include/util/format.hpp
src/modules/clock.cpp

Attempting to fix compatibility with libfmt-8.0.0 mentioned in #1143 and https://bugs.gentoo.org/797649. I don't really have any idea what I'm doing in C++, so criticism welcome (and probably necessary).
The issue with parse_nonnegative_int comes from the libfmt change [here](https://github.com/fmtlib/fmt/commit/e421d527), where the third argument becomes an integer. Previously on error the function returned -1, now it returns the third argument, which I've changed to -1 here. I'm unsure about side effects of the ctx object no longer being passed into `parse_nonnegative_int`. This function was also moved from `fmt/format.h` to `fmt/core.h` and namespaces seem to have changed along the way, so specifying `fmt::detail::` makes it compile (for me) but not sure if there's a better way. …

libfmt >=8.0.0 compatibility

---

.github/workflows/freebsd.yml
.github/workflows/linux.yml
Dockerfiles/fedora

Travis CI jobs haven't been running for months and FreeBSD was failing due to an ntp sync issues. It's time to do something about that :)
@Alexays, if you are going to merge that, please update the container images. And maybe it's time to delete .travis.yml and any other leftovers of Travis CI integration.
***
Another option I considered is to move everything to https://builds.sr.ht/. That'll certainly make FreeBSD jobs faster, avoiding the abomination of spinning a FreeBSD VM on a MacOS builder.
SourceHut is currently moving to a paid subscription model though and may require $20/year subscription in the future. I don't know the current status, but we can always ping Drew or Simon if that sounds interesting.

Add GitHub CI jobs on Linux

---

include/client.hpp
man/waybar.5.scd.in
src/client.cpp

Do not fail to parse a multi-bar config

---

include/ALabel.hpp
include/modules/pulseaudio.hpp
man/waybar-pulseaudio.5.scd
src/ALabel.cpp
src/modules/pulseaudio.cpp

Should implement https://github.com/Alexays/Waybar/issues/1121
Allow device name (such as alsa_output.pci-0000_00_1f.3.analog-stereo) to be used as key in pulseaudio format-icon configuration.

Support per-device icon in pulseaudio

---

include/modules/pulseaudio.hpp
src/modules/pulseaudio.cpp

In a system with multiple sinks, the default sink may not always be
the once currently being used. It is more useful to control the
currently active sink rather than an unused one.
This patch does not make any difference if the system only uses the
default sink.
Signed-off-by: Roosembert Palacios <roosemberth@posteo.ch>

pulseaudio: Control currently running sink

---

src/modules/sni/item.cpp

Fixes https://github.com/Alexays/Waybar/issues/1077. The approach here is to scale the icon size using the Gtk scale factor, create a cairo surface from the loaded pixbuf, and use that cairo surface for the image. The cairo surface will use the scale factor from the given window, which makes everything render correctly.
Screenshots:

Fix blurry tray icons for HiDPI displays

---

include/modules/sni/item.hpp
man/waybar-tray.5.scd
resources/style.css
src/modules/sni/item.cpp

Assorted enhancements for tray module.
I had to drop the tooltip icon changes with intent to finish those later, once I have a complete grasp of a possible implementation.
Need to take another look at `update_pending_` for possibility of races. Shouldn't be a blocker for the merge though, as I haven't found anything harmful so far. Only a minuscule chance of missing a property update.
- Try to optimize updates by assuming that signals don't lie and could be using to infer all modified properties. A somewhat risky assumption, given how broken is an average sni client implementation, but I've seen other trays working like that.
- Support tooltips for tray items (text only).
- Support `Scroll`  SNI method.
- Support `Status` property: hide `Passive` items by default; attach corresponding CSS …

tray module enhancements

---

.github/workflows/freebsd.yml
README.md
include/factory.hpp
include/modules/keyboard_state.hpp
man/waybar-keyboard-state.5.scd
man/waybar.5.scd.in
meson.build
meson_options.txt
resources/config
resources/style.css
src/factory.cpp
src/modules/keyboard_state.cpp

Adds a new module which shows the state of num lock, caps lock, and scroll lock.

Keyboard state module

---

resources/waybar.service.in

Currently waybar _can_ try to start even if there's no graphical session (and
no sway) running. Adding `Requisite=` prevents this. From `systemd.unit(5)`:
Requisite=
Similar to Requires=. However, if the units listed here are not started
already, they will not be started and the starting of this unit will
fail immediately.  Requisite= does not imply an ordering dependency,
even if both units are started in the same transaction. Hence this
setting should usually be combined with After=, to ensure this unit is
not started before the other unit.
When Requisite=b.service is used on a.service, this dependency will show
as RequisiteOf=a.service in property listing of b.service.  RequisiteOf=
dependency cannot be specified directly.

Don't start if graphical-session is not running

---

include/modules/sni/item.hpp
src/modules/sni/item.cpp

This PR fixes https://github.com/Alexays/Waybar/issues/1175 and refactors the code around updating the image to separate fetching the correct pixmap and scaling the pixmap.
The root cause of https://github.com/Alexays/Waybar/issues/1175 is that for certain icons, such as the network manager wireless signal icons, the requested icon size may not be available (the network manager applet only supplies a 22x22 pixel version of the wireless signal icon). There is some logic in `updateImage` for proportionally scaling the icon pixbuf if it did not match the requested icon size. However, the code branch in `updateImage` where the icon was loaded using `getIconByName` did not apply this resize logic, resulting in situations where, e.g., the pixbuf is too small.
In this PR, `updateImage` has been …

Fix incorrect tray icon scaling

---

include/modules/river/tags.hpp
man/waybar-river-tags.5.scd
protocol/river-status-unstable-v1.xml
src/modules/river/tags.cpp

Upstream river has a concept of urgent views/tags as of commit e59c2a73.
Introduce a new urgent style to expose this in the waybar module.
References https://github.com/ifreund/river/pull/397

river/tags: support urgent tags

---

include/modules/sway/language.hpp
src/modules/sway/language.cpp

Add number to the end of shortDescription if several variants for layouts and they aren't displayed.

fix: Add number to shortDescripton

---

include/modules/sni/host.hpp
include/modules/sni/item.hpp
src/modules/sni/host.cpp
src/modules/sni/item.cpp
src/modules/sni/tray.cpp

Fixes another trailing issue from https://github.com/Alexays/Waybar/issues/1175#issuecomment-890679048 where the incorrect tray icon size was sometimes used on multi-display setups. This issue seems to occur only on multi-display setups, and it seems to happen when tray items are added before the bar has been properly configured for both displays. This fix adds an event handler to the `signal_configure_event` in the tray `Item` class that calls `updateImage`, which results in the image being correctly resized when the bar's window configuration changes.
Before this change, I was able to repro the issue 1/3 of the time (out of 30 tries). Afterwards, I am unable to repro.

Fix tray icon scaling on multi-display setups

---

src/modules/sway/language.cpp

- Delete previous Layout before creating next one, and in destructor
- Use stack XKBContext instead of local new+delete
- Lock mutex in update() as it is called from a different thread than onEvent(res)

Fix memory leak and data race

---

README.md

travis-ci config was removed in a8edc0886d6524e3df46e58f98bc86184fa05bb1, so I guess the shield should go, too.

rm travis-ci shield

---

src/modules/backlight.cpp

round the brightness percentage instead of flooring it and displaying inaccurate results

round brightness

---

src/modules/sni/item.cpp

This fixes the following compiler warning:
```
[89/91] Compiling C++ object ....p/src_modules_sni_item.cpp.
../src/modules/sni/item.cpp: In member function ‘Glib::RefPtr<Gdk::Pixbuf> waybar::modules::SNI::Item::extractPixBuf(GVariant*)’:
../src/modules/sni/item.cpp:290:48: warning: ‘void* g_memdup(gconstpointer, guint)’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
290 |           array = static_cast<guchar*>(g_memdup(data, size));
|                                        ~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
from /usr/include/glib-2.0/gobject/gbinding.h:28,
from /usr/include/glib-2.0/glib-object.h:22,
from /usr/include/glib-2.0/gio/gioenums.h:2,
from /usr/include/glib-2.0/gio/giotypes.h:2,
from /usr/include/glib-2.0/gio/gio.h:26, …
```

Use g_memdup2 instead of g_memdup

---

Makefile
include/modules/network.hpp
man/waybar-network.5.scd
resources/config
src/modules/network.cpp

I didn't find any way to include the gateway without altering the code. So I did. I greped all the files for `ipaddr`, hoping I catched all the conventions.
I also added a new makefile target (`debug-run`), just because I was annoyed it didn't exist already.
Having `"format-ethernet": "{ipaddr} / {cidr}", "tooltip-format": "{ifname} via {gwaddr}"` feels good and natural. Check the `resources/config` I modified.

Added support for {gwaddr} as a variable

---

include/modules/cpu.hpp
man/waybar-cpu.5.scd
src/modules/cpu/common.cpp

This is a second attempt to merge #1250. I have added conditional check on fmt version as was suggested by @alebastr.
I checked their commit history and found that separation of headers was made about time when 7.1.3 was released, but this change was actually introduced only in 8.0.0. Seems to be correct.
Also I moved header inclusion in cpp file, because this compliant with google-style mention in the README.

Add cpu usage for every core

---

subprojects/catch2.wrap

Fixes #1255, now using pooled meson wrapdb database.

Update catch2 dependency 2.13.3 -> 2.13.7

---

src/modules/sni/item.cpp
src/modules/sni/tray.cpp

`show_all` call from `Tray::update` attempts to walk the widget tree and
make every widget visible. Since we control individual tray item
visibility based on a `Status` SNI property, we don't want that to happen.
Modify `Tray::update` to control the visibility of a whole tray module
only and ensure that the children of `Item` are still visible when
necessary.
***
Fixes the issue described in https://github.com/Alexays/Waybar/pull/1145#issuecomment-922361054.
The code didn't change since the initial fix, I just was too ~~lazy~~busy to format the commit message and send the PR :smiley:

fix(tray): fix visibility of Passive items

---

include/modules/clock.hpp
man/waybar-clock.5.scd
src/modules/clock.cpp

Fix: #911 
Also fixed timezones behavior: now Waybar starting with the first timezone in `timezones` list and falling back to the `timezone` field only if timezones omit or has no elements.

Fix Clock crash on empty string in timezones field

---

src/modules/sway/window.cpp

Quick fix suggestion for #1272 .
Tested briefly with solo, empty and normal and seemed to work so far.

sway/window: include floating_nodes when considering window count for class

---

src/modules/mpd/mpd.cpp

If the primary output does not support changing volume MPD will report `-1`.
Ensure that negative volume levels will be represented as `0` instead.
Signed-off-by: Sefa Eyeoglu <contact@scrumplex.net>

Ensure MPD volume is not negative

---

include/modules/river/tags.hpp
man/waybar-river-tags.5.scd
protocol/meson.build
protocol/river-control-unstable-v1.xml
src/modules/river/tags.cpp

I added some basic mouse click support for river/tags.
Left mouse click - set-focused-tags
Right mouse click - toggle-focused-tags
Fixes #1189

river/tags: Add possibility for mouse clicks

---

.github/workflows/freebsd.yml

Use latest action v0.1.5.
Pin runner to macos-10.15. macos-latest will start using macos-11 images without VirtualBox in less than a month.

ci: update FreeBSD configuration

---

include/modules/network.hpp
src/modules/network.cpp

This fixes issue #610 by reading bandwidth usage per-interface from
/proc/net/dev instead of globally via /proc/net/netstat. It supports the
same matching logic as elsewhere, so setting interface to '*' should
display the same sum-total bandwidth usage as the previous
implementation.

Switch network module to read /proc/net/dev

---

src/modules/network.cpp

just like https://github.com/Alexays/Waybar/pull/834 but for the network name.

dont escape essid in tooltip

---

resources/custom_modules/mediaplayer.py

Handle the Broken Pipe error thrown by `sys.stdout.flush()` (as Python ignores SIGPIPE by default), when piping `mediaplayer.py` to `head -n0` for example.

mediaplayer.py: Exit properly on SIGPIPE

---

meson.build
meson_options.txt
protocol/meson.build
src/factory.cpp

As requested in https://github.com/Alexays/Waybar/pull/805

build: Add experimental build option

---

include/bar.hpp
include/group.hpp
man/waybar.5.scd.in
meson.build
src/bar.cpp
src/group.cpp

This PR adds a module group feature. A module group contains multiple modules and renders them orthogonal to the bar direction (ie stacked vertically for a horizontal bar and vice versa).
My use case for it is that I want a vertical bar but I want some modules to share the same row on the bar. This may sound like a waste of screen space but I'm using waybar as an overlay that is most often hidden, and show on demand. A screenshot of my setup follows, volume/brightness bars are implemented each with two modules (one for the icon, one for the bar) placed in a group. Progress bars use CSS linear gradients as their background.
The way a group is configured is as follows:
```json
{
"modules_left": [
"module_a",
"group/mygroup",
"module_b"
],
"group/mygroup": {
"modules": [
"module_c", …
```

Add module group feature

---

src/modules/pulseaudio.cpp

A previous build fix changed the logic for per-device pulseaudio icon selection and used the source name instead of sink.
As some users might be using it based on source, I have added the sink in addition to the existing one.

Allow sink in addition to source for pulse icon

---

.github/workflows/freebsd.yml
include/bar.hpp
include/client.hpp
include/modules/sway/bar.hpp
include/util/SafeSignal.hpp
man/waybar.5.scd.in
meson.build
src/bar.cpp
src/client.cpp
src/modules/sway/bar.cpp
test/GlibTestsFixture.hpp
test/SafeSignal.cpp
test/meson.build

This feature makes waybar a client for the Sway bar IPC protocol and allows controlling some aspects of the bar behavior with  `swaymsg`
Documentation: [i3 bar display modes](https://i3wm.org/docs/userguide.html#_display_mode), [`sway-bar(5)`](https://github.com/swaywm/sway/blob/master/sway/sway-bar.5.scd)
* Sway
* Single bar configuration block (i.e. `$XDG_CONFIG_HOME/config/waybar` is a JSON object)
* The bar is started from the sway config with `swaybar_command waybar`
1.  Add `"ipc": true` to the waybar configuration
1. Set the desired `mode`, `hidden_state` and `modifier` in **the same** bar configuration block as `swaybar_command`   
*  Sway will assign the default identifier `bar-0` to the only bar instance and run waybar as `/usr/bin/waybar -b bar-0`
*  Waybar will read one bar …

Yet another swaybar ipc implementation

---

include/modules/clock.hpp
src/modules/clock.cpp

After this refactoring:
1. Timezones parses only once on start and the we refer to saved values. All time_zone.isString() checks gone to the constructor.
2. Single timezone case handling as case of multi timezoned logic.
3. Scroll event seems more clear now.
4. Tooltip template parses on start to check if there calendar placeholder or not. To do not calculate calendar_text() if not necessary.
This is preparations for another feature which I'll bring in separate PR.
Any feedback is appreciated.

Refactor Clock: generalize multi timezones and single timezone cases

---

include/bar.hpp
src/bar.cpp

There is a double delete situation which causes a SIGSEGV to happen
during destruction of bar.
This was introduced by the group feature patch.
The same object pointer is stored in two different vectors of
unique_ptr<AModule> element. Replace with shared_ptr to handle
reference counting correctly and avoid double delete.

bar: Fix crash when unplugging HDMI

---

src/modules/pulseaudio.cpp

When natural scrolling is enabled, the behavior of scrolling on pulseaudio
module is reversed, i.e. scrolling up reduces the volume, which is not expected.
This commit reverses the direction of scroll variable if "reverse-scrolling" is set to 1 in the config file like below.
`pulseaudio {
"reverse-scrolling": 1
}`
resolves #1220

Add reverse scrolling config option for pulseaudio module

---

src/modules/network.cpp

By definition, the best possible signal strength is -30dBm, so having -20dBm here doesn't make sense
Reference (can Ctrl+F for -30dBm): 
https://eyenetworks.no/en/wifi-signal-strength/
https://www.metageek.com/training/resources/wifi-signal-strength-basics/
As a small note, signal strengths in the -30s and -40s dBm actually is __not__ good - it is too strong and can cause errors between hosts and a receiver. Often, the maximum desirable levels are in the -50s dBm. Thinking about creating a seperate pull request to adjust the signalStrength value to account for this? Thoughts?

Adjust max wifi strength that is possible

---

README.md
include/modules/network.hpp
src/modules/network.cpp

This pull request contains a series of enhancements to the network module, separated out by commit. #3 and #4 on this list would require updates to the Wiki as well.
1. But first, a build dependency issue. Versions >=0.9.0 often do not build on Debian with the existing build dependencies. "xkbregistry" is required, but not supplied using the current list of Debian packages on the READme. I added the "libxkbregistry-dev" package to the READme under the command to install all required dependencies for Ubuntu.
2. Signal strength calculation. The previous calculated percentage was just a raw scale from -30dBm to -90dBm. While -30dBm is the strongest possible signal for wifi, if a signal is too strong, it can overwhelm receiving circuity that is designed to pick up and process a certain signal …

Network Module Enhancements

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

Ensure that sway workspaces are always displayed in the same order as
used internally by sway. The previous sorting code always sorted
unnumbered workspaces lexicographically. This isn't the order used by
sway internally. Therefore, commands such as "workspace next" might have
jumped arbitrarily in waybar.
This commit reworks the sorting code such that the internal order is
always obeyed. Additionally, numbered persistent workspaces are inserted
at their natural position at the front of the workspace list while
unnumbered ones are appended. This should match the expectations of
workspace ordering known from sway's behavior.
The changes make the configuration property "numeric-first" unnecessary
as this will always be the case now. There's also no reasonable way
around this behavior now. …

fix: match sway workspace order with sway one

---

Dockerfiles/alpine
include/modules/clock.hpp
include/util/waybar_time.hpp
meson.build
src/modules/clock.cpp
test/SafeSignal.cpp
test/config.cpp
test/main.cpp
test/meson.build
test/waybar_time.cpp

* Stop using `fmt::formatter<std::tm>` implementation details
* Add tests for the `waybar_time` formatter
Tests might be a bit fragile as the `date::format` output depends on an underlying STL locale implementation. Any difference there is a bug though, and things are working on two stdlib implementations I tested.
Alpine build fails as the tests require timezone data. Dockerfile change in the top commit should address that.
Fixes #1368, #1379

Fix build with fmt 8.1.0

---

src/modules/clock.cpp

Fixes #1393
When formatting the clock, pass the locale to the fmt function.

fix: Use locale when formatting clock

---

src/modules/battery.cpp

According to the [sysfs class power ABI], `/sys/class/power_supply/<supply_name>/status` may contain "Not charging".  This is already handled by `status_gt()` and `update()` (where `' '` is converted to `'-'` for use in config keys) but was not being read due to `skipws`.  Read with `std::getline()` to handle this case.
[sysfs class power ABI]: https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power
Fixes: #1139
Thanks for considering,
Kevin

battery: read status with spaces

---

src/modules/sway/language.cpp

This PR fixes a segmentation fault that happens on startup when there is a keyboard layout in use that does not appear in the `XKBContext` object. This may happen when one has a custom layout in e.g. `~/.xkb/symbols`.
Fixes #1387, possibly #1307

sway/language: fix segmentation fault for layouts not found in XKBContext

---

src/AModule.cpp

When they were uninitialized it caused getScrollDir() to incorrectly return SCROLL_DIR::NONE in some circumstances (especially in multi-bar setups).
This should fix:
#1287
#1398 
And maybe others

Properly initialize distance_scrolled members.

---

src/modules/clock.cpp

Seems like the tooltip text should only be set if both `if (tooltipEnabled())` and `if (config_["tooltip-format"].isString())` passes.
Addresses #1414

Fix disabled tooltip on clock module

---

man/waybar-tray.5.scd
src/modules/sni/tray.cpp

At the moment when a new appindicator is added, the icon gets added to the end which isn't very good if the tray is positioned on the right of the bar.
With `reverse-direction` set to true, new app indicators get added to the start

Reverse the tray icon order

---

man/waybar-clock.5.scd

Add tooltip documentation to the clock man page now that disabling it works.
(forgot to do this in #1418, as mentioned in #1414)

Update man page clock module - tooltip

---

include/util/format.hpp
src/modules/sni/item.cpp

this formatter is useful for other modules
which want to print Glib exceptions messages

move Glib ustring format helper to utils

---

src/modules/cpu/common.cpp

Limit cpu load figure to 2 digits right of decimal point - standard formatting for cpu load
Fixes #1443

CPU Load Formatting Fix

---

resources/style.css

If there is some other font installed that 1) matches the four existing font families and 2) provides its own glyph in the private use area used by Awesome, then that font's glyph will be used instead of the intended icon.
For example, the following character (U+F001, ["music"](https://fontawesome.com/icons/music?s=solid)):  ...looks like a pair of musical notes in fontawesome, but DejaVu Sans also provides a glyph, which looks like a couple of squares. DejaVu Sans matches first when "sans-serif" is requested, so its (unrelated) glyph is used.

style.css: add fontawesome to beginning of font list

---

src/bar.cpp

Fixes #1449.
Fixes #1439.
Fixes #1402.
The problem here is that if a custom module's JSON fails to parse, then the exception handling code will attempt to log the module name after it's been freed. This may cause `name.asString()` to throw an exception. This commit fixes the issue by capturing the name by value.
Valgrind output before the change:
<details>
```
valgrind ./build/waybar -c config.json
==94675== Memcheck, a memory error detector
==94675== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==94675== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==94675== Command: ./build/waybar -c config.json
==94675==
==94675== Warning: ignored attempt to set SIGRT32 handler in sigaction();
==94675==          the SIGRT32 signal is used internally by Valgrind …
```

avoid use-after-free in lambda

---

src/modules/mpd/mpd.cpp

Pretty self-explanatory single-line change. Currently the song position is zero-indexed, which aside from not really looking good when you're playing song 0 of 1, doesn't match `mpc`'s interface (e.g. `mpc play 0` errors).

Add 1 to songPosition in the MPD module

---

man/waybar-sway-window.5.scd

Default changed in bcadf64031ee0520212aa8f092f5ac14122cd924 and it
wasn't documented.
I was surprised about the change in the recent release and didn't find anything in the man-page.
Relevant change is here: https://github.com/grmat/Waybar/commit/bcadf64031ee0520212aa8f092f5ac14122cd924#diff-502183048a020c02261fe9061cae986f05fbe87113c79dd5257952b0b60a3a24R25

man: document icon in sway/window module

---

include/modules/clock.hpp
man/waybar-clock.5.scd
src/modules/clock.cpp

Introducing new tooltip placeholder: {timezoned_time_list}. It will be replaced with the list of times in different time zones from the config.
I've found it useful to hover the mouse pointer on time and see time in all my timezones at once. Current timezone excluding for the list, so if you will scroll over the time module and change the active timezone, this timezone will be excluded from the list and the previous active zone will be added.
How it works for me:
I know that this feature wasn't requested, but I found it very useful for me and hope it will be useful for someone else, who working remotely or have another kind of interest in other timezones.
Refactoring in #1277 was done as a preparation for this feature =)
Any feedback will be highly appreciated.

Feature Clock: show list of time in other timezones in a tooltip

---

resources/config

Supersedes https://github.com/Alexays/Waybar/pull/873
uses symbols instead of emoji
@Synthetica9 @roland-rollo

use moon phases for backlight format-icons

---

src/modules/sway/language.cpp

Hi.
I am using the `EurKEY` (`eu`) keyboard layout, which apparently is an "exotic" one.
Since waybar does not load the exotic ones, there is nothing displayed in the bar for the language module.
See my comment https://github.com/Alexays/Waybar/pull/1406#issuecomment-1059074832

sway/language: Load exotic xkb rules too

---

src/bar.cpp

Fixes #958 and #491 (or at least [this comment](https://github.com/Alexays/Waybar/issues/491#issuecomment-799217823)), this way if the bar is configured to be in overlay mode, it will stay in that mode when it's re-shown after being hidden. If there's a better way to do this, let me know, I just reused the code elsewhere that retrieved the config mode in the first place

Use user-defined mode when toggling visibility rather than resetting to default

---

src/modules/network.cpp

Hi, this is a simple PR to add B/s for network speed, since it's the standard for non french speakers.
Since an octet is a byte, the code was already there.

feat: added network speed in Bytes

---

src/modules/temperature.cpp

Actually even is set `"format" : ""` waybar displays some spaces. But when user wants to have the only notification when temperature threshold is triggered it looks not so good.
Current fix does:
1. If nor `"format" : ""` neither `"format-critical" : ""` is defined - throw an exception in order to have temperature module disabled during the start process
2. If "format" is empty and critical threshold is not triggered - hide the module
config example:
```
"temperature": {
// "thermal-zone": 2,
// "hwmon-path": "/sys/class/hwmon/hwmon2/temp1_input",
"format": "",
"critical-threshold": 90,
"format-critical": "<span font-family=\"Font Awesome 5 Free\">{icon}</span> {temperatureC}°C",
"format-icons": ["", "", ""],
"interval": 10
},
```

Hide/Unhide temperature module when "format*" is empty.

---

src/modules/battery.cpp

I have a device with a battery driver that is not currently supported by your battery module. A PineNote with a Rockchip RK817 battery controller. The driver is not upstreamed yet, but I think the changes are generic enough for this not to matter.
```
» ls /sys/class/power_supply/rk817-battery/
charge_empty_design  charge_full_design  charge_type                  constant_charge_voltage_max  current_boot  hwmon0  present  subsystem  uevent       voltage_boot        voltage_min_design  wakeup4
charge_full          charge_now          constant_charge_current_max  current_avg                  device        power   status   type       voltage_avg  voltage_max_design  voltage_ocv
```
It does not have a capacity, so it fails the initial check, and it does not have `current_now` or …

Battery module support for rk817

---

include/AModule.hpp
src/AModule.cpp

Added opportunity of the double/triple mouse events according https://github.com/Alexays/Waybar/issues/1068
It's better do not mix different types of clicks per button (Gdk for triple click raises single and double click before triple click)
1. on-double-click
2. on-triple-click
3. on-double-click-middle
4. on-triple-click-middle
5. on-double-click-right
6. on-triple-click-right
7. on-double-click-backward
8. on-triple-click-backward
9. on-double-click-forward
10. on-triple-click-forward

Waybar. Issue#1068. Double/Triple events

---

include/modules/sway/ipc/ipc.hpp
src/modules/sway/language.cpp

As we always use the enum to compare or initialize uint32_t values, it would be better to declare it with the right type. This way we could avoid `-Wnarrowing` warnings or unnecessary type casts.

refactor: change `enum ipc_command_type` to uint32_t

---

include/modules/clock.hpp
src/modules/clock.cpp

Config example:
`"clock": {
// "timezone": "America/New_York",
"format": " {:%b %d %Y (%R)}",
"tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
"format-alt": "{:%Y-%m-%d}",
"today-format": "<span color='#ff6699'><b><u>{}</u></b></span>",
"week-pos": "left",
"week-format": "<span color='#99ffdd'><b>{}</b></span>",
"interval": 10
}`
Screenshots:

#1315. Add option to display week number on calendar

---

include/modules/sway/window.hpp
src/modules/sway/window.cpp

If Gtk objects get updated from another thread than the main thread, GTK
can get confused. This is a regression of bcadf64031ee0520212aa8f092f5ac14122cd924.
Fixes #1464, #1474
EDIT: I'm not entirely sure it will solve #1464.

Sway/window: Only update icon from main thread

---

src/modules/clock.cpp
src/modules/simpleclock.cpp

I think this addresses #1226 and potentially #1497.
On FreeBSD, the change does not have any effect, but doesn't make it worse, either.

Replace sleep_until with sleep_for to prevent clock from getting stuck with system time adjustment

---

include/modules/sway/bar.hpp
man/waybar.5.scd.in
src/modules/sway/bar.cpp

- Show bar if a workspace becomes urgent
- Clear urgency hint with modifier press
- Show bar on sway mode
Feedback on the coding is welcome, not sure with regards to the signal and ipc creation.
I followed the comment in [swaybar](https://github.com/swaywm/sway/blob/master/swaybar/ipc.c#L450) to implement the behavior to hide the bar again after the modifier is pressed.
But my implementation might differ a bit as it will show the bar again if multiple workspaces have the urgency hint, the bar is hidden again, and then one of the urgent workspaces is focused. For me this makes sense as it will give a notification that other workspaces sill have the urgency hint.

Show hidden bar

---

src/modules/backlight.cpp

Reading brightness value for backlight device can fail intermittently (particularly when using ddcci-driver-linux). Handle this more
gracefully rather than crashing
fixes #1409

Backlight: avoid crash on getting brightness fails

---

src/modules/network.cpp

There was discussion on #1392 about implementing matching interface cycling to the network module, but as that is a more complex feature, this will patch the issue for the current single interface mode.
Tested working with `network.interface: <undefined>/null/"enp*"/"enp6s0"`

network: calculate bandwidth for current interface

---

include/factory.hpp
include/modules/bluetooth.hpp
man/waybar-bluetooth.5.scd
meson.build
src/factory.cpp
src/modules/bluetooth.cpp

Resolves #688 
Goal is to show selected bluetooth adapter and its connections. Still a work in progress.
TODO:
I also noticed that there is no entry for the bluetooth module in the wiki. So that should also maybe be added.
Possible future improvements not part of this merge request:
- show icon field of the connected bluetooth device when available using a config defined icon theme/size
- have format-icons for the connected device battery percentage
- change the selected connected device that appears in the main label changeable via scrolling or clicking?? Don't know how that would interact with the current format-device-preferences or show the latest connection model.
- also enumerate disconnected devices in the tooltip (e.g. by adding a tooltip-format-enumerate-paired option)

feat: extend bluetooth module

---

man/waybar-keyboard-state.5.scd
src/modules/keyboard_state.cpp

Allow labels for numlock/capslock/scrolllock to be styled independently by adding classes to them.
_Use case:_ unknowingly having caps lock on while entering a password is annoying --- I'd like to have the caps lock state indicator styled in red when stated is locked, but don't want num lock state indicator to also be red when state is locked.

Add classes to individual keyboard state labels

---

src/modules/cpu/common.cpp

When parseCpuFrequencies returns an empty vector, getCpuFrequency
would attempt to dereference an invalid iterator.
Return early from getCpuFrequency when parseCpuFrequencies returns an
empty vector.
Resolves a segfault when waybar is run within a VM on apple silicon.

Prevent segfault in getCpuFrequency

---

include/modules/battery.hpp
src/modules/battery.cpp

[ISSUE#1556](https://github.com/Alexays/Waybar/issues/1556)
1. battery.hpp - added local bool variable. Force to print warnings the
only once in order to warn user about wrong battery configuraion. And
does not bring a mess when the battery is turned off (gamepads, etc.)

Issue#1556. Battery module: a lot of warnings when battery dissapears

---

include/factory.hpp
include/modules/gamemode.hpp
man/waybar-gamemode.5.scd
meson.build
src/factory.cpp
src/modules/gamemode.cpp

This PR adds a gamemode module that keeps track of when gamemode is being used. For the people who don't know that gamemode is, here's a [link](https://github.com/FeralInteractive/gamemode).
Features:

Gamemode Module

---

include/modules/sway/window.hpp
src/modules/sway/window.cpp

This adds heuristics for finding the application's icon.
This will not find every icon, but a lot more than currently. I found issues with RenderDoc and JDownloader. But I guess these applications are legacy/X11 applications where icons can only be found with the help of Xlib.
Are you accepting this or would you rather like to adopt an approach like described [here](https://github.com/Alexays/Waybar/issues/1473#issuecomment-1065840022)? I'm unsure if we would have found the icons of the mentioned applications above with this approach.

sway/window: Add heuristics for finding icons

---

src/bar.cpp

Fixes #1568 
Don't unanchor from the side where the bar is supposed to anchor.

fix: vertical bar not anchored when width is set

---

man/waybar-bluetooth.5.scd
src/modules/bluetooth.cpp

- fixes non-existing ```tooltip-format-connected-battery```
- adds back ```format-icons```, which also adds the enabled state as a fallback if one of its derivative states is not defined (on, off, connected). This makes sure old bluetooth configs are fully supported and cause no crashes. (see #1574 #1569). This also supports showing an icon for the battery percentage in the ```*-connected-battery``` format options.
This would avoid further breakage if a new release is made for people who still need to upgrade and have an old bluetooth config.

fixes bluetooth module

---

README.md

Waybar now has two river specific modules, so I thought it worthwhile pointing these out in the README.md as is done for sway.

Advertise river modules

---

man/waybar-network.5.scd
src/modules/network.cpp

This PR adds total bandwidth (`bandwidthTotalBits`, `bandwidthTotalOctets` and `bandwidthTotalBytes`) to the network module.
I have decided against adding a variable at the top of the `update()` method, mostly because it seems calculations are being done on demand if the format is actually requested, but this can be moved if I am interpreting it wrong.
I have also updated the man page, which was missing bytes up/down too.

Add total bandwidth formatting options

---

include/modules/custom.hpp
src/modules/custom.cpp

When adding a custom module with a name, e.g.:
```jsonc
{
...,
"custom/foo#bar": { },
...
}
```
The custom module does not retain the `bar` class as it should, because all the classes are replaced with the runtime output:
https://github.com/Alexays/Waybar/blob/1b4a7b02f46c1bce2eafdde2a76f4a3adec6620e/src/modules/custom.cpp#L141-L147
Avoid removing the module instance name class so css class behavior is consistent between all modules.

Retain instance name css class for custom modules

---

src/modules/pulseaudio.cpp

when the module fails to get the pulseaudio device form factor, the module persists the existing value, resulting in the incorrect format-icon being used to format the label on device changes.
reset the form factor value so that the icon lookup properly falls back to "default" when missing

pulseaudio: avoid retaining outdated form factor

---

.github/workflows/linux.yml
Dockerfiles/gentoo

Hi @Alexays . Is it possible to add one more CI please ? It's Gentoo docker container. It's quite important for me and I guess for Gentoo community too ) 
Please see the final result in my repo: [LukashonakV workflows](https://github.com/LukashonakV/Waybar/actions) with name "Merge pull request 3". Direct Gentoo CI run is [Gentoo run](https://github.com/LukashonakV/Waybar/runs/7212299809?check_suite_focus=true)
How to have container in your Docker repository:
1. You can pull completed container from my repository: [vilu1209/waybar:gentoo](https://hub.docker.com/layers/246668874/vilu1209/waybar/gentoo/images/sha256-cd0834764199ee78758cac347f0343244a6df5e88cb9bc6660f3d9005280380c?context=repo) and push it back in your own. This particular repository contains Gentoo with the necessary …

New Gentoo CI

---

src/modules/sway/language.cpp

A few days ago I opened [this issue](https://github.com/Alexays/Waybar/issues/1615).
Basically it is about adding the layout as class name to the module to allow for more styles without the need of creating a clunky custom module.
I've finally managed to get the code working so I though on trying to push it 😄.

Language: Add layout as class name

---

include/modules/keyboard_state.hpp
include/modules/simpleclock.hpp
include/util/json.hpp
src/client.cpp
src/config.cpp
src/modules/clock.cpp
src/modules/mpd/state.cpp
src/modules/sni/host.cpp
src/modules/sway/bar.cpp

Addresses the following breaking change:
> Disabled automatic `std::ostream` insertion operator (`operator<<`) discovery when `fmt/ostream.h` is included to prevent ODR violations. You can get the old behavior by defining `FMT_DEPRECATED_OSTREAM` but this will be removed in the next major release. Use `fmt::streamed` or `fmt::ostream_formatter` to enable formatting via `std::ostream` instead.
The patch is good enough to fix builds in distributions updating to fmt 9. WIP because it's already late and I need to give it another look tomorrow; there's one more deprecation warning I want to address:
```
../subprojects/fmt/include/fmt/core.h:1711:43: warning: 'map<mpd_idle, 0>' is deprecated [-Wdeprecated-declarations]           
const auto& arg = …
```

fix: adapt to fmt 9.0.0 breaking changes

---

src/modules/sni/item.cpp

For me this fixes the issue of Nextcloud showing a missing tray icon. (I do not think that there is an open issue in regards to this.)
I am not sure if there the pixmap given should always be preferred though; I guess this "breaks" theming by not allowing to override the pixmap given from the application with your own theme.
I guess the following may be better:
After checking for the icon name, fall back to the pixmap if it was not found?
*So, if other behavior would be preferred, I could try to implement it accordingly.*
---
Anyway. Currently there is suboptimal behavior when
* an icon name is given
* a pixmap is given
* there is no globally installed icon for the given icon name
because it will then show the "missing icon" icon even though it could use the pixmap.

sni: Use the pixmap if for the given icon name an icon could not be found

---

include/modules/mpd/mpd.hpp
src/modules/mpd/mpd.cpp

By having ``{filename}`` in ``format`` under the ``mpd`` module it's now possible to show the filename (with extension)

mpd: add filename formatter

---

include/modules/sway/window.hpp
man/waybar-sway-window.5.scd
src/modules/sway/window.cpp

This is a very simple pull request, which grants the sway/window module the capability to display the 'shell' parameter from sway tree.
I personally find it very handy whenever I need to check if a certain window is running natively on Wayland or not.
I was wondering if I should also edit the manpage file for sway/window and the wiki.
Please feel free to correct my mistakes and formatting.

Feature: sway/window can show 'shell' parameter

---

src/modules/river/mode.cpp
src/modules/river/window.cpp

resolves #1591 
The window and mode text from river is escaped. The user's format is not, however the error will be clear.

#1591 river escape window and mode

---

src/modules/network.cpp

Like #1256 , but escape by calling `set_tooltip_markup()`, because the
label text uses `set_markup()`.

fix(network): dont escape essid in tooltip

---

src/modules/sni/item.cpp
src/modules/wlr/taskbar.cpp

do the same job to wlr/taskbar as [tray](https://github.com/Alexays/Waybar/pull/1174)
before:
after:

scale icons for HiDPI monitor

---

include/factory.hpp
include/modules/hyprland/language.hpp
man/waybar-hyprland-language.5.scd
meson.build
src/factory.cpp
src/modules/hyprland/language.cpp

Shows the current keyboard layout (like sway/language)
config:
- format (duh) like `"Lang: {}"`
- `keyboard-name` for specifying a keyboard to use (recommended to use the one with `AT Translated set ...`) -> if unset, any and all will be used.
Also allows for custom formats per-language:
```
"format-us": "Burger Land",
"format-de": "Germoney",
"format-it": "Mamma mia"
```
PR is le ready.

Added a basic hyprland/language module

---

man/waybar-pulseaudio.5.scd
src/modules/pulseaudio.cpp

Resolves #1607.
Added option to override the maximum volume in the pulseaudio module, defaults at 100.
Edited the manpage.

Add 'max-volume' option to pulseaudio

---

include/config.hpp
src/config.cpp

Please, have mercy. I am a mere go dev, and this is my first attempt at C++. I wanted to add support to reading the config path from an environment variable.
This PR adds support to reading the config base path from the environment variable `WAYBAR_CONFIG_DIR`. If it is set, but no configuration is found there, it falls back to the previous mechanism of using the default paths, without erroring.

Add support for reading the config path from env

---

include/AModule.hpp
include/modules/clock.hpp
src/modules/clock.cpp

Hi @Alexays , there is a small improvement to have scrolling ability on calendar #1545
1. For clock module added general event section "on-scroll"
2. Added subsection: "calendar" which stores int value as an months count for scrolling.
It's implemented not as event on mouse button clicks but through scrolling event which it seems to me more logically. In case when users wants to have both : calendar scrolling and timezone scrolling it's quite simple to extend "on-scroll" block
My config looks like:
```json
"clock": {
// "timezone": "America/New_York",
"format": " {:%b %d %Y (%R)}",
"tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
"format-alt": "{:%Y-%m-%d}",
"today-format": "<span color='#ff6699'><b><u>{}</u></b></span>",
"calendar-weeks-pos": "right", …
```

Issue#1545. Calendar scrolling opportunity

---

man/waybar-battery.5.scd
src/modules/battery.cpp

Currently using, e.g., `"format-time": "{H}:{M}"` results in output that looks weird for minutes < 10. For example if there are 2 hours and 3 minutes of time remaining it is displayed as `2:3`.
This PR adds a `"{m}"` format option that displays minutes always as two digits. Thus we'd have `2:03`, which is much nicer.
I considered casting the time remaining as a time object so that fmt Chrono Formatting (`"%H:%M"`, etc.) could be used, but that would be a breaking change.
p.s. I think I added documentation in all the right places (besides the github wiki), but please let me  know if I missed somewhere.

Add battery format-time option for zero-padded minutes

---

man/waybar-pulseaudio.5.scd
src/modules/pulseaudio.cpp

This adds a new config option, `ignored-sinks`, for the Pulseaudio module, which can be used to stop certain sinks (in my case the EasyEffects sink) from appearing. This is needed as these sinks are always running, and so hijack the volume indicator in the bar.
Example config:
``` json
"pulseaudio": {
"ignored-sinks": ["EasyEffects Sink"]
}
```

Add config option to ignore Pulseaudio Sinks

---

include/modules/idle_inhibitor.hpp
man/waybar-idle-inhibitor.5.scd
src/modules/idle_inhibitor.cpp

This addresses #1585.
The config value is tentatively named `start-activated`.
Let me know if anything looks wrong / needs fixing.

Add config value for inhibitor default state.

---

src/modules/custom.cpp

When having the following line in a custom module:
```
"exec": "echo 'test1 & test2'",
```
running waybar results in:
```
(waybar:3775754): Gtk-WARNING **: 01:21:03.702: Failed to set text 'test1 & test2 ' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

Escape text in custom module

---

src/config.cpp

Some of the logic in the battery module does not cover all possibilities. I've tried to reconcile this by changing the logic flow. Before if some of the `/sys/.../battery/...` files were available it was assumed that others would be although I found this to not be the case. Instead the module now checks for the existence of all files.
I've also added some extra calculations of possible variables which can be calculated from other variables (like how `charge_now` or `energy_now`, etc. can be calculated) which allows `time_remaining` to be calculated when `energy_now` or `power_now` are missing in most cases. Hopefully there isn't anything wrong in my logic, but I've been using it for a few days without any problems.

Some logic issues in battery.cpp

---

include/util/format.hpp

The current implementation of `pow_format` slips into scientific notation when it's formatting a number between 1000 and 1024 in binary mode (for instance, waybar is currently telling me I have `1.02e+03GiB` of disk space free). This PR uses the `f` presentation type instead of `g` to avoid this. Unfortunately, in fixed-point mode, the precision value only controls the number of digits after the decimal point, not the total number of significant figures. I went with `.1f` as a reasonable compromise, and adjusted the padding accordingly to account for having numbers up to 5 characters long in decimal mode, or up to 6 characters long in binary mode (`1023.9`).

Fix binary pow formatting for values between 1000 and 1024

---

src/modules/temperature.cpp

The zone was hardcoded in #1702.
This commit allows to use the "thermal-zone"
variable.
Follow up #1702

[FreeBSD] Use thermal-zone

---

include/modules/hyprland/window.hpp
src/modules/hyprland/window.cpp

Implements #1716
Example config:
```json
"hyprland/window": {
"separate-outputs": true
}
```

[hyprland/window] Add option to show active window on a per monitor basis

---

src/modules/pulseaudio.cpp

This fixes #1115 when many bars are created and destroyed, there will be too many PulseAudio connections.

pulseaudio: disconnect on destruction

---

resources/style.css

Moves the ``border = none;`` attribute from workspace buttons to the global scope. The hover effects on all buttons are now consistent in the default stylesheet.
Resolves problem discussed in #1120.

Remove border effect on hover

---

src/modules/hyprland/window.cpp

Fixes #1732
The hyprland/window widget had an assertion ensuring that the output from hyprctl matched the currently selected workspace id. However this assertion fails if workspaces are switched too quickly, causing the selected workspace to differ in id from the one in hyprctl, failing this assertion which then crashes the entire program.
This fix simply changes this assertion into an if statement, and if a mismatch is found, empty string is returned as the window name.

[hyprland/window] Fix crash on quickly switching workspaces

---

include/modules/wlr/workspace_manager.hpp
man/waybar-wlr-workspaces.5.scd
src/modules/hyprland/window.cpp
src/modules/wlr/workspace_manager.cpp

#1691 didn't work for me. This pull request fixes #1596, by adding the option "sort-by-number" to wlr/workspaces, which takes precedence over any other sort-by option if set to true.
Example config
```json
"wlr/workspaces": {
"sort-by-number": true,
}
```
The icons can still be changed using
```json
"format-icons": {
"1": "a",
"2": "b",
"3": "c",
"urgent": "d",
"active": "e",
"default": "f"
}
```
and the sorting will still be done according to the actual workspace numbers.

Add option to wlr/workspaces to sort workspaces by number

---

include/factory.hpp
include/modules/battery.hpp
meson.build
src/factory.cpp
src/modules/battery.cpp

This commit aims to propose a FreeBSD to gain battery support using sysctl on hw.acpi.battery.*
Discharging
Plugged
cc @jbeich

FreeBSD: Add support to battery

---

src/modules/battery.cpp

A pre-processor flag was misspelled and is now corrected.
Fixes #1735

Fix battery indicator crash on linux

---

resources/style.css

Seems like GTK labels have no intrinsic minimal width while buttons do. Probably because they should stay clickable with an empty label.
As a result, even if all margins, padding and borders of buttons are removed the label inside the buttons may still be padded if they are too short. Setting the minimal width of buttons to zero fixes this issue.
This PR sets the ``min-width`` of buttons to zero in the default config, resolving #1731 for future adopters of Waybar.

Set default minimal width of buttons to zero

---

include/AButton.hpp
resources/style.css
src/AButton.cpp

Buttons come with an intrinsic min-width but lack a method to alter this property. Setting the requested size to zero has also no effect on it.
The only way I found to work is to hard code the CSS into the button, added in this PR.

Fix button padding

---

.github/workflows/freebsd.yml
include/modules/keyboard_state.hpp
man/waybar-keyboard-state.5.scd
meson.build
meson_options.txt
src/modules/keyboard_state.cpp

The `keyboard-state` module used the polling mechanism to get the keyboard status by the interval.
But we more like to see the indicator update immediately, just like the `pulseaudio` module.
So, I use libinput keyboard event to listen to the specific key events update when it has been triggered.
And the `thread_` now is an event loop, so the `interval` value has no effect.
This patch is still in progress, such as the wiki page and the man page aren't finished yet.
I will also add the keyboard removal function in this patch because libinput can get the remove event.
But a prerequisite for this is all the devices that needed be listened should be connected before launching waybar, or you need 
to restart waybar, see related issue #1584 .
I need some opinions about this change.

Improve keyboard response time and enable hotplug support

---

src/modules/memory/common.cpp

While configuring Waybar i noticed that the values for `{used}` `{total}` `{free}` `{swapUsed}` `{swapTotal}` and  `{swapFree}` in the memory module don't get rounded, resulting in a really long and ugly floating point number in the output:
so i wrote a quick fix that rounds all the numbers to 2 digits:
tested on NixOS 22.11pre418904.db25c4da285 with Hyprland
my changes also use `float` instead of `auto` because it is less ambiguous and remove the redundant calls of `std::pow(1024,2)`

fixed memory module not rounding numbers

---

src/modules/battery.cpp

When using TLP for threshold, "Not charging" is still being shown, instead of "Plugged".
I don't think it was fixed as mentioned in https://github.com/Alexays/Waybar/issues/1560#issuecomment-1293083222
This should cover:
https://github.com/Alexays/Waybar/issues/253
https://github.com/Alexays/Waybar/issues/1560
Side note: my adapter does not have `/status`, so `current_status` on [L477](https://github.com/Alexays/Waybar/blob/master/src/modules/battery.cpp#L477) will always be empty. This logic is also present at two other places, so I'm not sure if I understand it.I can open a separate issue if it's relevant (Lenovo laptop, Arch).
```cpp
std::getline(std::ifstream(adapter_ / "status"), current_status);
```

Battery: "Plugged" status for TLP settings

---

src/modules/mpd/mpd.cpp

Seems like GTK buttons don't need to / don't support escape codes. Remove escapes from MPD label.
Comparison: (top bar is built off this PR)

fix: don't escape mpd label twice

---

src/modules/backlight.cpp

The backlight module should respect `format-<state>` config like other modules.

Make backlight module respect format-<state> config

---

include/modules/backlight.hpp
src/modules/backlight.cpp

Probably closes #393.
I know you want a more universal / robust solution for hiding any module, but this does what I need and takes less effort :P

feat(backlight): hide if the display is powered off

---

include/modules/hyprland/backend.hpp
include/modules/hyprland/language.hpp
include/modules/hyprland/window.hpp
src/modules/hyprland/backend.cpp
src/modules/hyprland/language.cpp
src/modules/hyprland/window.cpp

Hyprland Window could cause a crash when a monitor is removed. Especially when the "separate-outputs" option is enabled.
This happened because the Window got destructed, after which an event was sent to the Window to notify of an active window change. The Window then tried to parse JSON with a JSON parser that is already deleted, thus causing a crash.
Solution: unregister for events in the Window destructor.

Do not crash when a monitor is removed

---

src/modules/battery.cpp

On laptops with more than one battery the calculation of capacity is broken: the sum of capacities of batteries is displayed (and if this turns out to be bigger than a 100%, it gets clamped to 100%).
The `total_capacity` is computed as a sum over individual capacities of batteries, which can be in the range from 0% to _number of batteries_ * 100%. If `total_capacity` was calculated, the `calculated_capacity` is set to the same value. However, all values over 100% are clamped, since, as explained in the code comment:
> `// This can happen when the battery is calibrating and goes above 100%`
I propose the `calculated_capacity` should be normalized by the number of batteries.

normalize capacity by number of batteries

---

src/modules/pulseaudio.cpp

Using Fedora 37 with pipewire 0.3.60 a bluetooth connected headset is not correctly assigned with the bluetooth class.
The device is recognized as `monitor_source_name = bluez_output.38_18_4C_BD_21_24.1.monitor` thus the check for containing `a2dp_sink` fails.
This PR adds an additional check for the `bluez` substring in the `monitor_source_name`.

Recognize outputs with 'bluez' in monitor name as bluetooth class

---

include/factory.hpp
include/modules/wireplumber.hpp
man/waybar-wireplumber.5.scd
meson.build
meson_options.txt
resources/style.css
src/factory.cpp
src/modules/wireplumber.cpp

Adds basic support for showing volume via wireplumber. Allows specifying the node-id or falling back to the default Audio/Sink node id if node-id is not set. If tooltip on hover is enabled, will show `{node_name}` by default otherwise `tooltip-format`.
Format replacements:
`{volume}` - Volume in percentage
`{node_name}` - The node's nickname (`node.nick` property)

feat: wireplumber support

---

include/modules/hyprland/window.hpp
src/modules/hyprland/window.cpp
src/modules/wlr/workspace_manager.cpp

Fixes #1794 and #1803.
The first crash occurs when trying to parse the ID of a workspace as an uint, since named workspaces has negative IDs (starting from -1337). This is fixed by using ints for workspace IDs instead of uints.
The second crash occurs when converting a workspace name that isn't a number to an integer. This is fixed by wrapping std::stoi in a try block and only sorting by number, when both names can successfully be converted to integers. When one of the workspaces being compared isn't a number it will fallback to whatever other sorting method is enabled.

Fix crashes when using named workspaces in Hyprland

---

include/factory.hpp
include/modules/image.hpp
man/waybar-image.5.scd
meson.build
src/factory.cpp
src/modules/image.cpp

Resolves #1191, #944
Module which renders an image onto the bar.
Example paired with the MPD module:
Example config:
```json
"image/album-art": {
"path": "/tmp/mpd_art",
"size": 32,
"interval": 5,
"on-click": "mpc toggle"
}
```
A few problems:
- For some reason right click isn't working for me. All other events are.
- I don't think the image can be styled
This evening is my first dive into C++ and first dive into GTK so this probably isn't fantastic, so criticism is very welcome.

Add image module

---

src/modules/wireplumber.cpp

Adds basic icon support for the wireplumber module.
This can be achieved by using `{icon}` in the `format` config and pairing it with the `format-icons` config as well.
Example:
```
"wireplumber": {
"format": "{volume}% {icon}",
"format-icons": ["", "", ""]
}
```
Adding because #1811 indicated it wasn't supported.

feat: add icon support to the wireplumber module

---

src/modules/clock.cpp

#1646  introduced scrolling for the calendar tooltip. It seems, however, that this was hardcoded so that scroll up would go to the next month and scroll down would go to the previous month. This is the opposite of what is intuitive for me, so I tried assigning the integer -1 to the month increment, but there is a bounds check to make sure the integer is greater than zero. I think this bounds check is unnecessary, and allowing negative numbers lets the user easily invert scrolling so that up can go to the previous month and down go to the next month.

Allow the calendar month scrolling to be inverted

---

src/modules/hyprland/language.cpp

The current output form of `hyprctl devices` is like this:
```
Keyboard at 6f80ad70:
ITE Tech. Inc. ITE Device(8910) Keyboard
rules: r "", m "", l "us,ru", v "", o "grp:alt_shift_toggle"
active keymap: Russian
main: no
```
That is, `Keyboard at` goes _before_ the keyboard name, so looking for `Keyboard at` only makes it skip to the keyboard _after_ the one that the user specified (or crash if it's the last keyboard in the list).

Don't search "Keyboard at" from hyprland/language

---

src/modules/mpd/mpd.cpp
src/modules/pulseaudio.cpp
src/modules/sndio.cpp

Hides mdp/pulseaudio/sndio module if it's text resolves to being empty. 
Should close #699.

Hide module if text resolves to being empty. Issue #699

---

src/modules/battery.cpp

Hi,
This use time_to_empty_now and time_to_full_now, this is usefull to get a pretty waybar back on asahi linux on macbook.

feat(battery): add macsmc-battery time remaining support for asahi

---

src/modules/battery.cpp

Linux power_supply sysfs interface allows checking if the battery powers the whole system or a specific device/tree of devices with `scope` attribute[1]. We can use it to skip the non-system power supplies in the battery module and avoid adding HIDs or other peripheral devices to the total.
The logic is based on UPower, where it is assumed that "Unknown" devices or devices without a `scope` are system power supplies.
[1]: https://lore.kernel.org/lkml/alpine.LNX.2.00.1201031556460.24984@pobox.suse.cz/T/

fix(battery): ignore non-system power supplies

---

include/modules/clock.hpp
src/modules/battery.cpp
src/modules/clock.cpp
src/modules/mpd/mpd.cpp
src/modules/sndio.cpp

1. Let's do code simpler
2. Week format using regexp. Needs when user provide additional characters in format string and need to align week days according
3. Week format has got default formats: ":%U",":%V"
4. Week number is based on the first day of the week now. The output is the same as of date library now.
5. Avoiding of unnecessary operations
----

ISSUE#1877 Calendar week numbers

---

src/modules/hyprland/language.cpp

Hi, thanks a lot for the great project!
This PR fixes two problems in `hyprland/language` module on initialization:
* Sets the layout name when the `keyboard-name` option is not set by getting the first keyboard device from hyprland config
* Modifies the layout name according to the `format-<lang>` option (Fixes #1699)
Please let me know if something else is needed.

Fix hyprland language initialization issues

---

include/factory.hpp
include/modules/hyprland/submap.hpp
man/waybar-hyprland-language.5.scd
man/waybar-hyprland-submap.5.scd
meson.build
src/factory.cpp
src/modules/hyprland/submap.cpp

* Implemented `hyprland/submap` module (similar to *sway/mode*)
* Fixed `hyprland/language` module docs
Sorry about multiple changes in one go as I forgot to create branches on my fork. The latter is just some fixes for the docs of the language module

Implement hyprland submap module

---

.gitignore
src/modules/hyprland/language.cpp

Fixed an issue that resulted from incorrectly parsing the event string which contains extra commas coming from the keyboard variant.
Issues #1771 and #1901 should be fixed with this.

Fix wrong layout name in hyprland language module when a variant is used

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

for users who do not utilize any form of "workspace prev/next" commands, it can be very handle to sort the workspaces alphabetically.
this commit adds a new "alphabetical_sort" to the `sway/workspaces` module which allows the module to alway sort workspaces alphabetically.
this docs are updated to warn the user of the implications involved.
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>
I understand that this PR may not be welcome, since the comments in the code look like a good amount of effort was put into having Waybar *not* act like this. Feel free to push back and I'll just maintain this in my fork.

sway,feat: allow alphabetical sort

---

src/modules/cpu/common.cpp

cpu_load is pushed twice to the vector, introduced in: https://github.com/Alexays/Waybar/pull/1253
This MR removes the duplicated line so it's only pushes once per iteration.

fix: cpu_load pushed twice to the vector

---

src/modules/wlr/workspace_manager.cpp

This pull request fixes abnormal termination of waybar when using the wlr/workspace module and reconnecting a monitor.
Currently the behavior of disconnecting a monitor is the following: The workspace manager is destroyed immediately, but the compositor can send further messages. This results in GTK exiting with the following error message:
```
Gdk-Message: 16:01:27.831: Error reading events from display: Invalid argument
```
This pull request adds sending a stop request to instruct the compositor not to send any further messages. This is the same principle used in b79301a5bd.
Fixes #1783.

Fix GTK crash due to wlr/workspace module upon reconnecting monitor

---

src/modules/battery.cpp

time is reported in second and should be divided by 3600 and not 1000.
should fix: https://github.com/Alexays/Waybar/pull/1867#pullrequestreview-1246756355

fix: battery time remaining

---

include/modules/sway/window.hpp
man/waybar-sway-window.5.scd
src/modules/sway/window.cpp

A more sophisticated implementation for issue 1399, following the suggestions from https://github.com/Alexays/Waybar/issues/1399#issuecomment-1024913010
- Might break existing styles, but only if people relied on floating nodes being counted (introduced in commit 99723845976fb577a057b86e36b502c966bf254f -- so basically kinda breaks again what we fixed in that recent commit, but by using the new floating style, there should be a suitable workaround.)
- Provides classes empty, floating, tabbed, tiled, solo, stacked, and app_id. Some trace log output.
- Adds an "offscreen-css" bool option (default false), only effective when "all-outputs" is set. This provides styling according to windows on the given output when it's not focused, rather than showing the focused screens focused window and …

Sway window newstyles

---

include/modules/wireplumber.hpp
man/waybar.5.scd.in
src/modules/wireplumber.cpp

In order to fix the issue, the default node name is cached rather than the default node id. This is due to ids being unstable. So now when the object manager is installed (ie ready), the default node name is retrieved and stored for later.
Now when the mixer changed signal is emitted, the id of the changed node is used to get the node from the object manager. The nodes name is grabbed off that node and compared against the default node name, if they match the volume is updated. Some safeguarding has been added such that if the node cannot be found off the object manager, it's ignored.
Additionally, the "changed" signal on the default nodes api is now utilized to update the default node name if it has changed. This way if the default node changes, the module will be updated with the …

fix(wireplumber): waybar crashes when default node changes

---

src/modules/wlr/taskbar.cpp

Even though it makes little sense for this call to fail, it sometimes randomly does, and takes down waybar with it.
Fixes the crash from #1446, but does not bring icons back
As the issue occurs randomly, I plan on running this patch for a while to see if the issue goes away. I will mark the pull request as ready when confident the patch indeed works.

get_desktop_app_info: fix crash on failed DesktopAppInfo::create

---

src/modules/hyprland/submap.cpp

Without this, the module is rendered incorrectly on waybar startup, and will only be rendered when user triggers a submap (which is quite rare). I've noticed that some other modules also run `dp.emit()` in their constructor, presumably for the same purpose.

hyprland/submap: run initial render on startup

---

include/AModule.hpp
src/bar.cpp

The new image module (#1397) implements signal handling, which is useful for telling the bar the file has changed and should be redrawn. However, that doesn't work, since the ```refresh()``` method only gets called for custom modules.

Allow any module to implement signal handling

---

src/modules/custom.cpp

Just a small fix so that floating-point percentages get shown as rounded integers.

modules/custom: Added percentage rounding

---

src/modules/clock.cpp

Signed-off-by: Viktar Lukashonak <myxabeer@gmail.com>
During conversation in [PR#1956](https://github.com/Alexays/Waybar/pull/1956) it was registered a bug. Clock module lost format-alt option. This PR brings functionality back

Clock. Proper handletoggle propagation

---

include/modules/clock.hpp
src/modules/clock.cpp

Signed-off-by: Viktar Lukashonak <myxabeer@gmail.com>
Hi @Alexays , during [ISSUE#1321](https://github.com/Alexays/Waybar/issues/1321) investigation I've found one small minor bug. In order to avoid unmanaged string formatting in called functions... string formatting moved to the caller functionality + bug with the initial clock configuration (when weeks position are defined and weeks format not and vise versa) is fixed.

Clock. Formating simplify

---

include/modules/image.hpp
man/waybar-image.5.scd
src/factory.cpp
src/modules/image.cpp

The image module was a great contribution, I love having it in my bar. However, it didn't match the style of the rest of the repo and had a few issues that this PR addresses.
1. The current implementation does not properly attach CSS tags to itself. By running `env GTK_DEBUG=interactive waybar` one can see that the image module does not populate a name or attach any relevant style classes. This PR fixes that and brings it in parallel with styling of other waybar modules. You can now address it as `#image` in `styles.css`, and if you want duplicate modules you can define them as `image#img1`,`image#img2` and address them as `#image-img1`,`#image-img2`.
2. Documentation was not up to speed. The man page has been updated in this PR, and I'm adding the relevant wiki page as we speak.

Image module CSS fix

---

src/modules/hyprland/language.cpp

Second argument of substr is the length of the substring, _not_ the position. With positions, it's better to do like this.
Example:
```sh
[2023-01-29 13:08:00.927] [debug] hyprland IPC received activelayout>>ITE Tech. Inc. ITE Device(8910) Keyboard,Russian (with Ukrainian-Belorussian layout)
[2023-01-29 13:08:00.927] [debug] kbName is ITE Tech. Inc. ITE Device(8910) Keyboard,Russian (with
```
After the fix it's correct:
```sh
[2023-01-29 13:11:11.408] [debug] hyprland IPC received activelayout>>ITE Tech. Inc. ITE Device(8910) Keyboard,Russian (with Ukrainian-Belorussian layout)
[2023-01-29 13:11:11.408] [debug] kbName is ITE Tech. Inc. ITE Device(8910) Keyboard
```

Fix kbName initialization

---

src/modules/wireplumber.cpp

When freeing the `default_node_name_` pointer using `free`, the `&` operator was used to try to free the reference rather than the pointer. This caused a core dump. In order to fix this, the pointer is freed instead (ie the `&` operator is no longer used).
Fixes #1852

fix(wireplumber): free(): invalid pointer

---

src/modules/clock.cpp

Signed-off-by: Viktar Lukashonak <myxabeer@gmail.com>
Even user set hwclock to local he should define system timezone. This PR tries to get system timezone if no one is provided correct through Waybar configuration. Should fix https://github.com/Alexays/Waybar/issues/1988

When no one timezone is provided use system's TZ

---

src/main.cpp
src/modules/upower/upower_tooltip.cpp

To view the leak in the class build with
`meson -Dbuildtype=debug -Db_sanitize=address -Doptimization=g build`
And then run with
`ASAN_OPTIONS=detect_leaks=1 ./build/waybar --config=upower_config`
Let waybar run for a few minutes and then kill with CTRL-C
when the program is finished it will output a
```
=================================================================
==940640==ERROR: LeakSanitizer: detected memory leaks
```
which will have a section of
```
Direct leak of 9280 byte(s) in 116 object(s) allocated from:
#0 0x5a54c8 in operator new(unsigned long) ($HOME/Downloads/Waybar-0.9.17/build/waybar+0x5a54c8) (BuildId: 49a838544ce922121a44b057290a7f693645b7d6)
#1 0x7c9bfb in waybar::modules::upower::UPowerTooltip::updateTooltip(std::unordered_map<std::__cxx11::basic_string<char, …
```

Fixing memory leak on update UPower tooltip

---

src/modules/clock.cpp

Signed-off-by: Viktar Lukashonak <myxabeer@gmail.com>
Hi @Alexays ,
Again during [ISSUE#1321](https://github.com/Alexays/Waybar/issues/1321) is found minor penalty. Fix is pretty simple, for calendar header there was removed unnecessary string conversion. 
Thanks

Clock. Calendar. Avoid of unnecessary string transformation

---

include/modules/backlight.hpp
man/waybar-backlight.5.scd
src/modules/backlight.cpp

This adds the possibility of setting the brightness by scrolling up or down on the backlight module.
Code was adapted from the PulseAudio module, so the `reverse-scrolling` and `scroll-step` options were ported over.
Closes #1411.

Backlight: add brightness control

---

include/modules/image.hpp
man/waybar-image.5.scd
src/modules/image.cpp

I just made a small tweak in the image module to get the image path from an executable file. Here is a sample configuration.
```
"image/album-art": {
"exec":"~/.config/waybar/custom/spotify/album_art.sh",
"size": 32,
"interval": 5,  
},
```
If there is a path config exist, then it will load the image from the path config; otherwise, it will check for an exec configuration and execute the script, which should return a file path, and then it will load the image.
Here is a simple executable file
```
#!/bin/bash
album_art=$(playerctl -p spotify metadata mpris:artUrl)
if [[ -z $album_art ]] 
then
exit
fi
curl -s  "${album_art}" --output "/tmp/cover.jpeg"
echo "/tmp/cover.jpeg"
```

Set Image path from executable file (Image Module)

---

include/AModule.hpp
include/IModule.hpp
include/modules/clock.hpp
src/AModule.cpp
src/modules/clock.cpp

Hi @Alexays 
This PR is based on the https://github.com/Alexays/Waybar/issues/1977
The main idea - to stop of the code duplication in every modules when the module has to extend it's functionality via internal module member-functions.
So
1. IModule interface is extended by the doAction method
2. AModule has got it's own base doAction:  1. defines internal mapping between event name and module action name. 2. Calls override doAction.
3. Each module can provide it's own doAction which actually calls internal module functionality. Module action name is provided through function parameter
4. If Module overrides doAction and implements all necessary functionality via member-functions and has got internal mapping ... it could drop override handleToggle and handleScroll methods.
---
Es an …

ISSUE#1977. AModule implements module actions call

---

src/modules/sway/workspaces.cpp

From what I can see, it is currently not possible to individually and consistently style workspace buttons using css (unless all workspaces are visible at all times such that `:nth-child` can be used). This PR adds a css class to every workspace button using the workspace name. This the allows to use selectors such as `#workspaces button.workspace-2.focused`.
- The css classes are not sanitized, special symbols have to be escaped by the user. For example, if my workspace has the name `"@x$ f"`, the selector is `.workspace-\@x\$\ f`.
- The wiki would need to be updated.

feat(sway): add workspace css class

---

src/modules/sway/workspaces.cpp

This reverts commit a10464d9bb67ba75d3c9159bd027b67a565318e1.
Reverts https://github.com/Alexays/Waybar/pull/2017
Well this is awkward. Turns out there was already an `id` called `sway-workspace-{name}`. My changes were not necessary. Sorry about that.

Revert "feat(sway): add workspace css class"

---

src/modules/clock.cpp

Hi @Alexays , this PR should (but not sure 😄  ) solve #878 . At least there's a potential issue: 
1. User defines timezones as an array
2. User defines timezone as a single value
In both cases there no any check to ensure timezone can be initialize properly. 
This PR does:
1. TZ initialization is wrapped into try catch. If there is an exception waybar prints it as a warning,
2. If array of necessary timezones is empty waybar tries to use default system timezone

Clock tz try catch

---

include/group.hpp
man/waybar.5.scd.in
src/bar.cpp
src/group.cpp

currently, the orientation of group modules is always the opposite of the bar. Change it so that:
* the default orientation of the group module is always the opposite of its parent, even for nested groups
* the orientation can be overridden in the config
* css ID and class are set for the group element
Motivation:
I would like to set styling for sets of modules so that they are visually grouped. Some of this can be simulated by enumerating style settings for each module, but many things are not possible when all the modules' elements are siblings of each other 
The module group functionality is a bit is a bit inflexible and only really viable for a specific use case. This hopefully makes it more generally useful

group module: configurable orientation

---

src/modules/wireplumber.cpp

The `default_node_name_` is reassigned without calling `g_free` on the old string.
Fixes #2041

Wireplumber: Free the default node name

---

src/modules/custom.cpp

This fixes a memory leak I've been experiencing for quite some time.

custom module: free memory returned by libc's getline

---

src/modules/clock.cpp

**Reproducer:** set the date to 31 March 2023, try scrolling the calendar (`"on-scroll-up": "shift_down"`, ...)
**Expected:** All months
**Actual:** Months with 31 days only
Debug print shows `2023-02-31 is not a valid year_month_day`
In this MR I set day to 1 if shit is not zero to fix this.

modules/clock: fix calendar shift in months with 31 days

---

include/modules/wlr/taskbar.hpp
man/waybar-wlr-taskbar.5.scd
src/modules/wlr/taskbar.cpp

some users (maybe only myself) may want to sort the task bar by app_id which then places occurrences of the same task next to each other.
there is an alternative method to do this, making TaskBar's `tasks_` vector public, and having each Task find itself in `tbar_->tasks_` and setting their button in the right place, but it "feels" better to have TaskBar decide to place where its Task(s) should be within itself. 
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>

wlr-taskbar: allow sorting by app_id

---

include/modules/hyprland/language.hpp
man/waybar-hyprland-language.5.scd
src/modules/hyprland/language.cpp

This adds codes like {short} {variant} etc.  It uses the same codes as the ones for sway/language, I didn't bother adding the flags. Existing configs should still work fine.
I don't know C++ so please tell me if this is terrible.

[hyprland/language] Add more format replacements.

---

src/modules/mpris/mpris.cpp

apply styles to label rather than event_box (fixes play/pause state and per-player selectors)
closes #2087

mpris: fix css class application

---

src/modules/pulseaudio.cpp

fixes #2094
Test case:
```json
"tooltip": false,
"states": {
"full": 100,
"mid": 99,
"off": 0
},
"max-volume": 110,
"format":       "OVER {format_source} V {volume}%   ",
"format-full":  "{format_source}   ",
"format-mid":   "{format_source} V {volume}%   ",
"format-off":   "OFF {format_source}   ",
```
OVER shown over 100%, no volume at full, volume below 100%, OFF at 0%

#2094 pulseaudio apply states

---

include/modules/wlr/workspace_manager.hpp
src/modules/wlr/workspace_manager.cpp

Closes #1629, where multiple users have confirmed it's working
Config works identical to persistent workspaces in [sway/workspaces]
It had issues when used with the "all-outputs" option. I've made it so the two options can't be used together.

Persistent workspaces for [wlr/workspaces]

---

src/modules/hyprland/backend.cpp

Small fix for https://build.opensuse.org/build/X11:Wayland/openSUSE_Tumbleweed/x86_64/waybar/_log. This complies with openSUSE's packaging guidelines.
Reference: https://en.opensuse.org/openSUSE:Packaging_checks#binary-or-shlib-calls-gethostbyname

fix: use getaddrinfo() instead of gethostbyname()

---

src/modules/hyprland/backend.cpp

The return value check of `getaddrinfo` call was incorrect since it returns `0` on success as mentioned here: https://www.man7.org/linux/man-pages/man3/getaddrinfo.3.html#RETURN_VALUE. This fixes the initialization problem of Hyprland language module.
Also, I removed caching the result into the variable `SERVER` since it's not used anywhere down below.

Fix hyprland language initialization problem

---

Dockerfiles/gentoo
meson.build
src/modules/network.cpp
subprojects/cava.wrap

Hi @Alexays , 
Arch users noticed cava fork compiles both and library and application. So once waybar is installed it overrides existing cava application what is not they want. So in the libcava fork I refreshed building logic and by default provide libcava as a single library. In addition new  libcava release now provides pkg-config manifest. So waybar can use dependency meson method now.
This PR should solve [Arch, ...] users complaining about cava module with the error:  shared library is not found
Relates: #2133, #2130, #2129

cava: shared library is not found

---

include/modules/wlr/workspace_manager.hpp
src/modules/wlr/workspace_manager.cpp

Persistent workspaces without any windows now get their own CSS class

[wlr/workspaces] Separate CSS class for empty persistent workspaces

---

src/modules/wlr/workspace_manager.cpp

This PR introduces the "persistent" format-icon to the wlr/workspaces module, changing the icon of empty persistent workspaces
Fixes #2155

Add persistent format-icon to wlr/workspaces

---

src/modules/mpris/mpris.cpp

This hides the MPRIS module if there's no content. This has already been done for some other modules in #1860.

mpris: Hide label if empty

---

man/waybar-mpris.5.scd

Just noticed that these names are wrong in the man page.

mpris: Fix incorrect format replacement names

---

include/util/command.hpp
src/modules/network.cpp

- Pipes opened to run commands did not have the close-on-exec flag set, creating a brief window where a long-running process spawned by another thread might inherit the write end of the pipe. This would cause whatever was trying to read from the process to hang; in particular this could lead to certain custom modules not appearing properly under certain configurations. Fix this by using `pipe2` with the `O_CLOEXEC` flag (supported on Linux and all the BSDs) to atomically set the close-on-exec flag at startup.
- Set the close-on-exec flag on the eventfd created by the network module. (Allowing children to inherit this file descriptor is less problematic than it is for the pipes, but still best avoided.)
- If `fork()` fails, close both ends of the pipe (previously they would be leaked).

File descriptor handling bugs

---

src/modules/battery.cpp

In waybar::modules::Battery::~Battery(), store a copy of the batteries_ iterator before calling erase(), as erase() invalidates the iterator.
Prior to this change, disconnecting outputs resulted in a SEGFAULT when using the battery module; e.g.,
[debug] Received SIGCHLD in signalThread
[debug] Cmd exited with code 0
[debug] Received SIGCHLD in signalThread
[debug] Cmd exited with code 0
[debug] Received SIGCHLD in signalThread
[debug] Cmd exited with code 0
[debug] Output removed: AU Optronics 0x2336
[info] Bar configured (width: 1280, height: 25) for output: eDP-1
[info] Bar configured (width: 1280, height: 25) for output: eDP-1
zsh: segmentation fault (core dumped)  ./build/waybar -l trace

Fix SEGFAULT in battery module

---

src/modules/dwl/tags.cpp

Fixes an issue that occurs after starting Waybar with the `dwl/tags` module.
Error:
`[0000-00-00 00:00:00.000] [error] dwl_status_manager_v2 not advertised`

fix(dwl-module): fix typo to avoid null pointer

---

src/modules/river/window.cpp

The wiki mentions the river/window module has a tooltip, but it does not. This merge adds a tooltip with the same content as the label itself.

river/window: Add tooltip.

---

include/modules/sway/ipc/client.hpp

Fixing errors during the building due to missing library after latest GCC updates.
This PR will fix the following issues: https://github.com/Alexays/Waybar/issues/2159 https://github.com/Alexays/Waybar/issues/2177

Fixing 'incomplete type error' during building

---

src/modules/hyprland/window.cpp

Adds an `empty` css class when window name is empty.
Select with `#window.empty`.
Related #2186, #1995, #1934
- Assumes `windowName` is not null.
- Matches window with an empty name.

[hyprland/window] Add css class for empty window name

---

src/modules/sni/host.cpp
src/modules/sni/watcher.cpp

When Waybar exit in the log I see:
`(waybar:25493): GLib-GIO-WARNING **: 22:57:40.825: Invalid id 2 passed to g_bus_unwatch_name()`
Investigation shows: Tray module constructor calls :
1. watcher constructor
2. host constructor
In the same time both base classes(watcher and host) keeps information about cross resources. Watcher instance has got information about host and watcher either. The same for host class..
So when time to destruct instances, both watcher and host are trying to destroy cross resources. In such case : watcher may kill host resource earlier then host destruction is called and vise versa for host class.
This PR splits resource destruction between base classes. Host now destruct only host objects, watcher - watchers objects.
Actually I didn't find any other dependencies …

Tray module causes: Invalid id passed to g_bus_unwatch_name()

---

src/modules/wlr/workspace_manager.cpp

Just to turn off annoying C++20 compiler about [../src/modules/wlr/workspace_manager.cpp:67:10: warning: implicit capture of 'this' via '[=]' is deprecated in C++20 [-Wdeprecated]](https://github.com/LukashonakV/Waybar/actions/runs/5192869066/jobs/9362634710#step:5:160)

deprecated: implicit capture of 'this' via '[=]'

---

man/waybar-pulseaudio.5.scd
src/AModule.cpp
src/modules/backlight.cpp
src/modules/pulseaudio.cpp

The option is generally useful when scrolling is used, when configuring
input devices to use "natural scroll direction".
Both backlight and pulseaudio were using different implementations, this
unifies and documents them.
Signed-off-by: Robert Günzler <r@gnzler.io>

Lift reverse-scrolling option into AModule

---

src/modules/sway/window.cpp

Should fix #2227.
Probably a rebase error during development of #1419. The code block now removed was not supposed to be there anymore.
It also slipped from the `elseif (app_nb==1)` branch into the `else` (more than 1 node) branch and erroneously set app_id style and `old_app_id_=app_id_`.

sway/window: fix appid style not cleared

---

man/waybar-clock.5.scd
src/modules/clock.cpp

Hi @Alexays  this PR
1. Fixes the #2204 . When user specify "" either `timezone` or `timezones` option clock module now uses local timezone.
2. I refreshed waybar-clock man page and synced it with Wiki

Issue#2204

---

include/modules/upower/upower.hpp
man/waybar-upower.5.scd
src/modules/upower/upower.cpp

Hi @Alexays , this PR covers #1979 
I extended UPower filter:
> Every Device which is handled by Upower and which is not
> UP_DEVICE_KIND_UNKNOWN (0) or UP_DEVICE_KIND_LINE_POWER (1) is a Battery
So user now is able to `upower --dump`
Check the output:
```xml
Device: /org/freedesktop/UPower/devices/keyboard_dev_D4_AE_41_38_D0_EF
native-path:          /org/bluez/hci0/dev_D4_AE_41_38_D0_EF
model:                Xiaomi Smart Band 7 D0EF
serial:               D4:AE:41:38:D0:EF
power supply:         no
updated:              Fri 09 Jun 2023 03:38:17 PM +03 (2750 seconds ago)
has history:          yes
has statistics:       no
keyboard
present:             yes
rechargeable:        no
state:               unknown
warning-level:       none
percentage:          76%
icon-name: …
```

Upower native-path filter

---

src/modules/hyprland/backend.cpp

Basically I was testing #2245 and noticed that Waybar would randomly crash when there are too many windows in a workspace. Turns out the current IPC implementation only reads 8192 bytes of response and discards the rest. This PR is a quick fix.

More robust Hyprland backend

---

include/modules/hyprland/window.hpp
src/modules/hyprland/language.cpp
src/modules/hyprland/window.cpp

This PR reworks the `hyprland/window` module a bit, to allow the following CSS classes:
- `window#waybar.empty` When no windows are in the active workspace (or monitor's workspace if `separate-outputs` is enabled)
- `window#waybar.solo` When one tiled window is in the workspace
- `window#waybar.<app_id>` Where `<app_id>` is the class name (e.g. `chromium`) of the only window in the workspace
These are similar to the Sway module, except without the layout modes, because Hyprland's layout modes are different (and afaik it doesn't expose them to IPC anyway)
The "rework" was done because Hyprland IPC doesn't have one clear event for when the amount of windows on a workspace changes, so we just listen to `activewindow`, `closewindow` and `movewindow` and query the current workspace every time. …

hyprland/window: Add CSS customization similar to sway/window

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

Wanted to have the output displayed in the workspace switcher, this is just a simple one-line edit to achieve that.

Add output port (display) of workspace to template function of sway/workspace

---

src/modules/network.cpp
src/util/rfkill.cpp

While compiling Waybar, I had these warnings:
```
In file included from ../src/modules/network.cpp:1:
../include/modules/network.hpp: In constructor ‘waybar::modules::Network::Network(const std::string&, const Json::Value&)’:
../include/modules/network.hpp:87:16: warning: ‘waybar::modules::Network::rfkill_’ will be initialized after [-Wreorder]
87 |   util::Rfkill rfkill_;
|                ^~~~~~~
../include/modules/network.hpp:81:9: warning:   ‘float waybar::modules::Network::frequency_’ [-Wreorder]
81 |   float frequency_;
|         ^~~~~~~~~~
../src/modules/network.cpp:80:1: warning:   when initialized here [-Wreorder]
80 | waybar::modules::Network::Network(const std::string &id, const Json::Value &config)
| ^~~~~~
[141/150] Compiling C++ object waybar.p/src_util_rfkill.cpp.o …
```

Fixed some build warnings

---

include/factory.hpp
include/modules/hyprland/backend.hpp
include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
man/waybar-wlr-workspaces.5.scd
meson.build
src/factory.cpp
src/modules/hyprland/backend.cpp
src/modules/hyprland/workspaces.cpp

Resolves: https://github.com/Alexays/Waybar/issues/2194
Just basic functionality for now: show with id and/or icon witch active class.
In next PR I plan to merge some wlr/workspaces features: urgent class, active only workspace, different sorting options. Maybe also all-output and  persistent options (but I can not test it on multiple outputs by myself, so it'll require some help with testing)
test config:
```json
"modules-left": [ "hyprland/workspaces" ],
"hyprland/workspaces": {
"format": "{id}: {icon}",
"format-icons": {
"1": "",
"2": "",
"3": "",
"4": "",
"default": ""
}
}
```

feat: hyprland/workspaces

---

Dockerfiles/gentoo

Dear @Alexays this PR renews CI Gentoo docker container. 
Can you also retake Gentoo Docker image I've build on docker hub . I refreshed image and added necessary dependencies are need to build Waybar with cava functionality. 
Image can be taken here [waybar:gento](https://hub.docker.com/layers/vilu1209/waybar/gentoo/images/sha256-ba92ef4de4bac2aae1bae24f78fe5a6599680a02694cdbd4b79885931e292edd?context=repo)

Refresh Gentoo docker

---

include/util/prepare_for_sleep.h
include/util/sleeper_thread.hpp
meson.build
src/util/prepare_for_sleep.cpp

std::condition_variable::wait_for does not count time spent in sleep mode, resulting in longer than expected waits.

Wake all sleeping threads when leaving suspend

---

src/AModule.cpp

This is a fix for #1140.
Currently reverse-scrolling is applied globally. This can be annoying for those who use both a mouse and touchpad with "natural scrolling". In the case of scrolling to adjust volume, brightness, etc, scrolling up on a touchpad feels "natural" to adjust those things up.
However, this is the opposite of what "natural scrolling" does because it was designed for scrolling documents, which _does_ feel natural to reverse up/down.
So what this means for Waybar is that if we leave reverse-scrolling = false, the mouse wheel feels natural, but the touchpad feels backwards. If we set reverse-scrolling = true, the touchpad feels natural, but the mouse wheel feels backwards.
This PR does two things to address this issue:
- Fixes a regression introduced in #2232 that prevents …

Don't apply reverse scrolling to mice wheels

---

include/modules/wireplumber.hpp
man/waybar-pulseaudio.5.scd
man/waybar-wireplumber.5.scd
src/modules/wireplumber.cpp

This adds the ability to scroll the WirePlumber widget like the PulseAudio one.
- Default scroll action is to change the volume using WirePlumber's mixer API.
- max-volume and scroll-step values can be used to configure how volume adjustments works
- ~The default scroll-step is provided by the mixer API~
- Customizable scroll actions

wireplumber: Support for scrolling

---

include/util/gtk_icon.hpp
meson.build
src/modules/gamemode.cpp
src/modules/sni/item.cpp
src/modules/sway/window.cpp
src/modules/upower/upower.cpp
src/modules/upower/upower_tooltip.cpp
src/util/gtk_icon.cpp

The segfaults were happening on GTK icon theme functions, which are called via the C++ interface functions such as Gtk::IconTheme::has_icon.
There are multiple modules and threads using this functions on the default icon theme by calling Gtk::IconTheme::get_default(), which returns the same object for all callers, and was causing concurrent access to the same internal data structures on the GTK lib. Even a seemingly read-only function such as has_icon can cause writes due to the internal icon cache being updated.
To avoid this issues, a program wide global mutex must be used to ensure a single thread is accessing the default icon theme instance.
This commit implements wrappers for the existing IconTheme function calls, ensuring the global lock is held while calling the underling GTK …

Fix random segfault on GTK icon functions

---

include/modules/mpris/mpris.hpp
src/modules/mpris/mpris.cpp

I noticed that while MPRIS module is running and music is playing, all tooltips on other modules stop working.  When music is paused or stopped, they work again.
Upon investigation, MPRIS onPlayerMetadata(), onPlayerPlay() callbacks get triggered every ~20ms and call Mpris::update() without regard for update interval configured.  The Mpris label gets updated every time and interferes with showing tooltips for other modules.
The fix is to ignore any Mpris::update() calls until the configured update interval elapses from the previous non-ignored call.

Stop MPRIS module from updating every ~20ms

---

man/waybar-wlr-taskbar.5.scd
src/modules/wlr/taskbar.cpp

Hello,
I'm using the _wlr/taskbar_ and I was annoyed by some long application names like "Firefox Web Browser". I would prefer to just read "Firefox", so the button doesn't take so much space. 
I simply implemented the rewrite logic from sway/window and _hyprland/window_ for _wlr/taskbar_. A simple `waybar::util::rewriteString` was added and the man page was updated.
**Here is an example:**
The top waybar is using the rewrite rules. The bottom waybar is the old version with the full names.
You see, that the taskbar is way shorter by removing unnecessary parts from the application name.
```
"wlr/taskbar": {
"format": "{icon} {name}",
"icon-size": 20,
"tooltip": false,
"on-click": "activate",
"on-click-middle": "close",
"on-click-right": "minimize-raise",
"rewrite": {
"(\\s*)Firefox Web …
```

wlr/taskbar: add support for rewrite rules

---

src/bar.cpp

Add a new `start_hidden` flag to set visibility on launch.
I'm using `"mode": "hide"` on Hyprland.
To make the bar hide on launch, I currently have to do `waybar & sleep 1 && killall -SIGUSR1 waybar` to hide waybar on launch.  (I think the sleep is required because it takes a little under a second for the signal handling thread to become available.)
With this change, I can add this to my waybar config and have it hide on launch:
```json    
"mode": "hide",
"start_hidden": true,
```

Add a new start_hidden flag

---

default.nix
flake.lock
flake.nix
nix/default.nix

Reason for overriding instead of keeping the full default.nix in-tree: for example, the update from 0.9.16 to 0.9.17 broke this flake because of the changed dependencies/build options, after this change the derivation will be the same as the nixpkgs one (provided the user sets `inputs.waybar.inputs.nixpkgs.follows = "nixpkgs"`). This is the better option since the flake is unmaintained in this repo (although it may still break between releases). If someone decides to start maintaining it, this can be easily reverted.
And the dev shell now allows traditional `make` workflow, as well as clangd integration, allowing nix users to easily setup a dev environment.

improve nix dev shell; override the nixpkgs waybar

---

man/waybar-sway-workspaces.5.scd
resources/config
src/modules/sway/workspaces.cpp

This adds an option, it defaults to true which is the old behavior, when switching workspaces in the sway plugin using the mouse wheel, it uses sway ipc calls to disable mouse warp, and enable it again. 
When using the mouse to switch workspaces I don't want my mouse to move programmatically.
1. I haven't found a way to read the in memory currently active setting for mouse warp, to only do this if mouse warp ins enabled currently. I don't know if it is possible via sway ipc. I don't think reading the setting file is the way to go, as you can edit settings in situ using ipc calls. The effect this has is that if this setting is set away from the default in waybar it will enable mouse warp ephemerally if you use the mouse scroll wheel to switch workspaces. I don't know if this is a big …

sway/workspaces: setting to not warp to window when scrolling

---

include/modules/mpris/mpris.hpp
man/waybar-mpris.5.scd
src/modules/mpris/mpris.cpp

This PR makes it possible:
- the choice of tag orders in dynamic mode;
- the choice of the separator;
- the non-inclusion of the tag if not declared in "dynamic-order".
It is observed that "dynamic-priority" was renamed to "dynamic-importance-order" to be more intuitive and not confused with "dynamic-order".

mpris: dynamic tag ordering and separator customization

---

src/modules/sni/host.cpp
src/modules/sni/watcher.cpp

After upgrading to the latest release of Waybar the bar will crash whenever I close the laptop lid. After some debugging I believe it is because the watching added by `watch_name` in `Host` is not being correctly canceled using `unwatch_name`. After the Tray object and Host object are destroyed, additional callbacks will become use-after-free.
Apparently commit 3af1853260dafc43c992fc2357a3f3bace3bccaa removed the `unwatch_name`. I'm not sure why it did that, but it seems dangerous.
Additionally, bus_name_id_ is created by own_name. According to that function's documentation, the correct inverse operation is unown_name.

Partially revert 3af1853260 to fix use-after-free

---

include/modules/hyprland/window.hpp
man/waybar-hyprland-window.5.scd
man/waybar-sway-window.5.scd
src/modules/hyprland/window.cpp

* The `.solo` and `.<app_id>` classes now account for `hidden` (aka swallowed) windows, and also fullscreen windows in `"fullscreenMode": 1` (where a window is fullscreen but the bar is visible).
* Add `.hidden` CSS class for when a hidden/swallowed window is present on the workspace.

hyprland/window: Add .hidden CSS class, account for hidden & fullscreen windows

---

src/util/prepare_for_sleep.cpp

- (e)logind isn't supported on non-Linux
- system bus usage is limited to (e)logind, bluez, upower
- many modules don't use dbus at all

Unbreak modules without DBus

---

src/modules/hyprland/window.cpp

It was trying to find a workspace from the wrong array. The array of workspaces is there but it was not used.
Closes #2285

hyprland/window: Fix no info with separate-outputs=true

---

src/modules/sway/workspaces.cpp

Sorry about that, @q234rty correctly pointed out that my previous already merged pull request for a new feature did not default to the old behavior. 
While I don't understand why anyone wouldn't use this feature if they already are using mouse_warp, since I can't read out the current status of the mouse_warp option, having this default to being enable disturbs people who don't use mouse_warp also, which I totally see is a preferential subject. So until there is a way to read the current status of mouse_warp, this has to default to the old behavior.

fix, default to true, sway/workspaces: warp-on-scroll

---

src/modules/clock.cpp

Add `nullptr` to the timezones vector, so that the current timezone is fetched on each `update()`, and changes to it (e.g. with `timedatectl set-timezone`) are propagated.

clock: handle timezone changes (again)

---

Dockerfiles/archlinux

Hi @Alexays , I've rebuilt arch docker image. Can you retake it [vilu1209/waybar:archlinux](https://hub.docker.com/layers/vilu1209/waybar/archlinux/images/sha256-1492530202dbc7352fa866b079616b25d7ae3c8ce9e23e5e8ab00db13f2de704?context=repo)
This PR is raised in order to prevent any further questions about cava from arch community about build failures. As for example: #2281

Arch CI cava

---

include/modules/hyprland/window.hpp
man/waybar-hyprland-window.5.scd
src/modules/hyprland/window.cpp

This exposes more data as format arguments in the `hyprland/window` module. Most importantly you can now use `"{initialTitle}"` which often shows a nice String describing the program, other than the current state of the program (i.e. for a Firefox window it is "Mozilla Firefox" not "Comparing Alexays:master...Mr-Pine:hyprland-window-data · Alexays/Waybar — Mozilla Firefox")
Fixes #2289

`hyprland/window` expose more data

---

include/AAppIconLabel.hpp
include/modules/hyprland/window.hpp
include/modules/sway/window.hpp
meson.build
src/AAppIconLabel.cpp
src/modules/hyprland/window.cpp
src/modules/sway/window.cpp

This PR introduces App Icons for the `hyprland/window` module (as requested in #1925)
Since this required almost no changes from the code for `sway/window` and I didn't want to duplicate the code, I introduces a new `AAppIconLabel` class which now both `hyprland/window` and `sway/window` inherit from. The sway implementation uses `app_class` if `app_id` is not set (appears to be the case if the window is running under xwayland) but I wasn't really able to find a suitable replacement for that with hyprland (`app_id` seems to correspond to hyprlands `class` though). 
Tested on both hyprland and sway

App Icons for `hyprland/window`

---

include/modules/hyprland/window.hpp
man/waybar-hyprland-window.5.scd
src/modules/hyprland/window.cpp

Sorry, I know I submitted #2307 just half an hour ago, but I changed my mind. Rather than renaming `.hidden` to some other class name, I have renamed it to `.swallowing`. After some more discussion in the comments to https://github.com/Alexays/Waybar/commit/cdece498c1e3849ea6e8ff7795ddce1ca8265803#commitcomment-121410267 I realized that instead of excluding so many edge cases for it, it's easier to check specifically for window swallowing, as that's the only use case that makes sense and is not covered by other means.

hyprland/window: rename .hidden to .swallowing (and fix grouped windows)

---

src/modules/backlight.cpp

fix #2311 
this removes the `std::to_string` conversions from `percent` in the `backlight.cpp` when passing to `fmt::format`. i don't think this should break anything, as `percent` is defined as a `uint8_t`.
i aḿ not exactly certain why this was added in the first place, as this was originally added in 331b28393aa65354e8a7bdff5a35a61f8d2479cc and has been unchanged since, and i can not see any specific reason given in either the commit or the corresponding pr.

backlight: do not convert percent to string in fmt

---

src/modules/hyprland/backend.cpp

`getSocket1Reply` can get an incomplete response. When `getSocket1JsonReply` parses this response with the JSON parser, it throws the runtime error.
The socket read ends early when it doesn't completely fill the socket buffer when it has more data. The socket read now stops when the socket returns nothing instead of stopping when it has returned less than the size of the buffer.
Closes #2313

hyprland/backend: Fix JSON parser runtime error

---

src/modules/hyprland/language.cpp

This improves hyprland/language module, so you can specify keyboard variant for formatting.
So you are able to have multiple keyboard variants of same language and differentiate between them, for example, you can define "format-cs-qwerty" and "format-cs-coder".

hyprland/language: Differentiating keyboard layout variants

---

src/modules/sway/window.cpp

This patch tries to make `app_id` specific styling from `sway/window` more useful if the `smart_borders` and `smart_gaps` Sway options are used in conjunction with the `offscreen-css` option of the module.
My main use case for this is styles like `window#waybar.solo.kitty`, which can make Waybar blend in with the solo window on the workspace (gapless and borderless thanks to the Sway options). For example, you may set a semi-transparent background for Waybar only if a terminal with semi-transparent background is the only window on the workspace, but use a fully opaque background for any other (opaque) window.
Unfortunately, `app_id`-specific styling is not very useful with multiple monitors. Even if `offscreen-css` is enabled, the CSS class corresponding to `app_id` is only applied for …

sway/window: app_id on unfocused workspaces

---

resources/custom_modules/mediaplayer.py
src/modules/backlight.cpp

* Uses a class to manage the players (PlayerManager)
* Automatically shows the most important player:
* show the currently playing player
* or else show the first paused player
* or else show nothing
* => If the current active player is closed, the next player in the list (sorted by most recent) will be shown instead.

Mediaplayer improvements

---

include/modules/clock.hpp
src/modules/clock.cpp

Hi @Alexays , this PR should fix 
1. #2331
2. probably (#2254) .  This need to check and ask for issue author to provide conclusion
The problem was here: when calendar used to print information through fmt::format it used sys_days function which doesn't care about timezones and calculates date time in UTC. 
For now: the whole clock is moved to zoned logic. Even user doesn't configure his local timezone, system time zone will be used to provide info about date, time, calendar.  When user configures array of timezones and switches between each other calendar will also been recalculated with applying of the picked timezone.

time conversion between time zones

---

src/modules/clock.cpp

Hi @Alexays . While previous commits, I lost the part of code which was truncating of the system time to seconds. So ... Even precision now is more higher ... users complains about it. So this commit solves #2344

Clock. Narrow seconds precision

---

man/waybar-hyprland-window.5.scd
src/modules/hyprland/window.cpp

Fix for #2343 
Adds an emit call to the dispatcher. This is basically what the sway version does, too (not directly but via an ipc call)
As a bonus this documents the icon options for `hyprland/window`

`hyprland/window` start behavior fix

---

src/modules/clock.cpp

Hi @Alexays ,
This PR fixes #2356

tooltip-format spaces breaks pango format

---

man/waybar-cava.5.scd
man/waybar-clock.5.scd
man/waybar-hyprland-workspaces.5.scd
man/waybar-states.5.scd
man/waybar-wlr-taskbar.5.scd

This PR consists of the following 2 changes/commits:
man/waybar-clock: Fix typo and formatting
typo: Adressed -> Addressed
formatting: Add missing spaces
man: Make NAME-ing consistent
Tools like `apropos` and `whatis` use the NAME section to generate their
database, so make sure every manpage has it.
Also make sure they all have a brief description and make it consistent
across the manpages.

Manpage fixes

---

src/modules/sway/ipc/client.cpp

I havent' tested this because I don't use sway, but it's a pretty small change.
Fixes these warnings:
```
[103/154] Compiling C++ object waybar.p/src_modules_sway_ipc_client.cpp.o
../waybar-hyprland-git/src/modules/sway/ipc/client.cpp: In destructor ‘waybar::modules::sway::Ipc::~Ipc()’:
../waybar-hyprland-git/src/modules/sway/ipc/client.cpp:20:10: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
20 |     write(fd_, "close-sway-ipc", 14);
|     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../waybar-hyprland-git/src/modules/sway/ipc/client.cpp:25:10: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
25 |     write(fd_event_, …
```

Fixed sway IPC compile warnings

---

include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp

Adds `persistent_workspaces` to the hyprland/workspaces module, based on the implementation from wlr/workspaces.
Apart from what's possible with wlr/workspaces (specifying an array of monitors a workspace should be shown on), you can also specify a fixed number of workspaces each monitor should have, like this:
```jsonc
"persistent_workspaces": {
"*": 3,    // 3 workspaces by default
"DP-1": 5 // but DP-1 gets 5 workspaces
}
```
CC: @MonstrousOgre @Anakael @MightyPlaza

Persistent workspaces in hyprland/workspaces

---

src/modules/hyprland/workspaces.cpp

PR #2341 resulted in my workspaces not showing up. It seems this is a result of a couple minor logical mistakes (due to switching from `find` to `starts_with`), along with `id` not being formatted in, which was throwing an "argument not found" exception. I don't know the reasoning behind not formatting `id`, if anyone knows why, let me know.

Fix logical errors, formatting error

---

src/modules/hyprland/workspaces.cpp

Changes default workspace format to `{name}` to address the issue described in #2373.

Change default workspace format

---

man/waybar-hyprland-workspaces.5.scd

The wiki was updated but I forgot to update the man-page.

Updated hyprland-workspaces manpage

---

include/AModule.hpp
src/AModule.cpp

Allow `on-click-release` actions for most buttons, this will execute the action when the button is **released**.  
This is a workaround for #1968 (I believe the bug is caused by an unexpected focus loss while holding the button)  
> at least, it works for me.
By doing `"on-click-release": "swaync-client -t -sw",` I could fix the wrong location click bug without a sleep longer than the click.
And  I think, on-release will have other uses too!

Button release action

---

README.md

As mentioned in #2200 the Arch repository name was renamed from `community` to `extra` ([official announcement](https://archlinux.org/news/git-migration-announcement/)). The URL was fixed, but not the text.

docs: fix Arch repository name

---

include/util/format.hpp
src/modules/sni/item.cpp

don't rely on implicit conversion which is no longer present in fmt 10.1.0
Fixes #2403

Explicitly cast ustring to string when passing to fmt

---

src/modules/wlr/taskbar.cpp

fix: typo in taskbar.cpp

---

include/modules/bluetooth.hpp
man/waybar-bluetooth.5.scd
src/modules/bluetooth.cpp

Fixes #2163
This PR contains the following changes:
1. Adds the `format-no-controller` and `tooltip-format-no-controller` format strings that will be used if no bluetooth controller could be found.
2. Fixes the bluetooth module still being visible if the format string is empty.
The reason for why the bluetooth module was still being displayed is the return statement in the constructor of the bluetooth module:
https://github.com/Alexays/Waybar/blob/aecd80702e746e7cb9a78c70d0578a88547341b1/src/modules/bluetooth.cpp#L95-L106
This return statement caused `dp.emit()` not to be called and somehow this removed the ability for the module to hide.
I also think that it makes sense to have an additional format string for the case when the system does not have a bluetooth controller. If the user …

Add format-no-controller to bluetooth module and fix it still being visible if the format string is empty

---

flake.lock
flake.nix
include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspaces.cpp

Adding urgent class support to the hyprland workspaces module.
- Subscribe to urgent IPC
- Set is_urgent on workspace that is in the payload from the IPC call.
- Clear is_urgent when you activate a workspace that has is_urgent set.
related issue: https://github.com/Alexays/Waybar/issues/2271

Hyprland urgent class support

---

src/modules/hyprland/workspaces.cpp

This would make the behavior consistent with sway/workspaces and wlr/workspaces. A config like this:
```json
"hyprland/workspaces": {
"disable-scroll": true,
"active-only": false,
"all-outputs": false,
"on-click": "activate",
"sort-by-number": true,
"persistent_workspaces": {
"1": [],
"2": [],
"3": [],
"4": [],
"5": []
}
}
```
Would show workspaces 1 - 5 on all outputs.

Show workspaces on all outputs if persistent_workspaces value is empty

---

include/AModule.hpp
src/AModule.cpp

Attempt to properly add button release events
#2399 (but I hope without bugs)  
I've created a new function in AModule to handle release events without invoking handleToggle methods (what is not prepared to handle release events)  
Also, I've moved the user input handling to a private function (simply to avoid code duplication).  
> I've no access to my workstation, I couldn't test this PR. Please verify it before merging.

Release button event second attempt

---

man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspaces.cpp

Per discussion https://github.com/Alexays/Waybar/issues/2271#issuecomment-1692402703 with @zjeffer  about adding a new config style. You provide the monitors as keys and either an integer for generating that many workspaces or an array of workspaces to create on that monitor.

hyprland persistent workspace support new config declaration

---

include/bar.hpp
include/modules/sni/item.hpp
src/bar.cpp
src/modules/sni/item.cpp

Fixes passing relative coordinates to `ContextMenu`, `Activate`, `SecondaryActivate` DBus methods, while handling mouse click events. Resolves #2165.

sni: fix passing relative coordinates to dbus methods

---

src/modules/battery.cpp

A few days ago, I opened issue #2126 requesting this feature. I had some free time recently and decided to try making a pull request. I determined that weighted average of percentages with capacities as weights was a little complex, and that a better way to calculate the percentage that I wanted would be to just compute total_energy * 100 / total_energy_full. No change is required for the condition where the user sets design-capacity to true, as that is already total_energy * 100 / total_energy_full_design.
Right now, the option to enable this is called weighted-average. Is that an appropriate name, or should I call it something else?
Additionally, I discovered that it total_capacity is not greater than zero, Waybar already falls back to doing this calculation. (And still would, even if …

Display battery percentage as weighted average of battery levels

---

src/modules/hyprland/workspaces.cpp

Fix segfault when attempting to set_urgent on a missing workspace

modules/hyprland: Fix segfault when attempting to set_urgent on a missing workspace

---

include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp

Support https://github.com/Alexays/Waybar/issues/2271#issuecomment-1706681105 to fix `hyprland-autoname-workspace` and `hyprctl dispatch renameworkspace`.=

hyprland/workspaces: react on renameworkspace event

---

include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspaces.cpp

With this PR, `active_only` can be set to true, which will only show the active workspace. 
If I understand the feature request correctly, each monitor should show the currently visible workspace, right? This PR currently only shows the active one as reported by Hyprland, so if a monitor is not focused, it will not show any workspaces. Is this supposed to happen? I would expect it to be better if each monitor shows one "active" workspace, i.e. the one currently visible.
Let me know if this can be improved.
CC @Anakael @MightyPlaza

Implement 'active_only' option and 'visible' class in hyprland/workspaces

---

src/modules/hyprland/workspaces.cpp

Closes: https://github.com/Alexays/Waybar/issues/2481
Verified locally. With a `hyprctl dispatch renameworkspace 3 "4"` and saw old behavior (top) and new behavior (bottom) of it keeping the active state. My config visible = blue and active = green.

fix: rename workspace active fix

---

include/modules/hyprland/workspaces.hpp
include/util/enum.hpp
include/util/string.hpp
man/waybar-hyprland-workspaces.5.scd
man/waybar.5.scd.in
meson.build
src/modules/hyprland/workspaces.cpp
src/util/enum.cpp

Closes: https://github.com/Alexays/Waybar/issues/2474
Adds a `sort-by` option that takes in a string to choose how to sort workspaces. This allows you to manually specify the sorting method and future sorting methods can just utilize the same config option. Fallsback to the original sorting.

feat: hyprland workspaces add sort-by

---

man/waybar-hyprland-workspaces.5.scd
man/waybar-sway-workspaces.5.scd
src/modules/hyprland/workspaces.cpp
src/modules/sway/workspaces.cpp
src/modules/wlr/workspace_manager.cpp

Closes: https://github.com/Alexays/Waybar/issues/2443 
Persistent workspaces currently is the only option using this naming style, changing to match all other options. 
Prompt updating config from `persistent_workspaces` to `persistent-workspaces` but keep current implementation support until after next release to remove. 
Follow up: Update wiki entries to match new name.

deprecate persistent_workspaces in favor of persistent-workspaces

---

include/client.hpp
include/util/portal.hpp
meson.build
src/client.cpp
src/util/portal.cpp

summary:
-------
This commit adds xdg-desktop-portal support to waybar. If a portal supporting `org.freedesktop.portal.Settings` exists, then it will be queried for the current colorscheme. This colorscheme will then be used to prefer a `style-light.css` or `style-dark.css` over the basic `style.css`.
technical details:
-----------------
Appearance is provided by several libraries, such as libhandy (mobile) and libadwaita. However, waybar links to neither of these libraries. As the amount of code required to communicate with xdg-desktop portal as a client is rather minimal, I believe doing so is better than linking to an additional library.
The Gio library for communicating with dbus is rather messy, Instead of the `Portal` class containing a `Gio::Dbus::Proxy`, it extends it which …

search for dark or light mode stylesheet

---

man/waybar-battery.5.scd
src/modules/battery.cpp

Adds `bat-compatibility` boolean checking from configuration file.
Fixes: https://github.com/Alexays/Waybar/issues/2459

Fix battery not showing for some devices

---

flake.nix
result
src/modules/backlight.cpp

fixes backlight module showings incorrect percentage(eg 101% instead of 100% or 47% instead of 45%) on asahi linux
we need use `brightness` not `actual_brightness`

fix(backlight): wrong percentage numbers for device apple-panel-bl

---

include/modules/custom.hpp
include/util/sleeper_thread.hpp
man/waybar-custom.5.scd
src/modules/custom.cpp

These changes are intended to fix a performance problem I had on my laptop where using signals on my custom modules would cause excess CPU usage and battery drainage.
This PR makes it so that any custom module with an undefined `interval` but a defined `signal` will start up a thread with the new `Custom::waitingWorker()` function. This is identical to an `interval` based update with signals but will instead sleep indefinitely using a new `SleeperThread::sleep()` function.
Aside from making this a usable combination of config options this is higher performance than both the `"once"` option and any given integer interval. Full disclaimer, I am not an optimizations expert but waybar's CPU usage went from between 0.4% and 0.6% (sometimes getting much higher but I haven't recorded that and it …

Lighter Weight Signal-Based Custom Modules

---

src/modules/hyprland/workspaces.cpp

Wlr and Sway modules use the workspace `name` as the default icon if no icon is provided. This adds the same behavior for the `hyprland/workspace` module. 
Closes https://github.com/Alexays/Waybar/issues/2533
Before this fix, it defaulted to the last defined icon, which is silly (see above issue).

hyprland/workspaces: use `name` as fallback icon

---

src/modules/hyprland/workspaces.cpp

Fixes #2505
This PR makes sure special workspaces can be removed. Before this, the code for `Workspaces::remove_workspace()` didn't account for the workspaces starting with `special:` in their names, which resulted in the workspace not being found and, thus, not being removed.
During the investigation of this bug, I also stumbled upon Hyprland creating special workspaces twice. The second workspace always seems to be called `special:` + the name of the first special workspace, resulting in "doubled specials" (`special:special:<some_name>`). This PR also prevents the creation (and deletion) of workspaces named `special:special:`, which served no purpose and would linger a few seconds in the user's bar. See hyprwm/Hyprland#3424 for more info.
- Introduction of Special Workspace support in …

Fix: Hyprland's special workspaces aren't cleared

---

include/modules/hyprland/workspaces.hpp
include/util/rewrite_string.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/backlight.cpp
src/modules/battery.cpp
src/modules/custom.cpp
src/modules/hyprland/workspaces.cpp
src/util/rewrite_string.cpp

This PR introduces 3 new configurations for `hyprland/workspaces`, as well as a new formatter for `format`. These can be used to display all of a workspace's currently opened windows.
Unlike actual disciplined people, I can't seem to "assign responsabilities" to my workspaces, and tend to use them chaotically. This means that I frequently forget where I've left my browser or my VS Code windows and have to search for them.
As I'm aware I'm not alone in this, I ported over a functionality I had in my [Eww](https://github.com/elkowar/eww) setup that allows you to display a workspace's content dynamically.
We've added the `windows_map_` attribute to the `Workspace` class, mapping a window's address (currently represented by a string) to its user-facing representation. The representation is …

Feature: Hyprland dynamic window names on workspaces

---

include/modules/disk.hpp
man/waybar-disk.5.scd
src/modules/disk.cpp

This PR allows the user to force the disk output to always be in a specific unit, and not automatically change unit as the size in question changes. See below for a few example configs, which should demonstrate this change.
```
"disk": {
"interval": 30,
"format": "{specific_free:0.2f} GB out of {specific_total:0.2f} GB available. Alternatively {free} out of {total} available",
"unit": "GB"
// 1434.25 GB out of 2000.00 GB available. Alternatively 1.4TiB out of 1.9TiB available.
}
```
```
"disk": {
"interval": 30,
"format": "{specific_free:0.2f} GB out of {specific_total:0.2f} GB available. Alternatively {free} out of {total} available",
"unit": "GB"
// 0.25 GB out of 2000.00 GB available. Alternatively 241.3MiB out of 1.9TiB available.
}
```
I have added new options instead of updating …

Adding options to allow disk outputs to always be in a specific unit.

---

include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspaces.cpp

This PR introduces a new option to `hyprland/workspaces` called `ignore-workspaces`. This option is an array of regexes that will be matched against workspace names. If there's a match, the workspace being created will not be shown on the user's bar.
Chrome is notorious for launching a "sharing indicator" when your screen is being shared. This is specially frustrating when using tiling managers, such as Hyprland. 
My current solution for not having to see it is by forcing it to move to a workspace named `special:hell`. This PR, then, lets me add it to a ignored list of workspaces, with the following rule:
```json
"hyprland/workspaces": {
"ignore-workspaces": [
"(special:)?hell"
]
}
```
*(note that I'm optionally matching against "special:" because Hyprland is not very consistent when it …

Feat/Hyprland/Workspaces: Ignore workspaces

---

include/modules/cava.hpp
man/waybar-cava.5.scd
src/modules/cava.cpp

Hi everyone, this is a great project, thank you! It urged me to contribute....
I added to the cava module a configuration option `hide_on_silence`. If it is set to `true` the cava label is hidden if no sound is played after `sleep_timer` seconds.
If the option is not specified or set to `false` the bahaviour is unchanged (current behaviour, no hiding).

Revise cava module to hide on silence

---

include/modules/hyprland/workspaces.hpp
include/util/regex_collection.hpp
man/waybar-hyprland-workspaces.5.scd
meson.build
src/modules/disk.cpp
src/modules/hyprland/workspaces.cpp
src/util/regex_collection.cpp
src/util/rewrite_string.cpp

Resolves #2561 
This PR builds upon #2529 to introduce matching against a window's title in order to get its icon. In order to do that, the function that matches against regexes will now be supplied a string in this format: `"class<WINDOW_CLASS> title<WINDOW_TITLE>"`, as opposed to just the class. This way, users may provide rules in the following forms:
```json
"window-rewrite": {
"title<.*youtube.*>": "", // Windows whose titles contain "youtube"
"class<firefox>": "", // Windows whose classes are "firefox"
"class<firefox> title<.*github.*>": "", // Windows whose class is "firefox" and title contains "github". Note that "class" always comes first.
"foot": "", // Windows that contain "foot" in either class or title. For optimization reasons, it will only match against a title if at …
```

Feat/Hyprland: Allow matching against Window Titles for Rewrite

---

include/bar.hpp
include/group.hpp
man/waybar.5.scd.in
src/bar.cpp
src/group.cpp

This PR introduces "group drawers". This feature allows to user to hide all but the first element of a group until the mouse hovers over the group. The user can configure the animation's speed and direction.
https://github.com/Alexays/Waybar/assets/25804378/c96c3178-0528-42cb-b3ff-e226c3fbe6e3
The configuration to enable group drawers is available as a key under a group:
```json
"group/group-power": {
"orientation": "inherit",
"drawer": {
"transition-duration": 500,
"children-class": "not-power",
"transition-left-to-right": false,
},
"modules": [
"custom/power", // First element is the "group leader" and won't ever be hidden
"custom/quit",
"custom/lock",
"custom/reboot",
]
},
"custom/quit": {
"format": "󰗼",
"tooltip": false,
"on-click": "hyprctl dispatch exit"
},
"custom/lock": { …
```

Feature: Group Drawers

---

man/waybar-mpris.5.scd
src/modules/mpris/mpris.cpp

In all other places, the norm is to use `on-click-(middle|right)` but in the mpris module, `on-(middle|right)-click` was being used which caused clicks to malfunction if set to some custom commands

fix(modules/mpris): fix on-*-click typos

---

include/ASlider.hpp
include/modules/backlight.hpp
include/modules/backlight_slider.hpp
include/modules/pulseaudio.hpp
include/modules/pulseaudio_slider.hpp
include/util/audio_backend.hpp
include/util/backend_common.hpp
include/util/backlight_backend.hpp
man/waybar-backlight-slider.5.scd
man/waybar-pulseaudio-slider.5.scd
meson.build
src/ASlider.cpp
src/factory.cpp
src/modules/backlight.cpp
src/modules/backlight_slider.cpp
src/modules/pulseaudio.cpp
src/modules/pulseaudio_slider.cpp
src/util/audio_backend.cpp
src/util/backlight_backend.cpp

This PR:
1. Slightly refactors the pulseaudio module, moving all logic specific to dealing with pulseaudio into its own class, `PulseaudioBackend`;
2. Slightly refactors the backlight module, moving all logic specific to controlling brightness into its own class, `BacklightBackend`;
3. Introduces the Abstract Slider class `ASlider`;
4. Implements `PulseaudioSlider`, based on `ASlider` and `PulseaudioBackend`;
5. Implements `BacklightSlider`, based on `ASlider` and `BacklightBackend`;
https://github.com/Alexays/Waybar/assets/25804378/9a75aaed-ccea-4b93-a48d-7fa5878fd479
<details>
<summary>Audio Config</summary>
```json
"group/group-audio": {
"orientation": "inherit",
"drawer": {
"transition-duration": 500,
"children-class": "",
"transition-left-to-right": false,
},
"modules": [ …
```

Feature: Fantastic Sliders and Where to Find Them (Audio, Backlight and Abstract Sliders)

---

src/modules/clock.cpp

Fix allows for 12 hour clock format "{:%-I:%0M %p}" resulting in no leading zero on the hour.

fix clock to work with fmt 10.x

---

include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp

Fixes #2557
This PR fixes an issue that caused windows to disappear. This was caused because, sometimes, Hyprland's IPC decides to report the window-related event (`openwindow`, `movewindow`) before the `createworkspace` event. This, in turn, caused Waybar to have nowhere to put the moved/opened window, causing it to be discarted.
In order to solve this problem, the window creation has been delayed, much akin to how workspaces are created; they are pushed into a vector and are processed during `Workspaces::update()`. There will be 3 attempts to create each window, accounting for the possibility that the `createworkspace` message got *just* late enough that it wasn't processed in the same `update()` call.

Fix: Hyprland/Workspaces' windows disappearing when moving around

---

.github/workflows/lint.yml

Currently, only `h`, `cpp` and `c` files are linted using the Linter CI workflow.
Since there are multiple files with the `hpp` file ending, I added this file ending to the workflow config.

Lint header files with hpp file ending

---

include/modules/upower/upower.hpp
include/modules/upower/upower_tooltip.hpp
include/util/scope_guard.hpp
src/ALabel.cpp
src/modules/bluetooth.cpp
src/modules/cpu_usage/bsd.cpp
src/modules/custom.cpp
src/modules/mpris/mpris.cpp
src/modules/sni/host.cpp
src/modules/sni/watcher.cpp
src/modules/upower/upower.cpp
src/modules/upower/upower_tooltip.cpp
src/util/prepare_for_sleep.cpp

While looking through the source code, I found a few potential memory leaks.
Most of them were caused by early returns (e.g. because of an exception) without freeing a resource first.
To prevent those and make the code more robust, I added a `scope_guard` which will ensure via RAII that the resources are freed.
Additionally, I added them in a few places where `GError`s are in use and where I think there might be a risk in the future.
Instead of this custom `scope_guard` it could also be considered to use a third-party library but I think it's easier to provide this simple functionality in `util` instead of integrating yet another dependency.
I tried to group the different kinds of fixes I did in different commits, I'll squash them in the end to make history more readable.
Also, I made the …

Fix potential memory leaks

---

include/util/sleeper_thread.hpp

This PR fixes an issue which prevented `signal` from working without an `interval`.
For some reason, it was not allowed to interrupt the `sleep()` of a `SleeperThread`.
This change keeps the function consistent with sleep_until() and sleep_for() which both can be interrupted.
Resolves #2587 
Edit: `exec-on-event` is probably also affected

Custom module: Allow signal without interrupt

---

src/modules/network.cpp

On new interface discovery a new index is (may be) assigned to the `temp_idx`.
The new interface should be assigned to `net` if is the first one (`net->ifid_ == -1`) or if has higher priority (`priority < net->route_priority`... lower is higher according to metric).
This PR removes the additional condition `net->ifid_ != temp_idx` which is always be true and incorrectly ends up showing the last found route instead of the one with higher priority
Closes https://github.com/Alexays/Waybar/issues/2167

Show the network interface with highest priority (aka lower metric)

---

man/waybar-mpris.5.scd
src/modules/mpris/mpris.cpp

This PR sets the interval value to 0. It seems this is what it was meant to be set at, but was changed to '5' in commit ba6faa7.
This closes #2392.

modules/mpris: change default interval value to 0

---

include/modules/hyprland/window.hpp
include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp
src/modules/network.cpp

Did some cleanup in hyprland/workspaces:
* Renamed the CreateWindow class to WindowCreationPayload, to make it clearer it isn't a function but a class.
* Added const qualifiers and references to functions 
* Added std::move in initializer lists to avoid making copies
* ~~Put the WINDOW_CREATION_TIMEOUT variable in an anonymous namespace (it used to be statically defined inside the function it was used in, I don't understand why?)~~
On a related note, I also started a discussion here about adding a clang-tidy file to the repo: https://github.com/Alexays/Waybar/discussions/2591. I'd love to hear your thoughts on this. 
CC: @Syndelis @khaneliman @Anakael @MightyPlaza

General cleanup in hyprland/workspaces

---

src/modules/hyprland/workspaces.cpp

Fixes #2597
This PR guarantees persistent workspace rules will be applied even if the workspaces already exists at bar startup.
Previously, persistent workspaces would always be created before regular workspaces. #2578 changed that in order to guarantee workspaces were created with their respective windows.
However, this meant that pre-existing would-be-persistent workspaces were being created by another function, one which did not account for the persistent configuration.
The changes in this PR makes it so that the `Workspaces::create_workspace` method checks if a workspace with the same name already exists and, if so, sets the workspace as persistent depending on the payload, rather than attempting to create a new one.

Fix: Hyprland/Workspaces workspaces not being created as persistent when they already exist at startup

---

.github/workflows/freebsd.yml

Since the freebsd job is pretty unreliable, I reduced the timeout to 30min instead of the default of 6h.
The issue is known: https://github.com/vmactions/freebsd-vm/issues/74
Alternatively, if there are no fixes for this github action, it could be considered to switch to a different action.
One project already moved away from the one that is currently used in waybar:
https://github.com/mpv-player/mpv/commit/71a497deee8f5cb47a9ea37bc14038ecdf238e21

Reduce freebsd ci timeout

---

include/modules/upower/upower.hpp
include/modules/upower/upower_tooltip.hpp
include/util/scope_guard.hpp
include/util/sleeper_thread.hpp
src/ALabel.cpp
src/modules/bluetooth.cpp
src/modules/cpu_usage/bsd.cpp
src/modules/custom.cpp
src/modules/mpris/mpris.cpp
src/modules/sni/host.cpp
src/modules/sni/watcher.cpp
src/modules/upower/upower.cpp
src/modules/upower/upower_tooltip.cpp
src/util/prepare_for_sleep.cpp

As mentioned in the issue, the bug is caused by the standard library expecting for `std::condition_variable::sleep_for` a duration which does not cause an overflow when added to the current time.
This PR fixes the issue by using `sleep_until` to emulate `sleep_for` since `sleep_for` is defined as identical to adding the current time and then using `sleep_until` by the standard.
Additionally, this PR re-applies #2586 which was reverted in #2599 because of this bug.
I also tried to write a test to catch this kind of error for `SleeperThread`, but I wasn't able to check for this kind of failure.
The standard does not specify the behavior if a too big duration is passed.
I ended up writing a few basic other tests for the class and restructured the build system to allow for easier addition to …

Fix sleep_for for max duration

---

.github/workflows/freebsd.yml
src/modules/cpu_usage/bsd.cpp

Since the new CI Action for FreeBSD seems to take more than 30min, I increased the limit to 2h.
Additionally, due to the defective CI a build error is in the master due to the renaming of `scope_guard` to `ScopeGuard` (I missed that one unfortunately).

Fix FreeBSD build error and increase freebsd ci timeout

---

src/modules/mpris/mpris.cpp

NoActivePlayer messages is being logged everytime mpris polls for players when there are no active players. This message is spamming my hyprland error logs. Attached the log
```
[2023-10-31 11:00:18.444] [error] mpris[playerctld]: GDBus.Error:com.github.altdesktop.playerctld.NoActivePlayer: No player is being controlled by playerctld
[2023-10-31 11:00:18.557] [info] Bar configured (width: 1440, height: 34) for output: eDP-1
[2023-10-31 11:00:28.408] [error] mpris[playerctld]: GDBus.Error:com.github.altdesktop.playerctld.NoActivePlayer: No player is being controlled by playerctld
[2023-10-31 11:00:33.407] [error] mpris[playerctld]: GDBus.Error:com.github.altdesktop.playerctld.NoActivePlayer: No player is being controlled by playerctld
[2023-10-31 11:00:38.407] [error] mpris[playerctld]: …
```

Skips logging NoActivePlayer error msgs

---

src/modules/custom.cpp

This is the fix for the issue described in #2621: We should not crash if the input to a custom widget is invalid utf-8.
Instead, invalid characters are now shown as appropriate characters in your font:
I did not touch the JSON input code, since it should be fine as JSON should be valid UTF-8. I suspect there are other places in Waybar that needs similar treatment. This is beyond the scope of this PR though.
Please double check for potential memory leaks, as my C++ is rusty (no pun intended).

fix: custom: do not crash if input text is not valid utf-8

---

src/modules/sni/item.cpp

I delete tmp_size part, when call `load_icon` function, use request_size `icon_size * image.get_scale_factor()` like wlr/taskbar
`get_icon_sizes` doesn't handle scaling, if icon isn't scalable, tmp_size will be smaller size
https://github.com/Alexays/Waybar/blob/1149e51f7271fbb81b610c223dccc8181926c7e2/src/modules/wlr/taskbar.cpp#L181-L184
for example: nm-applet

tray: load_icon use request_size directly

---

src/modules/hyprland/workspaces.cpp

Waybar would crash after turning off/on monitor (especially after https://github.com/hyprwm/Hyprland/pull/3713). 
Might fix https://github.com/Alexays/Waybar/issues/2039 and https://github.com/Alexays/Waybar/issues/2015.

hyprland/workspaces: fix crash on monitor off/on

---

include/util/command.hpp

When turning off/on the monitor it would lead to defunct processes started by custom modules. I don't know why this is needed since we are tracking the pid of forked processes and properly waiting them (either on `command::close` or on `Custom` destructor).
Fixes #1713 (and probably #2244).

custom: reap zombie processes on termination

---

src/modules/clock.cpp

see [Issue 2615: Daylight saving hour breaks clock module](https://github.com/Alexays/Waybar/issues/2615)

avoid converting to local_time when converting to zoned_time afterwards

---

src/modules/wireplumber.cpp

The WirePlumber module assumes that either the node's name or description will not be null. This leads to a segmentation fault when both are.
The solution provided is to set self->node_name_ to a default value in this case.

Fix segmentation fault in WirePlumber module

---

include/AModule.hpp
include/modules/clock.hpp
include/util/date.hpp
man/waybar-clock.5.scd
meson.build
src/AModule.cpp
src/modules/clock.cpp
test/date.cpp

Hi @Alexays ,
This PR is created in order to fully switch clock module to use standard chrono library + format library in c++20.  date library by @HowardHinnant has been taken into standard in C++20. STL format library supports chrono now.
So clock module under C++20 now no more using fmt library and construct necessary information using STL.
One more major change: clock module is fully rewritten and as a base is using TZ(zoned time). It should minimize time conversion between local and zoned time. 
Structure of the helper include/util/date.hpp now provides compile time switching between 
"date/tz.h" + "fmt/chrono.h" <-> \<chrono> + \<format>
timezoned_time_list placeholder now is renamed to tz_list . This change is attracted in man page too.
\+ it should solve any issues during …

c++20. clock chrono API. STL + format

---

src/modules/hyprland/workspaces.cpp

When using more than one monitor, special workspaces may show in the workspace list while they don't with a single screen.
This patch addresses this issue.

Fix for #2646

---

src/modules/cpu_usage/linux.cpp

The ```iowait``` time present in ```/proc/stat``` is a sub-category of idle, and therefore shouldn't count toward CPU usage. However, Waybar doesn't account for it when calculating the idle time, giving wrong results in some cases.
For example, when running the following command on an idle system, to create a completely I/O bound task pinned to the first CPU:
taskset 1 dd if=/dev/sda of=/dev/null bs=1MB
Waybar displays the first CPU at 100% usage, which is incorrect, since the CPU is idle most of the time waiting for I/O, while other tools such as ```htop``` display the same CPU fairly close to 0%.

cpu_usage/linux: count iowait toward idle time

---

src/modules/hyprland/workspaces.cpp

added sorting of workspaces after a rename event got handled. The solution was mentioned in #2271

hyprland module: added sort_workspaces after rename occured

---

src/modules/wlr/taskbar.cpp

Icons are sometimes not found in the taskbar, for two reasons:
1. The icon given in the .desktop file for that program cannot be found.
2. Waybar is not given an `app_id`, so lookup is impossible.
If the user has configured Waybar to only show applications as icons, this means that the program is now essentially "hiding":
With this patch, when an icon cannot be found, Waybar will now load the "image-missing" icon of Gtk:

Using 'image-missing' fallback if no taskbar icon is found

---

src/modules/privacy/privacy.cpp

Only consider a privacy module as visible if it is enabled in the configuration. Otherwise, when screensharing or audio-in or audio-out is in use but the associated module is not enabled, the privacy widget is empty but still considered as visible.

privacy: fix visibility when a module is disabled

---

src/modules/hyprland/workspaces.cpp

When clicking on the hyprland special workspace button twice in a row, the toggle doesn't behave correctly.
This fixes the issue that hyprland special workspaces are not toggled correctly when you click on the buttons quickly more than once. Also eliminates some duplicate calls made to hyprland for any workspace switching.

Add button click check to hyprland workspaces module

---

src/modules/wireplumber.cpp

This fixes a crash where PipeWire tries to send events to a destroyed WirePlumber module.
Fixes #2154.

Disconnect from PipeWire when destroying the WirePlumber module

---

.clang-tidy

More info here: https://github.com/Alexays/Waybar/discussions/2591

Added initial .clang-tidy file

---

include/modules/upower/upower.hpp
man/waybar-upower.5.scd
src/modules/upower/upower.cpp

Adds the ability to hide the battery icon in the upower module. ie.
```json
"upower": {
"show-icon": false,
"hide-if-empty": false,
"tooltip": true,
"tooltip-spacing": 20,
"format": "{percentage}",
"format-alt": "{percentage} {time}"
}
```

upower: show-icon config option

---

README.md

It doesn’t make sense to keep the list in README.md when we maintain it in Wiki as well.

Clear README.md from duplicated list of distributions

---

src/modules/sway/workspaces.cpp

Fix persistent icon in sway/workspaces module.

Sway/workspaces: fix persistent icon

---

man/waybar.5.scd.in

I always find pure JSON cumbersome for configuration files due to the lack of support for comments. Seeing up-front that the configuration file is actually JSONC would have aided my adoption of waybar.
Changes proposed in this pull request:
- Clarify that the configuration file is JSON*C* format
- The configuration file can also be named config.jsonc
- Remove 'config' from list of documented valid locations

Specify config is JSONC

---

Dockerfiles/debian

* Added `sudo python3-venv python3-pip`
* Formatted Dockerfile
These packages are required for the clang-tidy action we talked about here: https://github.com/Alexays/Waybar/pull/2720#issuecomment-1845155151
PR for clang-tidy action coming soon (after this is merged and a new debian image is uploaded).

Added sudo, python3-pip & python3-venv to debian image, required for clang-tidy GH action

---

src/modules/wireplumber.cpp

The reverse-scroll option does nothing currently, since the reverse logic is present in both **AModule::getScrollDir** and **Wireplumber::handleScroll** thus reversing it twice when enabled.
This PR remove the reverse logic in **Wireplumber::handleScroll** to be consistent with other modules.

Fix wireplumber reverse-scroll option

---

.github/workflows/clang-tidy.yml

Reason: https://github.com/Alexays/Waybar/pull/2755#discussion_r1435861701
Thanks for all the help @2bndy5!

Bump clang-tidy cpp-linter-action version to v2.7.5

---

.github/workflows/freebsd.yml

I noticed the freebsd action fails more than half the time during teardown of the VM, so I thought maybe updating the action to the latest release would fix this. Last release was from 2023-10-07, now updating to the release from 2023-11-03.

Bump cross-platform-action to attempt fixing freebsd runner

---

src/modules/custom.cpp

Bug popped up from my previous PR (#2517) where users with modules that had both a `restart-interval` and `signal` defined would end up with a module that behaves as though only a signal is defined.
This PR fixes this issue (#2650).

fix `restart-interval` being ignored while `signal` is defined (#2650)

---

man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspaces.cpp

This turns the values of window rewrite rules in hyprland/workspaces from static strings to format strings with the values {class} and {title} available.
For example, I'm now doing this to list windows in each workspace without having to add a rule for every application I use:
```
"hyprland/workspaces": {
"format": "{name}: {windows}",
"window-rewrite-default": "{class}",
},
```

hyprland/workspaces: allow using the original window class/title

---

meson.build
subprojects/catch2.wrap

Hi @Alexays this PR is intended to fix #2447 . Originally root cause comes from the library upstream https://github.com/catchorg/Catch2/issues/2722 . This issue is closed and got into the freshest Catch2 releases.

Catch2 bump

---

README.md
include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp

An issue exists when using the Window Rewrite feature on Hyprland/Workspaces. The issue manifests only when the user has `all_outputs = false` on their configuration and moves a window from one of monitor A's workspaces to one of monitor B's workspaces. When that happens, the window's icon vanishes, and can only be seen again if the bar is restarted.
This happens because on this setup, not all workspaces exist accross all bar instances. The way that window moving works is that it "cuts" the icon from workspace 1 and "pastes" it to workspace 2, avoiding having to re-process the window's icon. However, since the origin workspace might not exist on one of the bar's instances, the window is rendered empty.
This PR introduces a new map `Workspacess::m_orphanWindowMap` which will now hold every …

Fix/Hyprland/Workspaces: Window Rewrite on multiple non-overlapping bars

---

include/factory.hpp
include/modules/systemd_failed_units.hpp
man/waybar-systemd-failed-units.5.scd
meson.build
src/factory.cpp
src/modules/systemd_failed_units.cpp

This module monitors the number of failed systemd units and can warn user if there is something going wrong. It's especially useful for periodic services.
Currently only the count is monitored and displayed, and there's no tooltip. It's nontrivial to get the actual failed unit names and it seems to require enumerating all units and then filter, which would be too CPU intensive to be done frequently.
Related but not equivalent to #1187.

Add module systemd-failed-units to monitor failed systemd units

---

src/modules/sni/tray.cpp

Given the following tray:
Before when empty:
After when empty:

fix(tray): completely hide tray when it is empty

---

src/modules/clock.cpp

Add `nullptr` to the timezones vector, so that the current timezone is fetched on each `update()`, and changes to it (e.g. with `timedatectl set-timezone`) are propagated.
(reimplements #2296 whose changes were undone in #2340)

clock: handle timezone changes (again again)

---

src/modules/clock.cpp

Fixes #2839.
I don't think the calendar will follow runtime timezone changes, but at least the clock will since #2838.

clock: fix construction with calendar.format.today

---

include/modules/upower/upower.hpp

Force displayDevice to be a nullptr on class setup
Should fix seg faults and device not displaying
Current code expects UPower::displayDevice to be initially null. If it is not, as was the case on my box, it can lead to seg faults or the device not displaying information

Fix module UPower display device poniter

---

src/modules/image.cpp

Since the GTK Image is hidden, the CSS class wasn't used for every cases.

Move `.empty` CSS class from Img to Box in the Image module

---

include/util/audio_backend.hpp
src/util/audio_backend.cpp

For some reason, I sometimes restart the pulseaudio server (pipewire-pulse actually). But after restart, waybar's pulseaudio module just stop updating. The solution is to restart the whole waybar.
So I think it would be better if waybar itself could reconnect to pulseaudio server after it restarts.
The pulseaudio context connection would failed according to the [documentation](https://freedesktop.org/software/pulseaudio/doxygen/def_8h.html#a892684c03cf9edaed1a95e609ec7573c). So we can simply reconnect the context there.
Tested on waybar latest git version and pipewire-pulse 1.0.0
Fixes: #2619
PS: I am not so good at C++ actually. So I am sorry if I do something stupid. :)

pulseaudio: reconnect context when pulseaudio server restarts

---

include/util/json.hpp
test/JsonParser.cpp
test/meson.build

Fixes #2495 and #2475
The JSON spec doesn't allow characters like `\xab`. Instead, it should be converted to unicode: `\u00ab`. 
It's my first time writing catch2 tests, let me know if I did something wrong.

Fix JSON parsing with hexadecimal characters

---

src/group.cpp

Fix: drawer not appearing on configured side

---

resources/config

Fixes #2893
This PR makes it so that, when the `battery` module is in the `Full` state, the battery life estimate is inaccessible similarly to how the module acts in the `Charging` and `Plugged` states.
This is done by adding a line in the default config which sets a format for the `Full` state. Setting a format for a given state disables access to the `format-alt` display while that state is active.
There are possibly better ways to approach this than a config change, but I couldn't think of any that wouldn't limit the functionality of other configs that may use `format-alt` here for things other than displaying a battery estimate, in which case the issue wouldn't occur.
If there is a better solution to this problem, please let me know and I'll look into that instead.

Make battery estimate inaccessible in the "Full" state on default config

---

include/AModule.hpp
include/bar.hpp
src/ALabel.cpp
src/ASlider.cpp
src/bar.cpp
src/modules/custom.cpp
src/modules/dwl/tags.cpp
src/modules/hyprland/workspaces.cpp
src/modules/image.cpp
src/modules/keyboard_state.cpp
src/modules/river/tags.cpp
src/modules/sni/tray.cpp
src/modules/sway/workspaces.cpp
src/modules/wlr/taskbar.cpp
src/modules/wlr/workspace_manager.cpp

At some point, my draft style for Fedora configuration was looking like that:
<details>
<summary>Warning: ugly CSS fragment inside</summary>
```css
/* Common module rules */
.modules-left > widget > label,
.modules-center > widget > label,
.modules-right > widget > label {
color: inherit;
margin: 0;
padding: 0 10px;
}
box.vertical.modules-left > widget > label,
box.vertical.modules-center > widget > label,
box.vertical.modules-right > widget > label {
padding: 10px 0;
}
window#waybar:not(.bottom):not(.left):not(.right) .modules-left > widget > label,
window#waybar:not(.bottom):not(.left):not(.right) .modules-center > widget > label,
window#waybar:not(.bottom):not(.left):not(.right) .modules-right > widget > label {
box-shadow: inset 0 -2px;
}
window#waybar.bottom .modules-left > widget > …
```

Add `module` class to the root elements of the modules 

---

src/bar.cpp

```
[1/2] Compiling C++ object waybar.p/src_bar.cpp.o
../src/bar.cpp: In function ‘Glib::ustring waybar::to_string(Gtk::PositionType)’:
../src/bar.cpp:120:1: warning: control reaches end of non-void function [-Wreturn-type]
120 | }
| ^
```

fix build warning in bar.cpp

---

man/waybar-custom.5.scd
src/modules/custom.cpp

Issue https://github.com/Alexays/Waybar/issues/2914 tries to use `tooltip-format` on a custom module without a script. This change results in `tooltip-format` entries in config being used as the tooltip format, _**over**_ any tooltip-related return from the output of a custom script if there is one.
This makes the most sense to me as it is the more visible change. If I see a `tooltip-format` entry in the config file, I expect that this is truth, not the output of a script in a different place. While it wouldn't be best practice to setting the tooltip in both places, I'd argue that a user would expect that their change to the config would be reflected in the case of using a 3rd party script they don't fully understand.

Add check for tooltip-format for custom modules

---

src/modules/temperature.cpp

Background and Motivation
-------------------------
When the `hwmon-path-abs` and the `input-filename` fields are used for the temperature module, we evaluated the following path:
```
[hwmon-path-abs] / [gap] / [input-filename]
```
where `gap` is the first file or directory in the `hwmon-path-abs` directory. This usually works but it doesn't seem to work for NVME or WiFi temperature sensors. For those cases, there are a bunch of other files in the `hwmon-path-abs` directory. In the bad case, the first selected file is not the one with the prefix `hwmon` and we end up checking the wrong location for the `input-filename`.
Change description
------------------
We are simply going through the `hwmon-path-abs` directory and searching for the first file/directory that begins with `hwmon`.
Test …

Search for the first hwmon* directory

---

include/modules/cpu.hpp
man/waybar-cpu.5.scd
src/modules/cpu.cpp

Fixes: https://github.com/Alexays/Waybar/issues/2911

Add style class for CPU state

---

include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp

This adds the following css classes to special workspaces in hyprland:
- active (+ correct behavior on monitor focus change)
- visible
- empty 
Styling only normal workspaces or only special workspaces is still possible. Example with `active`:
```css
#workspaces button.active:not(.special) {} /* only normal */
#workspaces button.active.special       {} /* only special */
```

Add css classes to hyprland special workspaces

---

include/modules/sway/workspaces.hpp
man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

This implementation mimics to some extend the implementation of hyprland

Implement windows formating in sway/workspaces

---

include/factory.hpp
include/modules/battery.hpp
include/util/css_reload_helper.hpp
man/waybar-hyprland-workspaces.5.scd
meson.build
protocol/meson.build
src/factory.cpp
test/meson.build

See individual commits for details.

build: refactorings and deprecation fixes

---

include/factory.hpp
src/factory.cpp

None of these includes are required in the header.

refactor: move all module includes to factory.cpp

---

.github/workflows/linux.yml
Dockerfiles/debian
meson.build
test/css_reload_helper.cpp
test/date.cpp
test/main.cpp

Should be the last one for today :)

Improve CI build times

---

include/util/date.hpp
src/modules/clock.cpp

`tz_up`/`tz_down` actions would crash on `nullptr` in the timezone list after 392f83e.
Since I had to look at the clock code anyways, I also fixed a warning about a reserved name for UDL (`-Wliteral-suffix`).

fix(clock): crash on scrolling with local timezone ("") in the list 

---

src/modules/hyprland/window.cpp

Due to [this change](https://github.com/hyprwm/Hyprland/pull/3186) in hyprland, the json value of the `"swallowing"` field is `"0x0"` when no window is swallowed, compared to `null` before.

Fixed window#waybar.swallowing for module hyprland/window

---

.github/workflows/clang-tidy.yml

The problem with cpp-linter-action is that they bring their own Python (via `actions/setup-python`), but fail to ensure that the dynamically-linked interpreter can find the `libpython3.xx.so`, either via `DT_RPATH` or with `LD_LIBRARY_PATH`:
```
/__t/Python/3.11.8/x64/bin/python: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory
```
The suggested fix is to have a matching version of libpython in the container, which... isn't optimal: the container (Debian) Python can have different patch release and build configuration.
Here I'm trying a different thing &mdash; run the same `setup-python` action but allow it to export `LD_LIBRARY_PATH`. And if that works, we can drop python3-pip/python3-venv packages from the debian …

ci: fix clang-tidy action

---

src/modules/cpu_frequency/bsd.cpp

This patch implements cpu_frequency module for BSD by sysctl.
Currently, I search all OID until it cannot find more.

feat: implement cpufreq for bsd by sysctl

---

resources/config
resources/style.css

Small non-functional changes to the default configuration

Config tweaks

---

.clang-tidy
include/modules/hyprland/backend.hpp
include/modules/hyprland/language.hpp
include/modules/hyprland/submap.hpp
include/modules/hyprland/window.hpp
src/modules/hyprland/backend.cpp
src/modules/hyprland/language.cpp
src/modules/hyprland/submap.cpp
src/modules/hyprland/window.cpp

CC: @Syndelis @khaneliman because you guys seem to be the most recently active in these files

fix clang-tidy errors in hyprland module

---

include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp

Fixes #2945
Split the config and rule persistency in 2 attributes, one storing the persistency as set in Waybar's config, the other one storing the persistency as set in Hyprland.
It fixes some conflicts between the persistency state of a workspace as set in Waybar's config and its dynamic state in Hyprland.
It allows to remove a persistent workspace in Waybar if this workspace is removed from Hyprland and if the workspace is not set as persistent in Waybar's config.

hyprland/workspaces: Improve the workspaces persistency logic

---

include/modules/hyprland/window.hpp
src/AAppIconLabel.cpp
src/AIconLabel.cpp
src/modules/hyprland/window.cpp

I noticed that some windows were displaying icons, while others weren't. I also found the gap between the icon and the window descriptor slightly excessive, and the module to be placed slightly too highly. This pull request aims to fix this.
I fixed the icon issue by matching the app descriptor with the suffix of the .desktop file, instead of the whole file name. I did this because I noticed that some applications like the terminal emulator "Foot", had "footclient" as the class name but "org.codeberg.dnkl.footclient.desktop" as the file name.
I also made it so that the search attempts to match the lowercase string version of the class name to its respective .desktop file, as well as the original. I did this because I noticed that some applications like LibreWolf had "LibreWolf" as the …

Improved hyprland/window by fixing icon search and implementing configurable spacing

---

src/modules/sway/workspaces.cpp

Filter out special output __i3 which contains scratchpad

---

.github/workflows/freebsd.yml

With the recent runner hardware upgrade[1] and support in the cross-platform-actions[2] it became possible to use a Linux runner for this workflow.
Linux-based configuration appears to be faster and stabler than macOS, so it's now recommended for use.
[1]: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
[2]: https://github.com/cross-platform-actions/action/releases/tag/v0.23.0

ci: move FreeBSD to ubuntu runners

---

src/modules/sway/workspaces.cpp

Fixes regression in bb843e0 that caused scrolling over the bar not working

Sway-Workspaces: Fixed scrolling not working

---

include/modules/mpd/state.hpp
resources/config.jsonc
src/modules/mpd/mpd.cpp
src/modules/mpd/state.cpp

mpd logs are on the second place in the list of complaints I'm getting from Fedora users, right after the missing font icons :)
So this change attempts to push all the 'no server available, business as usual' messages to debug, and add some powersaving with second precision timers (yes, these are promised to be more power-efficient due to being grouped and fired all at once internally).

mpd: less aggressive logging and reconnections

---

README.md
include/modules/power_profiles_daemon.hpp
man/waybar-power-profiles-daemon.5.scd
meson.build
resources/config.jsonc
resources/style.css
src/factory.cpp
src/modules/power_profiles_daemon.cpp

We introduce a module in charge to display and toggle on click the power profiles via power-profiles-daemon.
https://gitlab.freedesktop.org/upower/power-profiles-daemon
This daemon is pretty widespread. It's the component used by Gnome and KDE to manage the power profiles. The power management daemon is a pretty important software component for laptops and other battery-powered devices.
We're using the daemon DBus interface to:
- Fetch the available power profiles.
- Track the active power profile.
- Change the active power profile.
The original author recently gave up maintenance on the project. The Upower group took over the maintenance burden… …and created a new DBus name for the project. The old name is still advertised for now. We use the old name for compatibility sake: most …

Introduce a power-profiles-daemon module

---

man/waybar-backlight.5.scd
man/waybar-battery.5.scd
man/waybar-bluetooth.5.scd
man/waybar-cpu.5.scd
man/waybar-custom.5.scd
man/waybar-disk.5.scd
man/waybar-hyprland-submap.5.scd
man/waybar-idle-inhibitor.5.scd
man/waybar-inhibitor.5.scd
man/waybar-jack.5.scd
man/waybar-memory.5.scd
man/waybar-mpd.5.scd
man/waybar-mpris.5.scd
man/waybar-network.5.scd
man/waybar-pulseaudio.5.scd
man/waybar-river-layout.5.scd
man/waybar-river-mode.5.scd
man/waybar-river-window.5.scd
man/waybar-sndio.5.scd
man/waybar-sway-mode.5.scd
man/waybar-sway-window.5.scd
man/waybar-temperature.5.scd
man/waybar-wireplumber.5.scd
src/ALabel.cpp

This is PR adds the option to specify a "justify" field for aligning text modules. It should be either "left", "right" or "center".
This is especially useful for centering the text in labels on vertical bars. In situations like this:
`"format": "{icon}\n{value}%",`
This kind of fix was already mentioned in #366, however it was never implemented, so here's my take on it.
An example config for this:
```
"memory": {
"format": "\n{}%", // That's a character for a RAM module in the font I'm using.
"justify": "center",
},
```

Add justify config option for Labels

---

src/modules/power_profiles_daemon.cpp

The bus error when the daemon is not reachable prevents the initial update and keeps the module visible, as an empty section on the bar.
Do the update explicitly before connecting to set initial visibility.
While we at it, remove a couple of redundant `update()` calls.

fix(power-profiles-daemon): correctly set initial visibility

---

src/modules/dwl/tags.cpp

fix: #3014
After disabling a monitor using wlr-randr,waybar destroys the monitor-associated Tag object, but does not remove the monitor-associated event listener.
when use wlr-randr enable the monitor again ,the old listener still listening .
when dwl makes a set_tag request to the monitor and waybar will tries to use the Tag resource that has been freed.

fix:dwl tag crash when use wlr-randr enable monitor

---

include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspaces.cpp

Adds the css class `onThisMonitor`. 
This will make it possible to only style the waybar that a workspace is on.
Example:
```css
#workspaces .onThisMonitor {
color:blue;
}
/* waybar of monitor 1 with workspace A open:   [    A       B    ]
*                                                  blue   white
*
* waybar of monitor 2 with workspace B open:   [    A       B    ]
*                                                 white    blue
*/
```
Closes #2959

Hyprland workspaces `hosting-monitor` css class

---

src/modules/sway/workspaces.cpp

Fix peristent class on buttons

---

src/modules/wlr/taskbar.cpp

fix(wlr/taskbar): crash on taskbar drag and drop event

---

include/modules/wireplumber.hpp
meson.build
src/modules/wireplumber.cpp

Wireplumber 0.5 has an incompatible API. This is a first WIP crack at updating. Would fix #2873 (but should not be merged currently).
Two current problems:
- Ignores the results of the two setup calls changed which are now async.
- Doesn't actually seem to work, adding extra logging shows that volume is not actually returned.
However it does build at least... I don't know the WP API well enough to add much more.
[EDIT]: As below now updated to use the new async API and working, ready for review.

Update Wireplumber API to 0.5

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

Allows styling empty workspaces in Sway. While it is possible to do this using persistent tags, I feel like it may be a little confusing as persistent workspaces don't have to be empty. Thanks for reviewing!

Add empty workspace style for Sway

---

include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspaces.cpp

Option `move-to-monitor`:
Use `hyprctl dispatch focusworkspaceoncurrentmonitor` when clicking on workspace button
Option `active-per-monitor`:
Each bar on each monitor has its own active workspace. So instead of all the bars showing the same workspace which is currently active, each show the currently active workspace of the bar's monitor.
This may require additional testing. Also I hope this doesn't break backwards compatibility, especially with special workspaces. I didn't test, but it should be fine as I didn't change anything special workspace related.

[hyprland/workspaces] New options to change on click behaviour and active workspace status

---

include/util/backlight_backend.hpp
src/util/backlight_backend.cpp

Doesn't look like there was any use for being so generic. This fixes linking of the best_device() function with 'mold' linker.
I didn't test if the backlight module still works fine - I don't have a device that supports it in easy availability, but I didn't touch any functionality either.
Fixes error `mold: error: undefined symbol: waybar::util::BacklightDevice const* waybar::util::BacklightBackend::best_device<__gnu_cxx::__normal_iterator<waybar::util::BacklightDevice const*, std::vector<waybar::util::BacklightDevice, std::allocator<waybar::util::BacklightDevice> > > >(__gnu_cxx::__normal_iterator<waybar::util::BacklightDevice const*, std::vector<waybar::util::BacklightDevice, std::allocator<waybar::util::BacklightDevice> > >, __gnu_cxx::__normal_iterator<waybar::util::BacklightDevice …

refactor(backlight): use concrete types for some helper functions

---

include/modules/upower/upower.hpp
src/modules/upower/upower.cpp

Add CSS class based on the 'warning_level' field reported by UPower over D-Bus.  This makes it possible to add custom styling when the battery is near empty.
Example:
``` css
#upower {
background-color: #24283b;
color: #9ece6a;
}
#upower.low {
background-color: #f7768e;
color: #24283b;
}
@keyframes blink {
to {
background-color: #24283b;
}
}
#upower.critical {
background-color: #f7768e;
color: #24283b;
animation-name: blink;
animation-duration: 0.5s;
animation-timing-function: steps(12);
animation-iteration-count: infinite;
animation-direction: alternate;
}
```
Additionally, fixed some potential uninitialized reads.

Upower warning level

---

include/modules/clock.hpp
src/modules/clock.cpp

The functionality of being able to invert the month scrolling in the calendar by setting "on-scroll" to -1 appears to  have been broken in 86a3898.
This restores the ability to set the number of months that the scroll wheel scrolls, including negative numbers, as documented in the wiki https://github.com/Alexays/Waybar/wiki/Module:-Clock

Fix clock on-scroll value not being used for calendar

---

src/config.cpp

Fully clear the configuration before reloading, so that when the config is read and merged in there are no existing values which mergeConfig refuses to overwrite.

Fix reloading config

---

flake.lock
nix/default.nix

Current waybar from nixpkgs uses wireplumber 0.4, this updates the override to use wireplumber 0.5 instead.

nix: build against wireplumber 0.5

---

src/bar.cpp

fix for #2685 
During the strings conversion in `setupAltFormatKeyForModuleList` for the modules left/center/right, we need to check for group modules and iterate their array to add alt-format support to their modules as well.

(Fix) Alt format on group modules

---

src/modules/sway/workspaces.cpp

This fix is necessary to correctly apply the `#workspaces button.visible` style to all visible workspaces. This includes cases where workspaces are empty but still visible on the screen. This issue was introduced in #2944, which changes `ipc_.sendCmd(IPC_GET_WORKSPACES)` to `ipc_.sendCmd(IPC_GET_TREE)`. Therefore, the logic should be adjusted to handle the new IPC response correctly.

fix(sway/workspaces): Visible class doesn't work on visible and empty workspaces

---

src/modules/sway/workspaces.cpp

Floating nodes are not taken into account for visible and empty workspaces.
And fix focused icon (#3095)

fix(sway/workspaces): floating_nodes and focused icon

---

src/modules/wlr/taskbar.cpp

Files in home directory should take precedence system directories so search them first

taskbar: search user directories first for desktop files

---

man/waybar-styles.5.scd.in
man/waybar.5.scd.in
meson.build

waybar(5) describes the configuration syntax but doesn't mention how the stylesheets are handled.
This documentation would have been helpful to me as i figured out how to configure waybar.

Add waybar-styles(5) manual page

---

src/util/pipewire/pipewire_backend.cpp

Fixes #3047.
I haven't encountered any issues since adopting these locks. Calling https://github.com/hrdl-github/Waybar/blob/74773885c6166d190a294ad945b1f1d4d5f007ec/src/util/pipewire/pipewire_backend.cpp#L81 without locking causes the warning described in https://github.com/Alexays/Waybar/issues/3047#issue-2196726500. I am less certain whether the lock in the constructor is required.

Pipewire backend: use pipewire thread lock

---

src/modules/sway/workspaces.cpp

I'd expect the compiler to generate a warning for this, but apparently it didn't.

Remove unused variable in Workspaces::updateWindows

---

include/modules/clock.hpp
src/modules/clock.cpp

Added `shift_reset` action to the calendar in the clock module. This is handy, when you go back a couple of months and want to jump back to current date.

calendar: add shift_reset action

---

src/modules/hyprland/workspaces.cpp

- Update active workspace on worskpace moved. Fixes #3121 
- It should also cover #3074 . This PR solution is simpler than #3074 
- Don't update window count and sort workspace during init but AFTER their creation. It did nothing during init because the objects did not exist yet. It fixes a problem I had when configuring waybar where I launched it with already opened windows. This bug was not usually encountered because waybar usually starts with hyprland when there are no windows yet.

Fixes for hyprland/workspaces

---

include/modules/battery.hpp
man/waybar-battery.5.scd
src/modules/battery.cpp

This PR adds the following format replacements to the `battery` module (currently for Linux only):
Currently, both of the new format replacements select the battery candidate with the highest `charge_full_design`. This seemed the most intuitive for `{cycles}`, and I have applied the same logic to `{health}` to stay consistent with this. Should multiple batteries have the same `charge_full_design`, the "worse" value (i.e. higher cycle count, lower health percentage) is displayed.
However, I could also imagine using a `charge_full_design` weighted average of all eligible batteries' percentages for `{health}`, so it could represent the health of a full battery array.

battery: Add {cycles}, {health} format replacements

---

src/modules/sway/workspaces.cpp

Fixes #1496.
Scrolling works in `sway/workspaces` only if the focused monitor is shown in the bar. This PR uses the visible monitor if the focused monitor is not in the bar.

sway/workspaces: Fix scroll on unfocused monitor

---

include/AModule.hpp
man/waybar-styles.5.scd.in
resources/style.css
src/AModule.cpp

A second attempt at implementing hover for all modules in a much less intrusive way.
See https://github.com/Alexays/Waybar/pull/3139 also (the more naive implementation which I found a similar approach had been tried and reverted).
Let me know if any additional documentation is required to get this merged. Alternatively, I think this could just be merged directly exposing the functionality for the super users immediately and then improved upon later on.

feat(#2989): (optional) hover for all modules

---

src/modules/clock.cpp

Currently the tooltip is updated only if a placeholder (like `calendar`, `tz_list`, `ordinal_date`) is present, because the formatting string `tlpFmt_` is taken as reference, while if no placeholder is present, the tooltip will get the text formatted processed at the first time, then it will never be updated. To ensure that the tooltip will update in this scenario, we can set the tooltip string back as the formatting string, before the formatting occurs.
Here is the config to test it:
```
"clock": {
"tooltip-format": "{:%H:%M %Y-%m-%d}",
"format": "{:%H:%M %Y-%m-%d}",
}
```

fix: update clock tooltip without placeholders

---

src/modules/battery.cpp

Looks like I forgot to register the `{health}` replacement for the "default" (i.e. non-tooltip) replacements.
Also, some batteries report their `{health}` related data as `energy_full` and `energy_full_design` instead of `charge_full` and `charge_full_design`. This PR ~~will~~ also implements support for that.
For more information see the conversation below #3130 
---
~~Marking as draft since~~
- ~~I haven't tested this yet (quick commit from the web editor)~~
- ~~there might actually be another / more issue(s) with `{cycles}` and `{health}` in `format-alt`~~
Issues reported by @nebulosa2007 under the original PR for `{cycles}` and `{health}` (#3130)

fix(battery): Fix `{health}` format replacement

---

include/modules/upower/upower.hpp

fixes bd8b215416cdca6ed0c929c18cede7dfb907edf0

upower: fix segfault by initializing lastWarningLevel

---

src/AModule.cpp

looks like a small oopsie in recent merge

fix: set cursor appropriately on user event hover

---

flake.nix

Because last time I "fixed" it, I actually broke it, I forgot a line, but this time I changed other minor stuff (added `waybar`-named overlay and package, in addition to `default`, and the package output now is properly inherited from the overlay applied on top of Nixpkgs).

Nix Flake: Fix overlay (again)

---

resources/custom_modules/mediaplayer.py

fix custom module mediaplayer which doesn't consider  --exclude argument on player appear
previously player excluded by --exclude or -x argument started after `mediaplayer.py` wont be ignored
this commit fixed it

fix: custom module mediaplayer doesn't respect argument

---

flake.nix

#3196 made some changes to `flake.nix`. In [this line](https://github.com/Alexays/Waybar/blob/231d6972d7a023e9358ab7deda509baac49006cb/flake.nix#L67) flake's `waybar` package was defined to be the one in `nixpkgs` because the function that was passed to `genSystems` argument was called with `nixpkgs` without the flake's overlay applied. I changed the `genSystems` function to pass `nixpkgs` that uses the flake's overlay so the package comes from the flake itself and not `nixpkgs`.

flake: fix overlay not actually being applied

---

include/modules/sni/item.hpp
src/modules/sni/item.cpp

WE WANT HOVER! :laughing: 
```
#tray > .active {
opacity: 1;
}
#tray > .active:hover {
opacity: 0.5;
}
```

feat(#3182): style tray icon on hover

---

include/group.hpp
src/group.cpp

Adds hover targeting for the whole group.
Not a great gif to demonstrate the fix, but without the patch, there's a transparent background instead of black.
```
#power {
background-color: transparent;
color: white;
}
#power *:hover {
background-color: white;
color: black;
}
#power:hover {
background-color: black;
color: white;
}
```
```
"group/power": {
"orientation": "inherit",
"drawer": {
"transition-duration": 500,
"children-class": "not-power",
"transition-left-to-right": false,
},
"modules": [
"custom/lock",
"custom/quit",
"custom/suspend",
"custom/reboot",
],
},
```
```
widget:dir(ltr)
box#power.horizontal:dir(ltr)
revealer.drawer:dir(ltr)
box.horizontal:dir(ltr)
widget.not-power:dir(ltr)
label#custom-quit.module:dir(ltr)
widget.not-power:dir(ltr)
label#custom-suspend.module:dir(ltr) …
```

feat(#3174): hover for whole group

---

include/modules/dwl/window.hpp
src/modules/dwl/window.cpp

The module was crashing when the output has been deactivated through `wlr-randr --output DP-1 --off` , for example. The module object was destroyed, but the listener was still called, resulting in a NPE.

Remove listener when the window is destroyed

---

src/modules/hyprland/language.cpp

Based on the proposal by @s1syph0s (https://github.com/Alexays/Waybar/issues/2137#issuecomment-1890935492)
Should fix #2137 and #3222. Looking at https://wiki.hyprland.org/IPC/#events-list, `activelayout` has the parameters `KEYBOARDNAME,LAYOUTNAME`, so `find_last_of` should be more appropriate.
@dxrknesss @xadips Can you guys test this with your keyboard?

Fix hyprland/language events not working with keyboard names with commas in them

---

src/modules/upower.cpp

If a UPower device (such as a wireless mouse/keyboard) is removed `UPower::getUpDeviceInfo()` will succeeded, but the struct will be filled with null values, and then the `std::strcmp` will fail! A simple nullptr check will avoid this.

Do not try to strcmp a variable that may be a null-pointer

---

src/modules/cava.cpp

Hi @Alexays , this MR solves #3276 . The problem here: user's environment can miss $XDG_CONFIG_HOME variable. cava module had never validate that.

Cava. $XDG_CONFIG_HOME validation

---

src/modules/hyprland/backend.cpp

IPC messages are parsed in a dedicated thread, and the thread terminates when an exception is not caught, which causes the waybar process to crash with SIGABORT.
While this issue might be related to Hyprland, it is really annoying to see waybar crash. It would be better to catch those exceptions and report errors instead of crashing.

(hyprland) fix crash when failed to parse IPC message

---

Dockerfiles/debian

I investigated the issues with the clang-tidy action getting stuck when installing clang-tidy and clang-format. Apparently there's an issue in the current version of the `waybar:debian` image where any `apt install` command gets stuck. 
After updating the dockerfile to install the newer `libwireplumber-0.5-dev` package instead of `0.4`, apt works again.
Here's more info: https://github.com/cpp-linter/cpp-linter-action/issues/239

Fix debian dockerfile

---

man/waybar-temperature.5.scd
src/modules/temperature.cpp

Currently, only `hwmon-path` is allowed to have multiple path, however the hwmon ID is not stable, for which `hwmon-path-abs` is better, but it's supposed to be a string. This commit extends `hwmon-path-abs` and make it works like `hwmon-path`.

temperature: allow hwmon-path-abs as array

---

.clang-tidy
include/modules/privacy/privacy.hpp
include/modules/privacy/privacy_item.hpp
src/modules/privacy/privacy.cpp
src/modules/privacy/privacy_item.cpp

Two commits: 
* Temporarily removed the case style hints from clang-tidy because otherwise the repo is full of warnings
* clang-tidy fixes in the privacy module code, also fixes a compilation warning I've seen often (line 120 in privacy.cpp: potential uninitialized use of booleans, as not all compilers will initialize booleans by default)

clang-tidy fixes in the privacy module

---

include/modules/clock.hpp
src/modules/clock.cpp

Hi @Alexays, @FilippoBonazziSUSE this MR solves #2240 
Actually here it's GtkLabel wrong behavior with tooltips. Even @BrianCArnold has found workaround it's better to have code fixed. 
Temporary for now I replaced clock label with Gtk::TextView.  In order to have the same styling as it was for tooltips in the system, users should use next css styling
```css
textview#clock.tooltip, textview#clock.tooltip text {
background-color: inherit;
padding: inherit;
}
```
For now I'm trying to write test case in pure C in order to provide it gtk maintainers to fix gtk
So fixed variant looks good

Fix Clock. Tooltip calendar text overflows(#2240)

---

.github/workflows/docker.yml
Dockerfiles/debian

Initial test of a new GitHub action that will build and push all docker images in the Dockerfiles folder.
This will ensure all Dockerfiles are always up to date, avoiding issues like what's described in #3258

Add GitHub action for nightly Docker image building 

---

include/bar.hpp
src/bar.cpp

It fixes https://github.com/Alexays/Waybar/issues/3211
I think I found a bug in gtk-layer-shell, but it can be worked around by not changing bar's layer when hiding it.

fix(#3211) change layer for mode invisible to nullopt

---

.github/workflows/nix-tests.yml
.github/workflows/nix-update-flake-lock.yml

This PR adds two workflows:
1. `nix-tests` - checks nix files, builds the package, on every push and PR
2. `nix-update-flake-lock` - update dependencies of nix flake, runs once a month
`nix-update-flake-lock` creates a pull request updating flake.lock file when run.
Samples:-  [Nix-tests](https://github.com/Alexays/Waybar/actions/runs/9265649908/job/25488188870?pr=3306), [Update-flake-lock](https://github.com/JohnRTitor/Waybar/actions/runs/9265625759)

workflows: add nix workflows

---

src/modules/hyprland/backend.cpp

Was hardcoded to /tmp in previous versions
Resolves: https://github.com/Alexays/Waybar/issues/3280 #3287

modules/hyprland/backend: use /tmp

---

.github/workflows/freebsd.yml
.github/workflows/linux.yml
Makefile
src/modules/temperature.cpp

- Looks like we reference std::ranges and dont need this. It's breaking freebsd build. 
Documentation seemed a little confusing on the temperature paths thing... took some trial and error to figure out what it needed to be parsed properly.
Tested with 
```json
"hwmon-path-abs": [
"/sys/devices/pci0000:00/0000:00:18.3/hwmon/"
],
"input-filename": "temp3_input",
```
and 
```json
"hwmon-path-abs": "/sys/devices/pci0000:00/0000:00:18.3/hwmon",
"input-filename": "temp3_input",
```

treewide: meson deprecation and freebsd fixes

---

include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspace.cpp
src/modules/hyprland/workspaces.cpp

If `special-visible-only` is set, special workspaces will be shown only if visible, they'll be hidden if they're not visible.

Hyprland/Workspaces: Added option to hide non-visible special workspaces

---

.github/workflows/docker.yml
Dockerfiles/fedora

* Fix fedora image (https://github.com/Alexays/Waybar/actions/runs/9294824170/job/25580709676#step:4:197)
* Fix docker build failing when another build fails
I haven't been able to fix the opensuse build yet, here's the error:
```
╰─ docker build -f opensuse .
[+] Building 13.0s (5/5) FINISHED                                                                                                                                             docker:default
=> [internal] load build definition from opensuse                                                                                                                                      0.0s
=> => transferring dockerfile: 647B …
```

Fix docker image build github action

---

src/modules/wlr/taskbar.cpp

fixes taskbar `empty` class not being applied on taskbar empty when last not ignored application closes:
before: taskbar isn't transparent on empty (empty class is not applied when brave closes)
https://github.com/Alexays/Waybar/assets/66728045/9e21d3a5-2165-4410-bc30-39ca93c33a22
based on https://github.com/Alexays/Waybar/issues/2564

fix: taskbar not applying empty class on empty

---

src/modules/sway/workspaces.cpp

The `current-only` workspace setting should display only the active workspace name as determined by its `focused` attribute.  However, according to the `get_tree` output, workspaces that contain a focused window will report `"focused": false` and the window will report `"focused": true.` In this case, Waybar will not display a workspace name at all.
This change updates the logic for determining if a workspace is focused by also looking for a focused window.

sway/workspaces: Correct behavior when "current-only" is set

---

src/modules/privacy/privacy.cpp

Along with the local clang-tidy warning fixes
This fix privacy module being visible even with no corresponding modules included.
For example, with modules = ["screenshare", "audio-in"], so long as "audio-out" is in use, the modules would be visible even with nothing in it. The box itself may use extra space in the bar, which can be avoided.

fix privacy: consider only configured modules

---

man/waybar-pulseaudio.5.scd
src/modules/pulseaudio.cpp

This PR enables users to specify alternate pulseaudio icons for when a sink is muted. 
For example, adding a `headphone-muted` entry into a `format-icons` object will use the corresponding icon when the current sink is a headphone port and is muted.
Users can also specify `[current_sink_name]-muted`, `[port]-muted` or `default-muted` icons
When not muted, behavior is unchanged.
When muted, icons are searched for in the following order:
- `[current_sink_name]-muted`
- `[current_sink_name]` _(Existing behavior)_
- `[default_source_name]` _(Existing behavior)_
- `[port]-muted`
- `[port]` _(Existing behavior)_
- `default-muted`
- `default` _(Existing behavior)_
Feedback welcome, this is the least intrusive way I thought of to include this feature that I wanted personally.
```
"pulseaudio": { …
```

Support for muted icons for pulseaudio devices/ports

---

include/modules/bluetooth.hpp
src/modules/bluetooth.cpp

This pull requests adds hotplug detection for bluetooth controllers. This fixes #1655 and also allows detection of e. g. hot plugged USB bluetooth adapters.
When no bt controller is currently monitored, it will select the next illegible (correct alias if configured) bt controller that will be connected to the system. In case the currently monitored bt controller gets removed, it will look for other bt controllers illegible for monitoring.

Add hotplug detection of bluetooth controllers

---

src/modules/bluetooth.cpp

I think I forgot two edge cases in my previous pull request that can both be triggered on a system with multiple bluetooth controllers present.
The first issue is that `bt->cur_controller_.has_value()` isn’t being checked in `onObjectRemoved()`, which leads to a failed assertion if a bluetooth controller is removed from the system while no controller was currently displayed by waybar.
The second issue is that the list of connected devices isn’t being updated when switching the displayed controller in `onObjectRemoved()`.
Unfortunately due to a lack of multiple bluetooth controllers I can’t test if the bugs are actually triggerable or if this pull request fixes it. I’m quite confident in both, but I’ll try to get my hands on a usb bluetooth dongle next week in order to test it.

Fix device list not being updated on selecting new bluetooth controller

---

src/modules/battery.cpp

Closes #3293
The current code for battery calculation seems to assume that the `capacity` value returns the non-design battery capacity. This is not the case, and it instead returns the design capacity of the battery.
Currently, the `capacity` value is used above all other methods if it is present in the /sys directory of the battery. This means that the design capacity of the battery will always be displayed regardless of the `design-capacity` configuration option.
To remedy this issue, I have restructured the code so that the `capacity` value is only used if the other possible options for calculation have been exhausted beforehand.
This screenshot shows two instances Waybar while the battery is plugged in at full capacity. The top instance is the current release version, and the bottom …

modules/battery: Deprioritize `capacity` /sys value for battery calculation if other methods are available

---

include/modules/hyprland/workspaces.hpp
src/modules/hyprland/backend.cpp
src/modules/hyprland/submap.cpp
src/modules/hyprland/windowcreationpayload.cpp
src/modules/hyprland/workspace.cpp
src/modules/hyprland/workspaces.cpp
test/hyprland/backend.cpp
test/hyprland/fixtures/IPCTestFixture.hpp

Issues:
- Resolves https://github.com/Alexays/Waybar/issues/3388 
- Resolves https://github.com/Alexays/Waybar/issues/3365
This PR: 
- We will check for an empty response from getSocketReply before trying to parse JSON. Before the empty response check we get the JSON parse error from the JSON module. After the change, we wont try and parse the message that will cause the crash.
- Also includes some clangd cleanup. 
- Added test to verify we dont crash when we receive an empty socket response.

modules/hyprland/backend: handle empty socket response 

---

man/waybar-custom.5.scd
src/modules/custom.cpp

Resolves #3341
Custom module hides empty output, e.g. when a worker returns `{}` as json. But when using other content in the format, e.g. to add an icon before or after output, it's no longer possible to have the module hidden.
This PR addresses this by adding a config option `hide-empty-text`, when true, `text_` is checked for empty rather than `str`.
I realise I forgot the manpage, coming up in a second :P

add hide-empty-text option to hide module whenever output is empty but format is not

---

src/modules/wlr/taskbar.cpp

This is a workaround for #3366 .
Using gdb, I can see that `handle_app_id` can sometimes run when `tbar_->icon_themes()` has 0 elements. This happens in multi output settings and can result in empty icons for apps that have been started before waybar.
It looks to me that the Tasks can be present before `Taskbar::Taskbar` has run, I could also confirm this by temporarily setting a bool flag in the constructor. If anyone can, I would appreciate any more detailed explanation why that is even possible, because I don't understand it at all.
With an explanation there's probably better ways to do this. :) But the code in this PR addresses this by setting the app_ids for all of the taskbar's tasks again at the end of Taskbar's constructor, leading to another icon lookup with `icon_themes()` …

workaround for icons not rendered for apps existing before waybar launch

---

include/modules/power_profiles_daemon.hpp

When building the master branch on Ubuntu 22.04 I encountered a build error both with g++ 11 and clang 14. Essentially the compiler can not find a constructor for the `Profile` class in `src/modules/power_profiles_daemon`. I think c++ 20 should create a default constructor with a parameter list but that seems to not have happened even though g++11 and clang 14 should be (at least partially) c++20-capable. The error is as follows:
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/alloc_traits.h:518:4: error: no matching function for call to 'construct_at'
std::construct_at(__p, std::forward<_Args>(__args)...);
^~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/vector.tcc:117:21: note: in instantiation of function template …
```

Fix build error on Ubuntu 22.04

---

src/modules/hyprland/language.cpp

As I found out myself in #2072 and others have noted is baffling to figure out why some things are not matching or what to enter in a config to match the right keyboard language/layout/variant combo. This debug information helped clarify what was going wrong for my case (not fix it, just point to the problem) after being baffled for a long time and having tried a lot of stabbing in the dark.

Add keyboard debug info to hyprland language module

---

include/modules/upower.hpp
man/waybar-upower.5.scd
src/modules/upower.cpp

This is useful for wireless HID devices, as they often do not have the same `native-path` when re-connected.

Add config option to select UPower device based on device model.

---

man/waybar-pulseaudio-slider.5.scd

From #3373 : config example provided in man page does not work. This fixes it.

fix example in manpage for pulseaudio/slider

---

resources/custom_modules/mediaplayer.py

if title has a & in the name then the program will fail to set text due to error parsing markup, this fixes this

fix: display titles with '&' correctly 

---

man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspace.cpp

I'd like to ignore some windows from having icons or empty space taken on the bar. By filtering out empty repr we can supply rewrite rules that will ignore them from being processed and showing an empty space or default icon.

modules/hyprland/workspace: ignore empty window-rewrite

---

include/util/date.hpp
include/util/format.hpp
src/client.cpp

Since fmt 11.0.0, formatter:format() is required to be const.Mark affected functions as const to stay compatible with fmt 11.

Fix build with fmt11

---

README.md

Receiving this warning when following the instructions from the readme to build from scratch:
```txt
❯ meson build
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
Would it be better to just specify `make build` instead of `meson setup build` & `ninja -C build`?

chore: update meson build command in readme

---

include/modules/network.hpp
man/waybar-network.5.scd
src/modules/network.cpp

Adds a `bssid` field to the network module, which is useful when dealing with multiple APs

network: add bssid format replacement

---

flake.lock
src/client.cpp
src/modules/hyprland/window.cpp
src/modules/network.cpp

Gracefully handle lack of response from the IPC. If socket isn't available, we already log the IPC isn't running. We dont need to crash program just because we couldn't get responses. We can just return an empty object.
Tested this running on sway and Hyprland. No longer crashes on sway and appears to work the same on Hyprland. 
Also added some clang format and build fixes.

hyprland/window: fix crash when no return from socket

---

include/group.hpp
man/waybar.5.scd.in
src/group.cpp

resolves #3256 
Adds a config to groups revealer "click-to-reveal", which allows to reveal the hidden modules by clicking rather than mouse over.

feat/issue 3256: Toggle drawer state

---

src/util/audio_backend.cpp

If the current sink happens to be ignored it is never considered running so it will be replaced with another sink.
Otherwise if an ignored sink was set as the default sink for some reason during startup it might never get replaced even though it's supposed to be ignored.

pulseaudio: Consider ignored sinks never running

---

src/modules/hyprland/backend.cpp
test/hyprland/backend.cpp
test/hyprland/fixtures/IPCTestFixture.hpp

Allows us to disable modules entirely when socket connection isn't working. This is similar to how sway handles their socket connections disabling modules. This supports a single waybar config for multiple IPCs.
Previously, my waybar config would crash when Hyprland modules were in the same config when I was running under sway. In a recent PR I allowed empty responses to not crash the program. Now, I'm throwing runtime_errors when socket doesn't exist so the factory can disable the module in a similar way to the sway module. Now, a single config works properly when you have both hyprland and sway modules declared.

hyprland: disable modules instead of rendering empty

---

man/waybar-styles.5.scd.in
src/AModule.cpp

Seen a lot of discussion activity around this again... resurrecting the PR https://github.com/Alexays/Waybar/pull/3274 that resolves https://github.com/Alexays/Waybar/issues/3239. Follow up to work done in https://github.com/Alexays/Waybar/pull/3108 to make this opt in instead of always forced on users. 
One thing that might be nice is to set a global option for this... but I didn't see a way of doing that easily, atm.

AModule: Cursor config option

---

include/bar.hpp
src/bar.cpp

Accidentally removed updating the visible variable
Resolves https://github.com/Alexays/Waybar/issues/3455
Verified sending signal works with this update, and previous version doesn't toggle.

bar: fix setVisible

---

src/util/css_reload_helper.cpp

"reload_style_on_change" would check if the target file is a symlink, but only resolves the first link. If the symlink is acutally a chain of symlinks, such as what happens with NixOS's `mkOutOfStoreSymlink,` we will not find the actual file style file.
Updated the symlink resolution logic to walk down the symlink chain until it finds a non-symlink. Also check against a the original filename (which may be a symlink) to guard against infinitely looping on a circular symlink chain.

Walk up Symlink Chain

---

src/modules/clock.cpp

Fixes #3414
Right now, for the tooltip, all times are shifted if shift-down/shift-up actions are used. But it really only makes sense for this to apply to the {calendar} replacement, so use `shiftedNow` there and `now` for all the rest.
Because of this I didn't consider a config option. Should anyone miss the old (I'm inclined to say broken) behaviour, I'm happy to add one in the future. ;)

Issue #3414/clock: Shift ONLY calendar

---

include/group.hpp
src/group.cpp
src/util/css_reload_helper.cpp

Resolves https://github.com/Alexays/Waybar/issues/3391 . 
Finally spent some time on this. This changes the handleMouseLeave event to only fire when we leave the entire event_box__ and are not just going to a child element.

group: fix revealer hover regression

---

src/modules/cpu_usage/common.cpp
src/modules/cpu_usage/linux.cpp

First of all in case when the number CPUs change
prevent out-of-bound index access in
waybar::modules::CpuUsage::getCpuUsage()
Secondly on Linux when updating CPU usage
read /sys/devices/system/cpu/present
and use it to detect the offline CPUs missing from /proc/stat
For offline CPUs report 0 usage and "offline" in the tooltip
Fixes issue #3498
On Linux one can test this functionality with:
echo 0 > /sys/devices/system/cpu/cpu1/online
echo 1 > /sys/devices/system/cpu/cpu1/online
On non-Linux OSes I'm not sure how to detect offline CPUs, so I didn't add the offline CPU detection there
but at least CPU number change should not cause a crash there anymore or cause memory safety issues after this fix

Handle offline CPUs and CPU hotplug

---

src/modules/wireplumber.cpp

This fixes an issue on my system where for some reason the initial default node ID is incorrect and the initial node name is correct. Only afterwards there is a "default-node-changed" signal with the correct ID. However, this signal is discarded as the node name is unchanged.

Accept "default-node-changed" signals from wireplumber, even if only the node ID is changed

---

include/bar.hpp

fix crash caused by use bar instance after it is freed (use-after-free)

---

src/modules/hyprland/backend.cpp

Hyprland hasn't been using TCP sockets for IPC since the first release, so this getaddrinfo call and its result was never needed.
Additionally, it leaks the `aiRes`, causing test failure under ASan.
Not tested on a real Hyprland, but see https://github.com/hyprwm/Hyprland/commit/39a9980fb116108807ee68def27a6348184f282c.
CC: @khaneliman

hyprland/backend: drop unnecessary getaddrinfo call

---

src/modules/upower.cpp

While looping over all the upower devices, the currently set device that will be rendered in the waybar, is overridden. Since the loop doesn't end when the device is found, the upDevice_ is overridden with NULL in the iteration for the next device.
Now we only override upDevice_ if the current device matches the constraints.
Fixes d2a719d67c5427dffc3e431c41b96b60399576e6 ("Redo to minimize code duplication.") 
Fixes #3267

fix/upower: upower module selection with multiple devices

---

README.md
include/modules/niri/backend.hpp
include/modules/niri/language.hpp
include/modules/niri/window.hpp
include/modules/niri/workspaces.hpp
man/waybar-niri-language.5.scd
man/waybar-niri-window.5.scd
man/waybar-niri-workspaces.5.scd
man/waybar.5.scd.in
meson.build
meson_options.txt
src/factory.cpp
src/modules/image.cpp
src/modules/niri/backend.cpp
src/modules/niri/language.cpp
src/modules/niri/window.cpp
src/modules/niri/workspaces.cpp
src/modules/sni/item.cpp
subprojects/gtk-layer-shell.wrap

I am working on an [event stream IPC](https://github.com/YaLTeR/niri/pull/453) for the [niri](https://github.com/YaLTeR/niri) Wayland compositor, which is intended for bar modules and the like. To test out the design, I implemented Waybar modules for workspaces, focused window and language.
This PR is a Draft until I merge the niri PR (in a few days).
I followed the existing modules for Sway and Hyprland in my niri implementation, though with some differences.
Unlike Sway and Hyprland, the niri event stream IPC starts by sending the complete current state, so Waybar doesn't need to query it from other IPC calls. This, however, makes it more convenient to track the state in the IPC class directly, so that modules registering after the initial event burst can still access the current state. …

Add niri/workspaces, niri/window, niri/language

---

src/modules/sni/item.cpp
subprojects/fmt.wrap

fmt 11.0.1 was broken: it wasn't using our `Glib::ustring` formatter. This has been fixed long time ago in 11.0.2 and shouldn't be worked around in the code.
Reverted the changes and updated fmt wrap to 11.0.2.
11.0.2 can trigger `-Wstringop-overflow` warnings with gcc -O3; these are known false positives and will be addressed in the next release of fmt.
Fixes #3597

Fix `std::bad_cast`s in tray module

---

src/AAppIconLabel.cpp

If an app's identifier is an absolute path, return said path. This is for apps like `tidal-hifi` that identify itself as `/usr/share/icons/tidal-hifi/tidal-hifi.png`. Closes #3612

fix: return app_identifier as itself in AAppIconLabel if it's an absolute path

---

flake.lock
include/bar.hpp
meson.build
src/bar.cpp

Fixes #3211
Fixes #3512 (and a dozen other issues about `overlay` mode not being on top of fullscreen windows)
@VlctM, @7ff04da4aa6ac37197e249299066ac30, @srprca, I'd appreciate if you could test this PR.

Fixes for Sway modes and wlr_scene support

---

man/waybar-custom.5.scd
resources/config.jsonc
src/modules/custom.cpp

The current documentation for the custom module suggests mixing manual (`{icon}`) and automatic (`{}`) indexing of format args. Newer versions of the fmt library seem to not support this anymore (see issue #3605).
This commit introduces a name for the `text` output of the script, so that `{text}` can now be used instead of `{}` in the configuration. The documentation in the wiki should be updated upon rolling out this change.
An alternative way would be to just replace `{}` with `{0}` in the documentation, then this pull request wouldn’t be required.

fix(custom): stop mixing manual and automatic arg indexing

---

include/modules/cava.hpp
man/waybar-cava.5.scd
src/modules/cava.cpp

This PR adds `format_silent` config option; `updated` and `silent` css triggers.
- If `format_silent` is set and `hide_on_silence` is set to false and audio has not been playing for `sleep_timer` seconds, then cava module will be showing `format_silent` string until audio starts playing.
- `#cava.updated` triggers when a new frame is shown
- `#cava.silent` triggers when there has been no audio for `sleep_timer` seconds
When this PR gets merged, I will write documentation for these options
@Alexays if there is anything wrong with this PR, please point it out

cava: Add format_silent option and css triggers

---

nix/default.nix

Tested by add it to my nixos config.
The patches is the modification of downstream, it should not affect upstream. Any changes of upstream would caused patch fail. 
There are few person to maintain nix here I guess since the conflict has been existed for 1 week(from last time the flake.lock update), so I keep use overrideAttrs from nixpkgs in order to reduce the need of maintain.
Close #3639.

nix: remove patches from downstream

---

.github/workflows/docker.yml
.github/workflows/nix-update-flake-lock.yml

Limits the scheduled build and push and flake update CI to not run on forks since they just create failure noise.

.github/workflows: don't run on forks

---

nix/default.nix

Follow up to https://github.com/Alexays/Waybar/pull/3646, fixes the nix flake build.

nix/default: cava bump

---

.github/workflows/nix-update-flake-lock.yml

Follow up to https://github.com/Alexays/Waybar/pull/3651 since it sounded like https://github.com/Alexays/Waybar/pull/3651#discussion_r1779728761 some contributors find it useful to run it in their forks

.github/workflows: allow forks to manually run flake lock update

---

man/waybar-backlight.5.scd
src/modules/backlight.cpp

As currently it is possible to turn the brightness to zero which may not be desirable, this patch add a configurable brightness check.

#2275  Backlight: Add minimum brightness

---

src/main.cpp
src/modules/hyprland/backend.cpp

The waybar process does not exit instantaneously.
Signals may be received after main has started freeing resources.
When a worker thread is in `fgets` this time window can last forever (until Hyprland writes to the socket).
An easy way to duplicate the crash is pressing ^C twice with a Hyprland module waiting on socket2.
Thread 1 "waybar" received signal SIGSEGV, Segmentation fault.
spdlog::sinks::sink::should_log (this=0x5f620b542ca5,
msg_level=spdlog::level::info)
at /usr/src/debug/spdlog/spdlog-1.14.1/include/spdlog/sinks/sink-inl.h:13
13	  return msg_level >= level_.load(std::memory_order_relaxed);
(gdb) p $_siginfo._sifields._sigfault.si_addr
$1 = (void *) 0x5f620b542cad
`Workspaces::*` and `IPC::startIPC` may both call `getSocketFolder` at the same time and are racing for the same …

Fix a crash after handling SIGINT and a data race when initializing the Hyprland workspace modules

---

man/waybar.5.scd.in

I could only find information on how to toggle the bar in a GitHub issue/discussion, so I added the signals that Waybar accepts in the manpage

Add signals section to manpage

---

src/modules/hyprland/window.cpp

Both flags are wrong, because:
- the active group member can be fullscreened.
- technically, a grouped window can be solo as well, because only the active group member is shown, the other members are hidden. Also, you can have a group consisting of only one member.
Fixes https://github.com/Alexays/Waybar/issues/3746

fix hyprland's grouped window flags

---

src/util/pipewire/pipewire_backend.cpp

This would cause Waybar to crash if the privacy module ever got e.g. a empty (but properly null-terminated) string for the application_name.

fix null-deref due to unconstructed PrivacyNodeInfo

---

include/modules/network.hpp
src/modules/network.cpp

I often switch between networks that use either IPv4 or IPv6.
As the network module supports IPv4 _or_ IPv6 (but not both at the same time) I currently need to add two instances of the network module to my config and explicitly set the family to "ipv6" for one of them.
This PR makes the network module able to handle both IPv4 and IPv6 simultaneously. It is enough to have a single instance of the network module that handle both protocols and the family doesn't have to be specified. This is a bit simpler and probably what most users would expect.

Let network module handle ipv4 and ipv6 simultaneously

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

When using `window-rewrite`, the `class<>` rule would previously only match against the `app_id` of a window. However, XWayland windows don't have an app ID, resulting in an empty string for the rewritten name.
This change falls back to checking the `class` window property if there is no app ID to support matching against XWayland windows.
Closes: #3020

sway/workspaces: use X11 class for XWayland windows

---

src/util/audio_backend.cpp

Before this commit, Waybar would sometimes get into a state where it would consume 100% of a CPU core, and the pulseaudio widget would stop responding to volume adjustments.
In this state, the pulseaudio mainloop thread would spin, with the counter of enabled defer events at 1, but no actual enabled defer event in the list to get the counter back to zero after an iteration in the mainloop.
This could happen if the unsynchronized interactions with the mainloop thread happened to modify the list of deferred events at the same time as the mainloop.
This commit introduces locking in accordance with the PulseAudio documentation on the threaded mainloop:
> The lock needs to be held whenever you call any PulseAudio function that
> uses an object associated with this main loop. Those objects …

Add locking for interacting with the pulseaudio thread

---

src/util/backlight_backend.cpp

re-implementation of #3519 
fix #3302 
It works on my Arch Linux but I didn't test it comprehensively.

Using 'auto' instead of 'self' in backlight module

---

src/modules/dwl/window.cpp

Without this, markup characters like [&><] will be injected directly into the Label. Escaping them makes sure that the values will be printed exactly as they appear in the window title or layout symbol.

Escape markup characters in dwl/window

---

src/util/regex_collection.cpp

`regex_collection.cpp` uses `std::sort` and does not import correct header.
Compilation with libstdc++ worked due to some indirect import, but compilation with LLVM libc++ fails.

Fix compilation with libc++

---

src/modules/cava.cpp

Attempts to fix #3870. Makes Cava config behave according to the officially intended behavior.
```
; sleep_timer = 0
```
After some testing, this PR does indeed fix every problem observed in the original issue, including the glitchy freeze frame of cava upon playing sounds after silence.

fix: never sleep cava when sleep_timer is 0

---

src/modules/sni/item.cpp

Fix errors when the tooltip set by a tray app contains markup characters.
For example, [CopyQ](https://github.com/hluk/CopyQ) sets its tooltip to the last copied text, which could contain arbitrary characters, some of which (like `< > &`) can cause an error when interpreted.

Escape tray tooltip text

---

include/config.hpp
src/ALabel.cpp
src/config.cpp

Since Waybar supports including additional configuration files using the `"include"` key, I expected to be able to use wildcards in the paths passed in. For example, a drop-in config directory:
```jsonc
{
"include": "/etc/waybar/config.d/*.jsonc"
}
```
Currently, this *almost* works. `Config::tryExpandPath()` already expands wildcards using `wordexp()`, but only takes the first result and discards the rest.
This PR updates `Config::tryExpandPath()` to return a vector of expanded path matches instead of a single path wrapped in an optional, with an empty vector indicating no matches.
`Config::resolveConfigIncludes()` iterates over all of these matches, while other instances of path expansion (such as finding the base config path) retain their existing behavior and only use the first match.

Allow using wildcards in config include paths

---

man/waybar-river-tags.5.scd
src/modules/river/tags.cpp

Adds the ability to hide vacant tags on river. Vacant means not occupied and not focused.
Addresses:
https://github.com/Alexays/Waybar/issues/3790
https://github.com/Alexays/Waybar/issues/2537

Hide vacant tags config option on River

---

include/modules/battery.hpp
include/util/udev_deleter.hpp
src/modules/battery.cpp
src/util/backlight_backend.cpp

When switching how you listen for battery plugging status events, the battery status will instantly update again!
Instead of inotify events on the /sys/class/.../ files, it is recommended to listen to udev netlink kernel events.
Closes #2444 
Closes #2519 
I need aid implementing this, because I'm new to this project.
I will try to make this code look more like the backlight_backend, which also uses the udev netlink interfaces.

Make battery module update on plugging/unplugging again (refs #2519)

---

src/modules/upower.cpp

Fix https://github.com/Alexays/Waybar/issues/3027
Hide Upower module when specified by `native-path` or `model` device disconnected.

Hide upower module when specified device disconnected

---

src/modules/battery.cpp

Some drivers (example: qualcomm-battmgr, present on Snapdragon X1 laptops) expose the current_now and power_now values in sysfs as negative int when the device is discharging, positive when charging.
This breaks the battery runtime estimation in Waybar, as it expects a uint32 for power_now.
Change the battery module to use the absolute values of current_now and power_now.
I discussed about it with the maintainer of qualcomm-battmgr, and the conclusion has been that it's better to fix the userland tools to respect the ABI documentation for current_now (which specifies negative values when discharging), and allows for negative values for power_now: https://lore.kernel.org/linux-arm-msm/20250213-patch-qcomm-bat-uint-power-v1-1-16e7e2a77a02@mailbox.org/

fix: battery runtime estimation with negative sysfs values

---

include/modules/hyprland/backend.hpp
include/modules/hyprland/language.hpp
include/modules/hyprland/submap.hpp
include/modules/hyprland/window.hpp
include/modules/hyprland/workspace.hpp
include/modules/hyprland/workspaces.hpp
src/modules/hyprland/backend.cpp
src/modules/hyprland/language.cpp
src/modules/hyprland/submap.cpp
src/modules/hyprland/window.cpp
src/modules/hyprland/workspace.cpp
src/modules/hyprland/workspaces.cpp

* Fixes IPC being blocked at shutdown: previously it required Hyprland to send another IPC message over the socket (like focuswindow) before waybar would shut down.
* IPC now managed using a static instance instead of global unique ptr
* Some general improvements to the Hyprland modules

Hyprland IPC improvements

---

src/modules/hyprland/workspaces.cpp

Fixed handling of urgent state for special workspaces. Replaced unnecessary and incorrect second check of active workspace with result of previous check.

hyprland/workspaces: fixed urgent for special workspaces

---

src/modules/niri/language.cpp

Ellipsize (converting the content of the widget to triple dots `...`) leads to the module displaying no information and therefore becoming useless. Since other modules don't have this behavior, I think it should be off for this one too.

turn off ellipsize for niri/language module

---

src/modules/temperature.cpp

dev.cpu is mentionned but not used. Moreover, you can have dev.cpu... but no hw.acpi, so include a test on dev.cpu first

fix(FreeBSD): Use dev.cpu temperature sysctl

---

include/modules/wireplumber.hpp
man/waybar-wireplumber.5.scd
src/modules/wireplumber.cpp

This change adds support for source (microphone etc) nodes to the WirePlumber module. 
This is done via a new `"node-type": "Audio/Source"` param (defaults to `"Audio/Sink"`).
The intent here is to use two instances of the module to control the speakers and microphone separately:
```
// first instance controls speakers
"wireplumber#sink": {
"format": "{volume}%",
"format-muted": "",
"on-click": "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
},
// second instance controls microphone
"wireplumber#source": {
"node-type": "Audio/Source",
"format": "",
"format-muted": "",
"on-click": "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
}
```

Resolves #3092 Add source support to wireplumber module

---

meson.build
meson_options.txt
src/util/backlight_backend.cpp

There are cases where systemd-logind is not used/running. Result is that bcklight module will not run.
Add an option that, when set to false, allows backlight module to work without systemd-logind.

add login-proxy option

---

nix/default.nix

Downstream added version check, causes this flake to fail building.
With latest nixpkgs:
```bash
> Executing versionCheckPhase
> Did not find version 0.12.0+date=2025-03-06_dirty in the output of the command /nix/store/zpb7x04yv9d1z2mrm5wml644v4kgfr6k-waybar-0.12.0+date=2025-03-06_dirty/bin/waybar --version
> env: '--version': No such file or directory
```

nix/default: disable version check

---

include/modules/network.hpp
man/waybar-network.5.scd
src/modules/network.cpp

Fixes #3956.
Users can now set `family` to `ipv4`, `ipv6`, `ipv4_6` to show the IPv4, IPv6, or both. With the default being `ipv4`.

Provide an option to show ipv4, ipv6 or both

---

man/waybar-clock.5.scd

fix incorrect type for `weeks-pos` in waybar-clock man page

---

include/modules/hyprland/workspaces.hpp
src/modules/hyprland/workspaces.cpp

The Hyprland [v2 workspace events](https://github.com/hyprwm/Hyprland/pull/5022) add the workspace ID to the event payload.
Currently Waybar relies on workspace names because that was the best the old events provided. By transitioning to IDs instead of names, Waybar can provide a more robust experience, avoid hairy issues like https://github.com/Alexays/Waybar/issues/3830.
At some point I'd like to follow up with a similar change in special workspaces, but `activespecialv2` doesn't exist yet in Hyprland.

Migrate Hyprland workspace events to v2

---

include/modules/privacy/privacy.hpp
include/modules/privacy/privacy_item.hpp
src/factory.cpp
src/modules/privacy/privacy.cpp
src/modules/privacy/privacy_item.cpp

This PR changes the privacy module to stack icons vertically when the bar orientation is vertical. Closes #2657.

Add support for vertical orientation in privacy module

---

src/modules/hyprland/workspaces.cpp

Been getting nonstop crashes for a while, finally looked into it. Saw a bunch of messages in logs about failing to parse IPC messages and the crash always happening with a core dump pointing at the `onWindowTitleEvent` parsing. Looks like we didn't check if we reached the end of the iterator before accessing, like we did in most of the handlers. 
Also some quick lint cleanup for using range find iterator instead of find with explicit begin and end.

hyprland/workspaces: fix crash

---

.github/workflows/clang-format.yml
.github/workflows/clang-tidy.yml.bak
.github/workflows/freebsd.yml

Looks like the clangFormatVersion was bumped to an unreleased version of the github action, pinning to the commit that makes that version available until next release. 
Formatting should be handled in https://github.com/Alexays/Waybar/pull/4025

.github/workflows/clang-format: bump github action (fix clang-format check)

---

src/modules/wireplumber.cpp

From #3974 
I don't know how to reproduce the error, would be great if somebody could test this who can.
EDIT: While I think this was sensible to fix, there seem to be more problems on the back of the reported issue. Perhaps a short lived wireplumber device, but since I don't know the repro that's very speculative.

wireplumber: fix potential nullpointer deref

---

src/modules/sway/workspaces.cpp

This PR improves the logic used to detect the currently focused workspace in Sway by fixing an issue that occurred when the layout was set to tabbed (or any other nested layout).
Previously, the code only checked one level deep for a focused container, this failed to detect focus correctly when the focused view was nested deeper within tabbed or stacked containers, causing waybar to show incorrect or missing workspace names.
We now recursively traverse all child nodes (including nodes and floating_nodes) to check for a focused container, ensuring proper detection regardless of layout depth

Sway Workspace: Fix workspace button not showing for tabbed/nested layouts

---

src/modules/custom.cpp

I noticed that waybar was continually allocating more memory after I added a custom module that invoked a continuous script. After looking at it for a while, I think it is because the `ScopeGuard`—meant to clear the buffer—was capturing `buff` by value, so it would continually try and free `nullptr`.
Here's a change that should capture `buff` by reference and hopefully fix the issue (it seemed to fix it for at least my use case). 
I'm pretty rusty at C++, and newish to github in general, so feedback is appreciated.

Memory Fix for continuous scripts in custom module

---

man/waybar-network.5.scd

Fixed a small inconsistency in the man page. Personally I would prefer to see the frequency in MHz but it's not that important.

fix: network frequency is reported in GHz

---

src/modules/clock.cpp

Initialize `cldMonShift_` member in the `clock` module constructor.  
This fixes a bug where the calendar tooltip would break after a reload, when in month mode.
Fixes #3819 and probably also #4071.

fix: `cldMonShift_` not getting initialized in `Clock()` constructor

---

Dockerfiles/debian

Slim images of Debian tend to be smaller even during development. Hence replace the full-fledged variant with the slim one.

Dockerfiles: Use debian-slim for container

---

src/modules/network.cpp

`clearIface` resets `ifid_` to `-1`, but it does so before the rfkill state can be displayed.
This results in the module never switching to the `disabled` state (unless rfkill was already active prior to launching waybar).

fix: network module not displaying rfkill state

---

resources/waybar.service.in

Description= should be a noun phrase, and not a full sentence, according
to man 5 systemd.unit.
In particular, using a dot at the end result in messages like this in
journalctl when running as a user service (note the superfluous dot at
the end):
May 31 16:03:38 framework systemd[1180]: Started Highly customizable Wayland bar for Sway and Wlroots based compositors..
May 31 16:20:39 framework systemd[1180]: Stopping Highly customizable Wayland bar for Sway and Wlroots based compositors....
May 31 16:20:39 framework systemd[1180]: Stopped Highly customizable Wayland bar for Sway and Wlroots based compositors..

Fix Description= in systemd service file

---

.github/workflows/docker.yml
Dockerfiles/gentoo

The gentoo CI job started started failing on recent PRs. What caught my attention is that it's running a pretty old version of gcc (12.2.1). Turns out the docker image hasn't been updated in nearly 2 years (most likely because of the strict version requirement for `dev-cpp/gtkmm`).
I've reduced the frequency of the docker build workflow, as a daily rebuild of the gentoo image will most certainly bust through the free CI tier. I've also added a `workflow_dispatch` trigger, so it can be run manually if needed.

Fix gentoo CI build

---

man/waybar-memory.5.scd
src/modules/memory/common.cpp

Add an argument to the memory module which displays the state of the swap configuration of the local system.
Usage of swap does not necessarily indicate if swap is on or off.

modules: memory: Add swapState format argument

---

src/modules/mpris/mpris.cpp

When using `playerctld` as the `player` for the MPRIS module, hide the widget when no player is active.

fix: MPRIS widget not hiding when no player is active

---

include/modules/privacy/privacy.hpp
include/util/pipewire/privacy_node_info.hpp
man/waybar-privacy.5.scd
src/modules/privacy/privacy.cpp
src/util/pipewire/privacy_node_info.cpp

This PR introduces an option ignore to exclude pipewire nodes from the privacy module.
This PR is essentially #3526 with a bit more documentation. Original PR was made by @gkleen.
I found the original PR to be quite useful, but it wasn't merged. I will update the wiki if this gets merged.

privacy: ignore some streams

---

resources/custom_modules/mediaplayer.py

Fixed an issue where artist names like "Earth, Wind & Fire" were not displayed correctly. The change ensures that artist names containing "&" are now shown properly.

Update mediaplayer.py - Fix artist name display in mediaplayer.py

---

man/waybar.5.scd.in
src/AIconLabel.cpp

The current behaviour for modules employing `AIconLabel` is that the icon is show on the left of the label.  This is not desirable for for vertical bars and for users with a right-to-left script.  
This PR solves this issue by:
* making `AIconLabel` honour the `rotation` property
* adding a `swap-icon-label` property

AIconLabel.cpp: honour "rotation" property and add "swap-icon-label" propery

---

src/modules/privacy/privacy_item.cpp

Closes #3981
As I'm mostly dealing with languages with automatic memory management, I'm not an expert on this. :p But I think `update_tooltip` creates objects with every update and at least doesn't get rid of the childrens' children.
Attempt to address this by using `make_managed` instead of new objects.
I've tested it and at least with my limited test it worked, can't see the reported memory leak with heaptrack anymore, either.

Issue 3981: try and fix memory leak in privacy module

---

src/main.cpp

Fixes #4047.
This creates a separate thread to watch for signals. I used a `pipe` to send signals to the signal thread, as pipes are one of the few signal-safe messaging options.
Because GTK isn't thread safe, I couldn't handle signals in the signal thread either, so I used a `SafeSignal` which is thread-safe (but probably not signal-safe!) so that signals were handled on the main thread.
I also moved the `SIGCHLD` handling code into the new thread. I'm unsure about this change, as it will longer mask `SIGCHLD` in the main thread. From a cursory test it seems to work and children are still being reaped correctly, but I separated this change into its own commit so it can be reverted separately.
(Incidentally, all of `reload`'s accesses were on the same thread, so I changed it from a global …

Fix signal safety deadlock

---

src/modules/hyprland/submap.cpp

It would be nice to allow simple pango markup in `"format": "{}",` of the `"hyprland/submap"` module from the `hyprland.conf` file.
Example `hyprland.conf`:
```conf
...
$submapName = Note:  <b>S</b> <i>some app</i> <b>O</b> <i>other app</i>
bind = $mainMod, A, submap, $submapName
submap = $submapName
bind = , s, exec, someapp
bind = , o, exec, otherapp
bind = , escape, submap, reset
submap = reset
...
```
I was able to get this to work by editing the code in `src/modules/hyprland/submap.cpp` and changing lines `71-72` from
```cpp
auto submapName = ev.substr(ev.find_last_of('>') + 1);
submapName = waybar::util::sanitize_string(submapName);
```
to
```cpp
auto submapName = ev.substr(ev.find_first_of('>') + 2 );
```
Without these edits or something similar the original code cuts/removes …

hyprland/submap: allow pango markup.

---

src/bar.cpp

Thanks to tmccombs this commit fixes some inconsitencies in #3730. These inconsitencies were:
- Fixed the oversight of missing the implementation of expand_center for center_ and right_
- Removes a last minut printf debugging statment I missed.
These two points were a mistake on my site and I should have reviewd my PR more carefully before publishing.
I am sorry for the inconvenience

Fixes: Add stretching of modules and modules-center toggling

---

include/modules/sway/window.hpp
man/waybar-sway-window.5.scd
src/modules/sway/window.cpp

if any check fails, that's still because of src/modules/sway/workspaces.cpp, i didn't touch that. see #4094 
EDIT: i did forget to format the header file though, should be fixed now.

feat: sway/window: provide {marks} format replacement

---

src/modules/mpris/mpris.cpp

**Summary:**  
This PR adds support for using mouse side buttons (typically buttons 8 and 9, often mapped as "back" and "forward" on high-end mice) to control previous/next track actions in the Waybar mpris module. This allows users to quickly skip tracks using their mouse's extra buttons.
**Context:**  
Related to #1160, which requested support for additional mouse buttons (beyond 0–5) for actions like next/previous track. This PR implements `on-click-backward` (button 8) and `on-click-forward` (button 9) as built-in actions, making it easier to control playback with modern mice.
**Testing:**  
Tested on Arch Linux (Wayland) with a Razer mouse.  
Please note: Other platforms and mice may need further testing.
**Notes:**  
- No breaking changes; existing button actions remain unchanged.
- …

Add support for mouse side buttons (back/forward) to control track navigation in mpris module

---

include/modules/hyprland/workspaces.hpp
man/waybar-hyprland-workspaces.5.scd
src/modules/hyprland/workspace.cpp
src/modules/hyprland/workspaces.cpp

Add ability to hide all not-`persistent` workspaces in hyrpland
Full problem: #4111

Add persistent-only setting for hyprland/workspaces

---

include/modules/wayfire/backend.hpp
include/modules/wayfire/window.hpp
include/modules/wayfire/workspaces.hpp
man/waybar-wayfire-window.5.scd
man/waybar-wayfire-workspaces.5.scd
meson.build
src/factory.cpp
src/modules/wayfire/backend.cpp
src/modules/wayfire/window.cpp
src/modules/wayfire/workspaces.cpp

I implemented Wayfire integration (especially for workspaces and window) since it did not seem to exist.
I have confirmed that it works in my environment, but please let me know if there is anything else I can do.

add module wayfire/window, wayfire/workspaces

---

man/waybar-niri-workspaces.5.scd
src/modules/niri/backend.cpp
src/modules/niri/workspaces.cpp

This adds support for the [newly added urgency feature in niri](https://github.com/YaLTeR/niri/pull/1319) to niri-workspaces, matching other modules like sway-workspaces.

niri: add support for urgency indicators to workspaces

---

src/modules/hyprland/language.cpp

Hypr onfig:
```
kb_layout = us, us
kb_variant = basic, intl
```
Using find_last_of eg:
`ev = "activelayout>>kb-name-,English (US, intl., with dead keys)"`
So layout name will be = " with dead keys)" -> unknown layout !
Using find_first_of fixed it.

Fixed one layout with multiple variant bug hyprland/language Fixes #3676

---

include/modules/gps.hpp
man/waybar-gps.5.scd
meson.build
meson_options.txt
src/factory.cpp
src/modules/gps.cpp

Adds a GPS module using libgps and gpsd.
No need to get a GPS receiver, you can test using an android phone and the [gpsdRelay](https://github.com/project-kaat/gpsdRelay) app.
Install gpsd and run:
`gpsd tcp://<ip-of-phone>:6000`

Add GPS module

---

include/modules/bluetooth.hpp
src/modules/bluetooth.cpp

Current bluetooth module shows battery percentage from bluez experimental features. This has two drawbacks:
1.  Not super user friendly, as users need to activate these features;
2. Most importantly, a lot of devices (at least in my experience) do not report battery percentage anyway, despite having it in upower;
In this PR, the bluetooth module will first try to fetch battery percentage from bluez and, if not available, will try fetching it from upower.
At the moment, the code is getting all upower devices, and then looking for the one with the correct serial number. I don't know if there's a better way of doing this

Bluetooth module: fetch battery percentage from upower if not found from bluez

---

src/modules/network.cpp

fix: 'ethernet' network state should have precedence over 'disabled'

---

src/client.cpp

Addresses #4291
This might a breaking change for people who's setup expect the value of the GTK CSS variables to just always be the default variant. However I feel like this is more inline with expectations (at least mine) and better for the future.
Also I am not very familiar with the GTK C++ APIs and if this is the best way to accomplish this. But this works for me on my local build.

respect gtk color scheme variant for gtk css variable

---

include/modules/network.hpp
include/util/rfkill.hpp
man/waybar-network.5.scd
src/modules/network.cpp

This setting makes it possible to have a configuration with two network modules where one of them displays the ethernet state (disconnected, linked, ethernet), and the other, the wifi state (disabled, disconnected, linked, wifi).
Otherwise the ethernet state would show up as "disabled" (instead of "disconnected") when rfkill is active.

feat: add rfkill network setting

---

src/modules/sni/item.cpp

Adds a (albeit hacky way) to override the tray icon for Electron apps.
Uses the lowercase version of the tooltip as the ID that is used to fetch the icon, and thus what you would pass into the tray `icons` option:
Example config:
```
{
"tray": {
"spacing": 10,
"icons": {
"1password": "<path to icon theme>/apps/16/1password.svg",
"bitwarden": "...",
"vesktop": "...",
"iranoutofelectroappselectronmustdie": "xD"
}
}
```
EDIT: screenshot

feat: add a way to override electron app tray icons

---

man/waybar-mpd.5.scd
src/modules/mpd/mpd.cpp

Many people have files in their music library that are not properly tagged and for such files `{title}` and `{album}` cannot be displayed by the mpd module. As a fallback the user might want to display filename or the full URI of this file instead ( see https://github.com/Alexays/Waybar/issues/3631 ).
This PR
* enables the `{filename}` format replacement to be used in tooltips (previously only available in the label, for some reason)
* documents the `{filename}` format replacement in the man page
* adds an `{uri}` format replacement which takes the value of [`mpd_song_get_uri`](https://www.musicpd.org/doc/libmpdclient/song_8h.html#a969dbd00e70ee44b573eb2feb0fb71b3)
While this does not allow to display the filename conditionally on the title being empty (format strings like …

mpd: add uri and filename format arguments

---

include/modules/river/layout.hpp
man/waybar-river-layout.5.scd
src/modules/river/layout.cpp

This allows for custom styling for specific river layouts (such as monocle). It follows the same pattern as used in river/mode for making custom per-mode styling possible.

feat(river): set layout name as class

---

include/bar.hpp
include/util/kill_signal.hpp
man/waybar.5.scd.in
src/bar.cpp
src/main.cpp
src/util/enum.cpp

Imlpements https://github.com/Alexays/Waybar/issues/3928
The code isn't the best and there is some duplication too. 
I'd appreciate if there would be help with it.
And, of course, any feedback if you still think that this is a good way to tackle the show/hide feature or not.

Idempotent bar show/hide via configurable user kill signals

---

include/modules/sni/tray.hpp
src/modules/sni/tray.cpp

Currently, the tray module automatically hides when there are no tray icons. However, this behavior is not consistent with the "show-passive-items" config property. If there are passive tray items (e.g. Spotify) and "show-passive-items" is false (as it is by default), the tray will still be visible.
This PR fixes this by only hiding the tray if there are no visible tray icons.

fix: hide tray when there are no non-passive icons

---

man/waybar-sway-workspaces.5.scd
src/modules/sway/workspaces.cpp

Scroll direction by default is kinda counterintuitive, especially for people who migrating from i3/polybar to sway/waybar.
The code now checks for "reverse-scroll" property and switches workspaces in different direction if it's true

sway/workspaces: Implement reverse-scroll

---

include/config.hpp
src/bar.cpp
src/config.cpp
src/modules/custom.cpp

This is a two part PR, it appears when I was tinkering with my `waybar` config in my ``~/.config/waybar/` directory and occasionally did 
```
includes: [
"modules/custom.jsonc",
"modules/groups.jsonc"
]
```
and suddenly half of my waybar just disappeared. It took me a long time to trace the issue, since there was zero messages in logs, even with `-l debug` key.
So, as a result here is the PR:
1. I've added couple of warning statements that elements description is missing. My assumption is that unlike any other elements (e.g. "cpu"), "custom" and "group" elements has no defaults to fall into, so if there is no configuration found (it can be wrong include as in my case, or just a typo) then this element will always be hidden. And so it is legit to warn user that this may happen.
2. I've …

Relative paths in included configs

---

include/modules/sni/item.hpp
src/modules/sni/item.cpp

If a tray menu is open and hovered as the item disappears from the tray, its GTK menu is left in an invalid state and locks up waybar.
This gets spammed in the logs:
```
(waybar:54340): Gtk-CRITICAL **: 13:56:28.088: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
```

fix: close sni menu on item destruction

---

src/AIconLabel.cpp
src/bar.cpp

This pull request improves the robustness of the `onMap` event handler in `bar.cpp` by adding checks to ensure the GDK window is valid before proceeding with surface initialization. This helps prevent  crashes or undefined behavior when the window is not available.
Error handling improvements:
* Added null checks for the GDK window reference and GDK window object in the `onMap` method of `Bar`, logging warnings and deferring surface initialization if either is unavailable.
fixes:
```bash
(waybar:1514241): Gdk-WARNING **: 20:57:45.295: Couldn't map window 0x560086bf4850 as subsurface because its parent is not mapped.
Segmentation fault (core dumped)
```

fix: handle null GDK window reference in surface initialization

---

include/modules/river/tags.hpp
src/modules/river/tags.cpp

Before this, vacant tags would show with `hide-vacant` set on initial startup, because we receive initial tag events from River before we show the bar. In that case, we won't call `set_visible(false)` on the respective buttons because they're not shown yet. This registers the output status listener after we show the bar so we won't miss any events.

fix(river): hide vacant tags on initial startup

---

include/modules/ext/workspace_manager.hpp
man/waybar-ext-workspaces.5.scd
src/modules/ext/workspace_manager.cpp

Do this by removing the needs-update tracking. The gain was questionable to begin with and turns out it  doesn't work correctly with multiple outputs.
While at it, I've added a "deactivate" action.
Supersedes #4435 
Closes #4434

ext/workspaces: fix appearing of hidden workspaces

---

include/modules/hyprland/backend.hpp
src/modules/hyprland/backend.cpp

In rare circumstances, we may fork(), e.g., as part of a custom module, and the child process may fail to exec() and exit. In those cases, the IPC destructor will be called in the child process.
Prior to this commit, this call would then result in the shared socket being closed. Prevent this by only closing the socket from the original process.

Prevent child zombie process from tearing down Hyprland IPC

---

include/config.hpp
src/config.cpp
test/config.cpp
test/config/include-relative-path.json
test/config/include-wildcard.json
test/config/modules/cpu.jsonc
test/config/modules/memory.jsonc

This bugfix tries to solve regression #4354
As it turns out, initial implementation used `findConfigPath` which was made with a different purpose. So, I had to update `findIncludePath` to use original `tryExpandPath` which provides full set of results instead of only one as `findConfigPath` does. This implementation produces expected result.
During manual test, one should use this file for `memory.jsonc` (there is a typo in original issue)
```
// modules/memory.jsonc
{
"memory": {
"interval": 2,
"format": "foo: {used:0.1f}G",
}
}
```

bugfix: expanding wildcards in config includes (#4354)

---

src/modules/gamemode.cpp

Fixes #2206 
Quite a simple solution, might be a bit crude, is there a better way to do this?

Fix: styling: set gamemode icon size and spacing to 0 if use-icon is false

---

src/modules/ext/workspace_manager.cpp

When parsing the configuration, the configuration of the left button was mistakenly parsed as that of the middle button and the right button, resulting in both the middle button and the right button being able to only trigger the action of the left button

fix: right and middle button not work in ext/workspace module
