Alexays/Waybar

meson.build, meson_options.txt
Make the output directory for extras configurable.
=> meson: make extra output directory configurable

resources/config, src/modules/battery.cpp
Also naming is a bit more consistent
I hope it's okay for you that I create pulls for such minor features.
=> Added second warning stage to battery module

include/modules/memory.hpp, src/modules/memory.cpp
This parses `/proc/meminfo` as suggested in #6 
Closes #6
=> Use /proc/meminfo for Memory module

resources/config, src/modules/pulseaudio.cpp
=> Add config option for volume change scroll step size

include/bar.hpp, include/modules/battery.hpp, include/modules/clock.hpp, include/modules/cpu.hpp, include/modules/custom.hpp, include/modules/memory.hpp, include/modules/network.hpp, include/modules/sni/tray.hpp, include/modules/sway/ipc/client.hpp, include/modules/sway/ipc/ipc.hpp, include/modules/sway/mode.hpp, include/modules/sway/window.hpp, include/modules/sway/workspaces.hpp, include/util/command.hpp, include/util/json.hpp, include/util/sleeper_thread.hpp, meson.build, src/bar.cpp, src/modules/clock.cpp, src/modules/cpu.cpp, src/modules/network.cpp, src/modules/sway/ipc/client.cpp, src/modules/sway/mode.cpp, src/modules/sway/window.cpp, src/modules/sway/workspaces.cpp
close #120 
@jeremejevs Can you test :)
Also anyone interested if they can test that nothing is broken 😄 
(especially the network that had a big refactor)
=> refactor: proper modules destruction

include/ALabel.hpp, src/ALabel.cpp, src/modules/network.cpp
@oliverpool This PR might fix your issue #145, i can't test until tomorrow, but if anyone can confirm that it fixes the problem, I'll merge this PR :)
=> fix(Network): format-alt

src/modules/custom.cpp, src/modules/sway/mode.cpp
Fixes #162 
This should escape all needed user controlled inputs.
=> fix: Escape user controlled input

resources/config
Messed up the example format... I'm an idiot.
=> Fix tooltip format

.gitignore, src/modules/backlight.cpp
Also ignore other potential build directories
Fixes #196. @Robinhuett, could you confirm?
=> Disable backlight module if no backlights found

include/modules/sway/workspaces.hpp, src/modules/sway/workspaces.cpp
Hello!
This one resolves #205 that I've just created.
It simply hides the all the buttons but the focused one.
=> resolves #205

src/modules/network.cpp
Adds the possibility to set different formats in the tooltip. Mainly the same as the normal format just with the prefix `tooltip`. If non are defined, but the tooltip enabled, it will use the same output as the bar.
```
"network" {
"interface": "wlp2s0",
"format": "{ifname}",
"format-wifi": "{essid} ({signalStrength}%) ",
"format-ethernet": "{ifname} ",
"format-disconnected": "", //An empty format will hide the module.
"tooltip-format": "{ifname}",
"tooltip-format-wifi": "{essid} ({signalStrength}%) ",
"tooltip-format-ethernet": "{ifname} ",
"tooltip-format-disconnected": "Disconnected",
"max-length": 50
}
```
=> Add custom tooltip format for network module

src/ALabel.cpp, src/bar.cpp
Adds support for on-click-[backward/forward/middle]
Also fixing format-alt, which was making modules to behave a bit erratically (was not sure if I was to make a separated pr for this issue, but I decided against it in the end, sry if that's a bother)
=> Improving mouse buttons support

README.md, include/factory.hpp, include/modules/temperature.hpp, meson.build, resources/config, resources/style.css, src/factory.cpp, src/modules/temperature.cpp
Read temperature from sysfs (thermal zone or specific hwmon path). Add a `.critical` class when temperature is above a configurable threshold.
=> Add temperature module

resources/custom_modules/mediaplayer.py
I saw some littering in the global scope. Wrapping it in a main method should fix things up.
If it seems random. I'm busy implementing command line arguments for this script, so you can select the right player if you want, and if you don't it will just list the last one that received an update. Probably accounting for both wanted behaviours in #103.
=> refactor: Add main method / Clean global scope

resources/custom_modules/mediaplayer.py
Added command line arguments and some logging. This should be enough boilerplate/refactoring to get this feature to work.
=> Feature: Command line arguments/Logging

resources/config, resources/custom_modules/mediaplayer.py, resources/style.css
- Class is set via json class attribute 
- Different background colors for classes (examples 'custom-spotify' and 'custom-vlc' in style.css)
- Icon is chosen based on json alt attribute (default is musical note icon)
=> Convert spotify module to generic json version

include/modules/custom.hpp, src/modules/custom.cpp
Resolve #263
@AndreasBackx Can you confirm that it doesn't break anything and solve your problem correctly :)
=> Custom: Ability to add multiple classes

meson.build
=> Update fmt build dependency

include/modules/pulseaudio.hpp, src/modules/pulseaudio.cpp
=> fix(btformat): fixes an issue where btformat was not detected

include/modules/network.hpp, resources/config, src/modules/network.cpp
Will closes #292 #230 #239
People who want to test and review are welcome :)
=> Network improvements

include/bar.hpp, include/modules/battery.hpp, include/modules/cpu.hpp, include/modules/custom.hpp, meson.build, src/bar.cpp, src/client.cpp, src/main.cpp, src/modules/battery.cpp, src/modules/cpu.cpp, src/modules/custom.cpp, src/modules/mpd.cpp, src/modules/network.cpp, src/modules/sni/host.cpp, src/modules/sni/item.cpp, src/modules/sni/tray.cpp, src/modules/sni/watcher.cpp, src/modules/sway/mode.cpp, src/modules/sway/window.cpp, src/modules/sway/workspaces.cpp, subprojects/spdlog.wrap
Adding spdlog and replacing most text printing
I barely know how to use meson, so hopefully I did it mostly right. Didn't find how to include spdlog while disabling compiler warnings for it though
=> Adding spdlog

src/client.cpp, src/modules/sni/item.cpp
Hopefully, that will address or at least explain issues like [this comment](https://github.com/Alexays/Waybar/issues/21#issuecomment-489599739). And make troubleshooting a bit easier for those who are afraid of C++ :smile: 
I had to add log level command line option as there's no way to set it otherwise. Could be reverted if you feel there's a better option, like config file key or whatever else.
=> Tray error handling and logging improvements

include/util/command.hpp
=> Prevent zombie apocalypse by ignoring SIGCHLD

include/AModule.hpp, src/AModule.cpp
(This is against the `clean` branch, so this should update #387)
=> AModule: handle X axis scrolling

src/AModule.cpp
- Implemented review by @panaman67
- General cleanup.
Again, this is against `clean`, affecting #387
(Should probably merge with a rebase, don't see a reason to insert the extra merge commit here)
=> Cleanup on clean branch

src/modules/pulseaudio.cpp
Reconnect the event handler that was removed in commit 527144a.
Fixes Alexays#400
=> fix(pulseaudio): connect scroll event handler

include/modules/sni/item.hpp, src/modules/sni/item.cpp
A couple of tray fixes. See individual commit descriptions.
=> Tray fixes

include/modules/clock.hpp, src/bar.cpp, src/modules/sni/host.cpp
=> Unbreak with fmtlib 6.0.0

man/waybar-memory.5.scd
=> fix: correct man memory description

man/waybar-sway-workspaces.5.scd, src/modules/sway/workspaces.cpp
though this breaks backwards compatibility
=> Fix typo: persistant -> persistent

.travis.yml, Dockerfiles/alpine, Dockerfiles/archlinux, Dockerfiles/debian, Dockerfiles/fedora, Dockerfiles/opensuse, man/waybar-pulseaudio.5.scd, man/waybar-states.5.scd
Also enable `man-pages` option in travis so that docs are tested as part of the CI/CD process
=> Fix some issues in man pages

meson.build, resources/waybar.service
=> Revert "service file: allow for waybar installed in different prefix"

src/modules/pulseaudio.cpp
Change default behavior from 0% - 99% to 0% - 100%.
=> change audio scroll bound

man/waybar-pulseaudio.5.scd, src/modules/pulseaudio.cpp
Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>
=> pulseaudio: export desc as a format

src/bar.cpp
Now if we toggle bar mode by send SIGUSR1 when bar is still visible
[example](https://imgur.com/a/950sIzg)
=> Toggle opacity

man/waybar-backlight.5.scd, man/waybar-battery.5.scd, man/waybar-clock.5.scd, man/waybar-cpu.5.scd, man/waybar-custom.5.scd, man/waybar-disk.5.scd, man/waybar-idle-inhibitor.5.scd, man/waybar-memory.5.scd, man/waybar-mpd.5.scd, man/waybar-network.5.scd, man/waybar-pulseaudio.5.scd, man/waybar-sway-mode.5.scd, man/waybar-sway-window.5.scd, man/waybar-temperature.5.scd
=> Add info on "on-click-middle" option to custom module man page

man/waybar-backlight.5.scd, man/waybar-battery.5.scd, man/waybar-clock.5.scd, man/waybar-cpu.5.scd, man/waybar-custom.5.scd, man/waybar-disk.5.scd, man/waybar-idle-inhibitor.5.scd, man/waybar-memory.5.scd, man/waybar-mpd.5.scd, man/waybar-network.5.scd, man/waybar-pulseaudio.5.scd, man/waybar-sway-mode.5.scd, man/waybar-sway-window.5.scd, man/waybar-temperature.5.scd
=> Revert "Add info on "on-click-middle" option to custom module man page"

resources/custom_modules/mediaplayer.py
Using mps-youtube, most tracks that I'm listening to do not return information on the artist.
Adding an else condition to return the title anyways.
=> feat: show title if artist isn't available

src/modules/network.cpp
This pull request fixes the display of the IPv6 address and its CIDR in the network module.
=> fix(network): display of IPv6 address

include/modules/mpd.hpp, man/waybar-mpd.5.scd, src/modules/mpd.cpp
I've been using this locally for a while and finally decided to submit this upstream, now that the MPD module doesn't segfault anymore :wink:. Let me know if there are any changes I need to make.
=> mpd: add paused format string

include/modules/clock.hpp, man/waybar-clock.5.scd, meson.build, resources/config, src/modules/clock.cpp, subprojects/utfcpp.wrap
A simple single-month calendar in clock tooltip.  Layout follows Unix cal style.  Supports localized weekday names.
=> Current month calendar in clock tooltip.

src/modules/pulseaudio.cpp
Fixes #382
Possibly fixes and related to #497.
=> pulse: track default source/sink changes

man/waybar-temperature.5.scd, src/modules/temperature.cpp
This fixes [this issue](https://github.com/Alexays/Waybar/issues/622).
=> Added support for absolute device paths for the temperature module.

.travis.yml, README.md, include/factory.hpp, include/modules/cpu.hpp, include/modules/memory.hpp, include/modules/pulseaudio.hpp, include/modules/sni/item.hpp, include/modules/sway/workspaces.hpp, include/util/command.hpp, meson.build, meson_options.txt, src/client.cpp, src/factory.cpp, src/modules/cpu.cpp, src/modules/cpu/bsd.cpp, src/modules/cpu/common.cpp, src/modules/cpu/linux.cpp, src/modules/disk.cpp, src/modules/memory/bsd.cpp, src/modules/memory/common.cpp, src/modules/memory/linux.cpp, src/modules/sni/item.cpp
Kinda works ([package](https://www.freshports.org/x11/waybar)) but I haven't tested much.
```
$ waybar
[info] Resources files: //usr/local/etc/xdg/waybar/config, //usr/local/etc/xdg/waybar/style.css
[error] media stopped unexpectedly, is it endless?
[warning] module network: Unknown module: network
[warning] module temperature: Disabling module "temperature", Can't open /sys/class/thermal/thermal_zone0/temp
[warning] module backlight: Disabling module "backlight", No backlight found
[warning] module battery: Unknown module: battery
[warning] module battery#bat2: Unknown module: battery#bat2
[warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
[info] Bar configured (width: 3840, height: 30) for output: DP-1
[error] mpd: Failed to …
```
=> FreeBSD support

meson.build
=> chore: always include sway module

meson.build
cf https://reproducible-builds.org/
=> Remove date macro on version for reproducible builds

include/util/format.hpp
For https://github.com/Alexays/Waybar/issues/810
=> Fix crash with fmt

include/factory.hpp, include/modules/network.hpp, meson.build, meson_options.txt, src/factory.cpp, src/modules/network.cpp
Add a feature to meson config which allows for optionally building rfkill stuffs.
See #822
=> Rfkill optional

src/modules/network.cpp
=> network: fix typo - update tooltip only when it changes

man/waybar-mpd.5.scd, resources/config, src/modules/mpd.cpp
Just a small update I use to display the current track number and queue length. If you like to add it, feel free to do so — and thanks for the great work ;)
=> Added song position and queue length.

.travis.yml, Dockerfiles/alpine, README.md, include/factory.hpp, include/modules/sndio.hpp, man/waybar-sndio.5.scd, meson.build, meson_options.txt, src/factory.cpp, src/modules/sndio.cpp
- can control sndio: change volume, toggle mute
- appearance is somewhat dynamic: takes muted status into account
- uses polling inside sleeper thread to update values
=> Add sndio module.

src/bar.cpp
Added css selectors to the module groups. This allows for individual styling of each group seperately. Suggested in #652
=> added module group selectors for styling

meson.build, src/modules/network.cpp
A couple of minor build fixes. See individual commits for error details.
Tested with gcc 11 and meson 0.49.2.
=> Build fixes

include/util/format.hpp
=> Revert "Replace lowercase "k" with uppercase "K" to make it look more consistent"

.github/workflows/freebsd.yml
The last build on TravisCI was 20 days ago, so let's try an alternative.
https://travis-ci.com/github/Alexays/Waybar/builds
https://news.ycombinator.com/item?id=25338983
Example build: https://github.com/jbeich/Waybar/runs/1602295701
=> CI: add FreeBSD to Actions

include/client.hpp, src/client.cpp, src/main.cpp
=> Implement support for reloading of config files.

include/modules/battery.hpp, man/waybar-battery.5.scd, src/modules/battery.cpp
Hi Alex,
I like to keep an eye on the power draw of my laptop, hope you don't mind this small addition :)
Cheers,
Martin
=> add power formatter to battery module

src/modules/idle_inhibitor.cpp
=> disable Idle Inhibitor module if unsupported

src/modules/battery.cpp
Use the most relevant battery status, instead of the status of the last battery. The most relevant is the first of charging, discharging, not charging, full or unknown, in this order. So, e.g. when one of the batteries is charging and others are not charging or full, report use charging as the status. Or, when one of the batteries is discharging and others are full, use discharging as the status.
=> Use the correct battery status when multiple batteries are present

src/modules/pulseaudio.cpp
Hello,
I'm not really experience with C++, so apologies for any mistakes.
I opened this PR due to https://github.com/Alexays/Waybar/issues/853.
This should be temporary, as https://github.com/Alexays/Waybar/issues/925 exists.
- Add additional fields, namely `source_volume` and `source_desc`
- Add `tooltip-format`, reverting to default behavior if not specified
- Add additional CSS classes, namely `sink-muted` and `source-muted`
=> Improve Pulseaudio sink/source separation

include/modules/wlr/taskbar.hpp, man/waybar-wlr-taskbar.5.scd, src/modules/wlr/taskbar.cpp
Implement https://github.com/Alexays/Waybar/issues/1029
=> [wlr/taskbar] Add ignore-list param

src/modules/battery.cpp
As discussed on #1098 , little fix for pinebook pro laptops.
=> fix: incorrect battery percentage on Pinebook Pro

src/modules/battery.cpp
=> Revert "Fix power calculation when battery units are in μA instead of μW"

include/modules/sway/language.hpp, man/waybar-sway-language.5.scd, src/modules/sway/language.cpp
Implement https://github.com/Alexays/Waybar/issues/1208
=> feat: Add short desc to lang

include/modules/cpu.hpp, man/waybar-cpu.5.scd, src/modules/cpu/common.cpp
=> Revert "Add CPU usage for every core"

src/modules/sway/language.cpp
A redo of #1192 for the current state of the module.
=> sway/language: remove tabs, indent with 2 spaces

resources/custom_modules/mediaplayer.py, src/modules/clock.cpp, src/modules/network.cpp, src/modules/sni/tray.cpp, test/config.cpp
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
=> Fix spelling errors

include/modules/wlr/taskbar.hpp, man/waybar-wlr-taskbar.5.scd, src/modules/wlr/taskbar.cpp
Implement: https://github.com/Alexays/Waybar/issues/1293
=> feat: Ignore by title

src/modules/network.cpp
=> Revert "dont escape essid in tooltip"

include/factory.hpp, include/modules/inhibitor.hpp, meson.build, meson_options.txt, src/factory.cpp, src/modules/inhibitor.cpp
The logind feature adds a new inhibitor module which allows to acquire
the inhibitor locks that logind presents.
=> Add logind feature, with its 'inhibitor' module

README.md
Its a very, very popular Distro, especially for Wayland users...
It might be good to also put the Package in the README. Just an idea.
=> Add Gentoo to README.md

man/waybar.5.scd.in, src/bar.cpp
When `"fixed-center": true,` (default):
When `"fixed-center": false,`:
Resolves #957
=> Add `fixed-center` option

resources/style.css
(see commit message)
Fixes #1148.
=> resources: don't break tray icon checkboxes via CSS

man/waybar-memory.5.scd, src/modules/memory/common.cpp
Implements: https://github.com/Alexays/Waybar/issues/1156
=> [Memory] feat: Add swap flags

include/modules/keyboard_state.hpp, man/waybar-keyboard-state.5.scd, src/modules/keyboard_state.cpp
=> Improve keyboard_state error messages

include/AIconLabel.hpp, include/modules/sway/window.hpp, meson.build, src/AIconLabel.cpp, src/modules/sway/window.cpp
Demo:
https://user-images.githubusercontent.com/19961516/137642147-1f71a58e-a91c-41d0-8124-e40e895153e0.mp4
Signed-off-by: Felix Weilbach <felix.weilbach@t-online.de>
=> Show application icon when using sway window module

include/modules/clock.hpp, src/modules/clock.cpp
I'm not clear on the implications of this change, but it seems to fix the freebsd github action error.
Fixes error introduced by https://github.com/Alexays/Waybar/pull/1333
=> Fix freebsd action

man/waybar-bluetooth.5.scd, src/modules/bluetooth.cpp
Allow to set a different style if the bluetooth adapter is disabled.
=> Add disabled bluetooth style

include/modules/sway/window.hpp, man/waybar-sway-window.5.scd, src/modules/sway/window.cpp
=> sway/window: Allow the user to change the size of the app icon

src/bar.cpp
Don't set the anchor for certain edges when the width or the height is not set to a value of 'auto' (1).
When the bar is vertical, the top and bottom edges are not anchored otherwise the left and right edges are not anchored.
This resolves an issue wherein the width and height set for the layer-shell were ignored because the layer was set to anchor to all edges.
=> bar: don't set layer-shell anchor for edges when width is not 'auto'

meson.build
Forgot to add the Gamemode man file in #1554... My bad
=> Added gamemode man file to meson

include/factory.hpp, include/modules/river/mode.hpp, man/waybar-river-mode.5.scd, man/waybar.5.scd.in, meson.build, protocol/river-status-unstable-v1.xml, src/factory.cpp, src/modules/river/mode.cpp, src/modules/river/window.cpp
This module shows river's current mapping mode (e.g. normal, locked).
ref https://github.com/riverwm/river/pull/614
=> river/mode: new module

.github/workflows/freebsd.yml
See https://github.com/actions/virtual-environments/issues/5583
=> CI: prevent FreeBSD breakage in future

src/modules/network.cpp
=> Revert "added checking router id in handleEvent function, because module does…"

src/modules/temperature.cpp
This PR aims to propose a FreeBSD to gain temperature support using sysctl on hw.acpi.thermal.tz0.temperature.
Screenshot (with cpu and memory):
@jbeich maybe you have a better idea about this fix?
=> FreeBSD: Add support to temperature

src/modules/pulseaudio.cpp
Fixed issue where volume stepping would cause the max volume to go above the max and never reach 0.
=> Fixed pulseaudio max-volume configuration

include/factory.hpp, include/modules/sway/scratchpad.hpp, man/waybar-sway-scratchpad.5.scd, man/waybar.5.scd.in, meson.build, resources/config, resources/style.css, src/factory.cpp, src/modules/sway/scratchpad.cpp
Scratchpad indicator for swaywm.
Related issue: #1662 .
=> [sway/scratchpad] New module for scratchpad of sway

include/factory.hpp, include/modules/user.hpp, meson.build, src/factory.cpp, src/modules/user.cpp
Module for show login user, user default avatar(.face) or custom image, system work time or system start date
=> added user module

include/modules/hyprland/window.hpp, include/modules/sway/window.hpp, include/util/rewrite_title.hpp, man/waybar-hyprland-window.5.scd, meson.build, src/modules/hyprland/window.cpp, src/modules/sway/window.cpp, src/util/rewrite_title.cpp
=> [hyprland/window] Implement rewrite option like in sway/window

src/modules/custom.cpp
=> Revert "Escape text in custom module"

man/waybar-backlight.5.scd, man/waybar-battery.5.scd, man/waybar-cpu.5.scd, man/waybar-disk.5.scd, man/waybar-memory.5.scd, man/waybar-pulseaudio.5.scd, man/waybar-states.5.scd
Improves the accuracy and consistency of the documentation for module states.
=> Fix states documentation

src/modules/custom.cpp
=> fix custom module leaves zombie processes behind when bars are removed

include/modules/upower/upower.hpp, man/waybar-upower.5.scd, src/modules/upower/upower.cpp
Added on-click to upower to bring it more inline with battery
=> Upower click

src/modules/wireplumber.cpp
This fixes #1811 by falling back to `node.description` if `node.nick` is not available. This can happen for bluetooth devices that do not have a `node.nick`.
=> fix: wireplumber module when used with a bluetooth device

include/modules/clock.hpp, src/modules/clock.cpp
During the investigation there was found an issue
=> format-calendar-weeks won't accept format strings #1874.

src/modules/hyprland/language.cpp
* Made linter happy
* Renamed some variables to conform to the formatting
=> Minor refactorings and formatting fixes for hyprland language module

src/modules/clock.cpp
I've tried to improve ux in the clock module when calendar_shift is used:
1. Alter only the date, not the time (see the difference in the videos below).
2. Use shifted values only in the tooltip; when scrolling, the date will change only there.
3. When the mouse leaves (the popup closes), the shift is reset.
**current waybar 0.9.16**
https://user-images.githubusercontent.com/449375/209773492-5af428ba-6e22-4ddd-9085-5c181590162c.mp4
**after proposed changes**
https://user-images.githubusercontent.com/449375/209773501-fae54cc5-7ad6-43e1-bbd9-73ebeaea0c27.mp4
=> modules/clock: improve ux when calendar_shift is used

Dockerfiles/alpine, Dockerfiles/archlinux, Dockerfiles/debian, Dockerfiles/fedora, Dockerfiles/gentoo, Dockerfiles/opensuse, include/modules/mpris/mpris.hpp
- Activate ci for mpris module
- mpris: fix build errors
=> Activate CI for mpris module

man/waybar-sway-window.5.scd
Noticed error in manpage while editing the wiki.
=> sway/window: fix manpage

man/waybar-image.5.scd, man/waybar.5.scd.in, meson.build
=> docs(image): add image doc in meson and fix title

src/modules/hyprland/language.cpp
=> Sanitize hyprland language string only instead of the whole format

src/AModule.cpp
Hi @Alexays . This PR supplement modules action and solves the Issue #2030 . The issue here is module (like Clock) when format-alt is not provided can call ALabel contstructor with enable_click = false or enable_scroll = false.  In the same time user can use redefining action functionality. As a result even user redefined actions AModule don't catch events. So AModule first check this. And in case when user redefined actions, AModule initializes event catching.
=> Issue #2030. AModule enable_click & enable_scroll

src/modules/mpd/mpd.cpp, src/modules/wireplumber.cpp
=> refactor: make linter happy.

include/modules/mpris/mpris.hpp, man/waybar-mpd.5.scd, man/waybar-mpris.5.scd, src/modules/mpris/mpris.cpp
the reason i added so much code for unicode is because i personally listen to quite a lot of japanese music, so it's nice to have proper support for japanese titles
Closes #2023
=> mpris: add tooltip, length limits, position tag

include/util/rewrite_string.hpp, man/waybar-sway-window.5.scd, meson.build, src/modules/hyprland/window.cpp, src/modules/sway/window.cpp, src/util/rewrite_string.cpp
=> sway/window: Rewrite entire format output instead of just the title

src/modules/wireplumber.cpp
Checking against names for volume changes seems a bit weird to me and also didn't really work, so I've made use of node_id_ to check against this instead and also fixed an issue, where the volume update would refuse to do its thing despite it being the same id that was used on launch.
=> Made use of node_id_

include/modules/clock.hpp, src/modules/clock.cpp
Hi @Alexays , this PR should fix #2073
=> #2073 today style not applied to new date 1 day after starting waybar

src/modules/backlight.cpp
=> backlight: support tooltip

src/modules/river/tags.cpp
adds the set-tags and toggle-tags setting so it's possible to have different tags set vs toggled. This enables the use of e.g. sticky tags
Also clean-up the code a bit.
=> river/tags: refactor to support special purpose tags

include/modules/dwl/tags.hpp, protocol/dwl-ipc-unstable-v2.xml, protocol/meson.build, src/modules/dwl/tags.cpp
Since [MadcowOG](https://github.com/MadcowOG) change the IPC patch for DWL - I also updated the DWL module to match it.
This targets [version 2](https://github.com/djpohly/dwl/compare/main...madcowog:ipc-v2.patch) of the path
=> Update to new ipc version

src/modules/cava.cpp, src/modules/wlr/workspace_manager.cpp
Hi @Alexays , this PR just a couple of small fixes.
=> Small performance fixies

src/modules/sway/workspaces.cpp
Resolves: https://github.com/Alexays/Waybar/issues/2188
=> [sway/workspaces] fix: change icons priority

man/waybar-temperature.5.scd, src/modules/temperature.cpp
So user can share configuration file among different machines with different hardware configurations.
=> support multiple items in hwmon-path of temperature module

src/modules/hyprland/window.cpp, src/modules/wlr/taskbar.cpp
Resolves: https://github.com/Alexays/Waybar/issues/2214
=> [wrl/taskbare] fix: use empty class for empty taskbar

src/modules/hyprland/window.cpp, src/modules/hyprland/workspaces.cpp
Workspaces were not being deleted from the box
=> Fixes for hyprland/workspaces

src/modules/gamemode.cpp, src/modules/hyprland/workspaces.cpp, src/modules/sway/window.cpp, src/modules/upower/upower.cpp, src/modules/upower/upower_tooltip.cpp, src/util/gtk_icon.cpp
Getting the ID of a nullptr workspace segfaults.
=> Fix rare segfault when destroying workspace

include/modules/image.hpp, man/waybar-image.5.scd, src/modules/image.cpp
I modified the image module to allow users setting tooltips for image modules with scripts.
Hope there's someone can help me review this.
Thanks!
=> Image tooltip

include/modules/mpris/mpris.hpp
Maybe we should force the compilation to fail if there are warnings? :)
=> Fixed build warnings

include/util/sleeper_thread.hpp
=> Ensure signal is disconnected in destructor

man/waybar-cava.5.scd, man/waybar.5.scd.in, meson.build
Hi @Alexays . I've added manual page for cava module
=> cava man page

include/modules/sway/workspaces.hpp, man/waybar-sway-workspaces.5.scd, src/modules/sway/workspaces.cpp
Resolves: comments in https://github.com/Alexays/Waybar/issues/2188
=> [sway/workspaces] feat: add high-priority-named optiion

.github/workflows/linux.yml, meson.build, src/modules/backlight.cpp
Is there a reason we're still on C++17?
=> Use C++20 by default

include/modules/keyboard_state.hpp, man/waybar-keyboard-state.5.scd, src/modules/keyboard_state.cpp
fix #2082 
fix https://github.com/Alexays/Waybar/issues/2215#issuecomment-1587163718
fix #2137
=> feat(keyboard-state): add binding-keys options

man/waybar-hyprland-workspaces.5.scd, src/modules/hyprland/workspaces.cpp
Fixes #2430 
I haven't tested this yet because I'm still having trouble compiling due to fmt (#2415), but I'm pretty sure this will work fine. Maybe someone else can test it?
=> hyprland/workspaces: Add "empty" icon and class

src/modules/hyprland/workspaces.cpp
=> Hyprland/workspaces: add urgent icon

src/modules/clock.cpp
Hi @Alexays , after C++20 chrono refactoring , it's not able to build project using clang.
This PR fixes clang errors and should solve:
1. #2665
2. #2659 - comments from @Artturin - https://github.com/Alexays/Waybar/pull/2659#issuecomment-1807069923
=> Happy clang. fmt9-10

man/waybar-hyprland-submap.5.scd, src/modules/hyprland/submap.cpp
=> Add style classes for hyprland/submap

meson.build, src/group.cpp, src/modules/cava.cpp, src/modules/hyprland/submap.cpp, subprojects/cava.wrap
Hi Alex, it's just libcava bump
=> libcava bump 0.10.1

include/modules/cpu.hpp, man/waybar-cpu.5.scd, src/modules/cpu.cpp
=> Revert "Add style class for CPU state"

include/modules/sway/workspaces.hpp, man/waybar-sway-workspaces.5.scd, src/modules/sway/workspaces.cpp
=> Revert "Implement windows formating in sway/workspaces"

nix/default.nix
The flake no longer builds after the recent meson changes, this fixes the build.
Also, catch2_3 is now 3.5.2 in nixos-unstable, so the previous override is no longer needed.
I wasn't sure what formatter should be used, ended up used nixpkgs-fmt.
=> nix: update libcava version and removal of gtk-layer-shell meson option

include/modules/sway/workspaces.hpp, man/waybar-sway-workspaces.5.scd, src/modules/sway/workspaces.cpp
This implementation mimics to some extend the implementation of hyprland
=> Implement windows formating in sway/workspaces

resources/custom_modules/mediaplayer.py
Adds option to exclude a list of players (comma separated list)
Example:
```
mediaplayer.py -x firefox,spotify
```
I included these changes because I really like this tool, but I am not interested in Firefox's media player status in my waybar. This feature seems very basic and I wanted to contribute to this great repo.
=> mediaplayer: add exclude player option

src/modules/sway/workspaces.cpp
=> Fix peristant workspaces for sway

README.md
* Change repology badge header  
* Use 3 columns instead of 1 to display badge
Preview: https://github.com/luzpaz/Waybar/blob/repology-badge/README.md#installation
=> README: tweak repology badge

src/modules/hyprland/workspaces.cpp
Fixes segfault introduced by #2968 .
I commented about this segfault in the original PR but it wasn't addressed.
=> Fixed segfault

src/modules/sway/workspaces.cpp
=> Also consider floating nodes when checking for flags

src/modules/sway/workspaces.cpp
Fixes a regression added in #3001
=> fix(sway/workspaces): visible class doesn't work

README.md, include/modules/dwl/window.hpp, man/waybar-dwl-window.5.scd, man/waybar.5.scd.in, meson.build, src/factory.cpp, src/modules/dwl/tags.cpp, src/modules/dwl/window.cpp
Works through ipc patch, same as dwl/tags
=> Add dwl/window module

src/modules/custom.cpp
=> Escape tooltip in custom module

src/AModule.cpp
=> fix(#3162): hover event did not propagate causing issues

include/modules/upower.hpp, src/modules/upower.cpp
Hi @Alexays , 
This MR solves #3223  . The problem was presented before refactoring. Upower module was not aware about whether system is going to sleep and what to do with presented devices.
=> Upower. Fix segmentation fault

meson.build, src/modules/cava.cpp, subprojects/cava.wrap
Hi @Alexays , this MR solves:
1. #3276
2. #3288
3. And possible can fix #3277
=> cava bump: 0.10.2

src/modules/clock.cpp, src/modules/mpris/mpris.cpp, src/modules/privacy/privacy.cpp
1. along with some clang-tidy issue in the file.
2. with the fix for privacy module: https://github.com/Alexays/Waybar/pull/3244
=> fix mpris: hide on current player vanished

include/AModule.hpp, include/modules/clock.hpp, include/modules/hyprland/workspaces.hpp, include/util/clara.hpp, include/util/format.hpp, src/modules/bluetooth.cpp, src/modules/clock.cpp, src/modules/cpu_usage/linux.cpp, src/modules/dwl/tags.cpp, src/modules/hyprland/backend.cpp, src/modules/hyprland/workspaces.cpp, src/modules/memory/bsd.cpp, src/modules/wlr/workspace_manager.cpp, test/utils/SafeSignal.cpp
Remove deprecated config value. Was deprecated 9 months ago. https://github.com/Alexays/Waybar/commit/c9e1899594f9c36dc7fc7bc201238438d59ca6ff
Clean up old log statement left in from testing PR
Clean up failing clang-format check
=> hyprland/workspaces: remove deprecated property

include/AModule.hpp, include/util/backlight_backend.hpp, include/util/regex_collection.hpp, src/AAppIconLabel.cpp, src/ALabel.cpp, src/AModule.cpp, src/bar.cpp, src/client.cpp, src/config.cpp, src/group.cpp, src/main.cpp, src/util/audio_backend.cpp, src/util/backlight_backend.cpp, src/util/portal.cpp, src/util/prepare_for_sleep.cpp, src/util/regex_collection.cpp, src/util/sanitize_str.cpp, src/util/ustring_clen.cpp
Just resolving a bunch of the clang-tidy warnings/fixes throughout src and src/util.
=> treewide: clang-tidy

src/modules/temperature.cpp
No big deal, just noticed this.
=> (temperature) fix clang-tidy lint .

include/modules/sway/workspaces.hpp, man/waybar-sway-workspaces.5.scd, src/modules/sway/workspaces.cpp
Follow up to https://github.com/Alexays/Waybar/pull/3364 and https://github.com/Alexays/Waybar/pull/3407
=> sway/workspaces: remove deprecated field and ignore empty rewrite rules

src/modules/pulseaudio.cpp
This looks like a regression from f4ffb21c
=> fix: check format-source before use

src/modules/power_profiles_daemon.cpp
=> chore: update power_profiles_daemon.cpp

include/modules/temperature.hpp, man/waybar-temperature.5.scd, src/modules/temperature.cpp
Adds simple warning on top of normal and critical states.
=> Add warning threshold to temperature module

include/modules/sway/workspaces.hpp, src/modules/sway/workspaces.cpp
Fixes #3763.
Also a little code simplications while we're at it.
=> sway: fix "Mapping is not an object" warning

src/modules/hyprland/window.cpp
fix:
https://github.com/Alexays/Waybar/issues/2693
i think it is the same problem with https://github.com/Alexays/Waybar/pull/2789
=> fix: hyprland/window get empty ipc json data

src/modules/hyprland/window.cpp
This gives the user the option to display a tooltip on the hyprland/window module. The format specified in the 'tooltip-format' option is used for this. If it is not specified, the rewritten window title is shown instead.
This feature is useful for when you specify a max-length and want to see the full title of the window. It fixes #2898
=> [hyprland/window] enable tooltip for hyprland window module

src/modules/hyprland/workspaces.cpp
Should fix #3834
@jbirnick can you test this PR?
=> Fix workspacerules not taking into account defaultName

man/waybar-backlight-slider.5.scd
fixes #4015 
Typo in manpage, config example doesn't work.
=> fix manpage for backlight/slider

src/util/audio_backend.cpp
Getting crashes when called before we have proper information.
Not sure if its the best way, but it resolved crashing for me on boot. (which somehow also caused thunderbird to crash)
=> audio_backend: fix crash

src/modules/wlr/taskbar.cpp
=> wlr/taskbar: find icon by title as fallback

nix/default.nix
Fix nix build follow up to https://github.com/Alexays/Waybar/pull/4056
Have formatting fixes in https://github.com/Alexays/Waybar/pull/4025 
@Alexays
=> nix: cava bump (fix nix build)

default.nix, flake.nix, nix/default.nix, src/modules/sni/item.cpp, src/modules/sni/tray.cpp, src/modules/temperature.cpp, src/modules/wlr/taskbar.cpp
Also format files that haven't been getting formatted.
=> flake.nix: add treefmt; treewide: clang and nix format

man/waybar-idle-inhibitor.5.scd
Copied this from another man page.
If this is correct I can try adding this to some of the other man pages.
=> Add idle_inhibitor style docs.

src/modules/clock.cpp
Closes #3132
Fixed the issue by counting the number of wide characters and using it when padding the calendar line.
My reference for how to check for wide characters was [src/modules/mpris/mpris.cpp L210](https://github.com/Alexays/Waybar/blob/0.12.0/src/modules/mpris/mpris.cpp#L204-L219).
=> Fix calendar extra padding if there are wide characters

include/modules/hyprland/workspaces.hpp, man/waybar-hyprland-workspaces.5.scd, src/modules/hyprland/workspaces.cpp
=> hyprland workspaces: Add sorting Special Centered

src/modules/wlr/taskbar.cpp
=> add rewrite to wlr tooltip

src/modules/bluetooth.cpp
=> Revert "Bluetooth module: fetch battery percentage from upower if not found from bluez"

include/modules/hyprland/backend.hpp, nix/default.nix
Fixes:
https://github.com/Alexays/Waybar/issues/4218
https://github.com/Alexays/Waybar/issues/4215
=> Added IPC fix and Nix GPS fix

src/util/gtk_icon.cpp
Fixes issue https://github.com/Alexays/Waybar/issues/4231
=> Fix default icon in tray module

src/modules/hyprland/language.cpp
Fix #4229 as per https://github.com/Alexays/Waybar/pull/4068#issuecomment-3012980699
=> fix hyprland/language layout parsing

src/modules/battery.cpp
=> Change default tooltip for the battery module.

src/ALabel.cpp
The problem is commit 2b552f7 which introduces a minimum interval time of 1ms. But then, in modules/custom.cpp, the constructor tests if the interval is nonzero to distinguish continuous workers from delay workers.
This PR preserves the default value 0.
=> Fixes #4521 and #4522

src/modules/network.cpp
Fix the unit calculation error introduced in this pr
https://github.com/Alexays/Waybar/pull/4390
=> fix: Correct the error in converting network speed units
